import type { Project } from "../../document";
import { createId } from "../../document";
import { DEMO_IMG } from "../assets";
import { b, page, shell, id, outputsFor } from "../helpers";
import { northlineStyleExtras, nlText, NL } from "../brand/northlineStyles";
import { contractLong } from "./contracts";

export { affidavit } from "./affidavit";
export { contractEmployees, contractLong } from "./contracts";
export { legalDecision } from "./legalDecision";
export {
  LEGAL,
  legalLetterhead,
  signaturePair,
  urlQrFooter,
} from "./legalShared";
export { rentalCar, rentalHouse } from "./rentals";

export { hospitalBill } from "./hospitalBill";
export { ratesFines } from "./ratesFines";
export { companyChart } from "./orgChart";

export function letter(): Project {
  const headerBlocks = [
    b("shape", {
      name: "Letterhead",
      x: 0,
      y: 0,
      w: 720,
      h: 88,
      content: { shape: "rect", filled: true },
      style: { background: NL.accentSoft },
      zIndex: 0,
    }),
    b("picture", {
      name: "Logo",
      x: 40,
      y: 28,
      w: 140,
      h: 40,
      content: { src: DEMO_IMG.logoMark, alt: "Northline" },
      zIndex: 1,
    }),
    b("text", {
      name: "Sender",
      x: 400,
      y: 28,
      w: 260,
      h: 52,
      content: {
        text: "Northline Systems\n14 Harbor Lane, Antwerp\nops@northline.example",
      },
      style: { ...nlText("nl-caption"), textAlign: "right" },
      zIndex: 1,
    }),
    b("shape", {
      name: "Top rule",
      x: 40,
      y: 84,
      w: 620,
      h: 4,
      content: { shape: "rect", filled: true },
      style: { background: NL.accent },
      zIndex: 1,
    }),
  ];
  const footerBlocks = [
    b("text", {
      name: "Confidential",
      x: 40,
      y: 14,
      w: 640,
      h: 20,
      content: {
        text: "Confidential — intended solely for {{company}}. {{ref}}",
      },
      style: { ...nlText("nl-fineprint"), textAlign: "center" },
    }),
  ];
  return shell(
    {
      name: "Formal business letter",
      author: "Northline Correspondence",
      subject: "US Letter letterhead with merge fields",
      description:
        "Northline letterhead with EN/FR body via document language (ADR 0015).",
    },
    [
      page("Letter", [
        b("date", {
          name: "Printed today",
          x: 480,
          y: 108,
          w: 160,
          h: 22,
          content: { source: "today", format: "short", path: "date", fixed: "" },
          style: { ...nlText("nl-body-tight"), textAlign: "right", color: "#5c6570" },
        }),
        b("text", {
          name: "Date",
          x: 40,
          y: 108,
          w: 200,
          h: 22,
          content: { text: "{{date|date:long}}" },
          style: { ...nlText("nl-body-tight") },
        }),
        b("paragraph", {
          name: "Recipient",
          x: 40,
          y: 140,
          w: 280,
          h: 64,
          content: {
            text: "{{title}} {{name}}\n{{company}}\n{{address}}",
          },
          style: { ...nlText("nl-body-tight") },
        }),
        b("text", {
          name: "Subject line",
          x: 40,
          y: 220,
          w: 520,
          h: 24,
          content: { text: "Re: {{subject}}" },
          style: { ...nlText("nl-h3") },
        }),
        b("paragraph", {
          name: "Body EN",
          x: 40,
          y: 256,
          w: 620,
          h: 280,
          content: {
            text: "Dear {{title}} {{name}},\n\nThank you for your inquiry regarding {{topic}}. We are pleased to confirm availability for the engagement described in our proposal dated {{date|date:long}}.\n\nPlease find the enclosed schedule. We remain at your disposal for any clarification.\n\nShould you require an earlier kickoff, we can rearrange the first milestone without affecting the overall fee schedule. Our delivery lead will contact your team within two business days of countersignature.\n\nPrinted {{env.today|date:short}}.",
          },
          style: { ...nlText("nl-body"), lineHeight: 1.55 },
          condition: "vars.language != 'fr'",
        }),
        b("paragraph", {
          name: "Body FR",
          x: 40,
          y: 256,
          w: 620,
          h: 280,
          content: {
            text: "Madame, Monsieur {{name}},\n\nNous vous remercions de votre demande concernant {{topic}}. Nous confirmons notre disponibilité pour la mission décrite dans notre proposition datée du {{date|date:long}}.\n\nVeuillez trouver ci-joint le calendrier. Nous restons à votre disposition pour toute précision.\n\nSi un démarrage anticipé est nécessaire, nous pouvons réaménager le premier jalon sans modifier le barème. Notre responsable livraison contactera votre équipe sous deux jours ouvrés après contre-signature.\n\nImprimé le {{env.today|date:short}}.",
          },
          style: { ...nlText("nl-body"), lineHeight: 1.55 },
          condition: "vars.language == 'fr'",
        }),
        b("text", {
          name: "Closing EN",
          x: 40,
          y: 560,
          w: 200,
          h: 40,
          content: { text: "Yours sincerely,\n{{signer}}" },
          style: { ...nlText("nl-body") },
          condition: "vars.language != 'fr'",
        }),
        b("text", {
          name: "Closing FR",
          x: 40,
          y: 560,
          w: 280,
          h: 40,
          content: { text: "Veuillez agréer nos salutations distinguées,\n{{signer}}" },
          style: { ...nlText("nl-body") },
          condition: "vars.language == 'fr'",
        }),
        b("signature", {
          name: "Signature",
          x: 40,
          y: 600,
          w: 220,
          h: 96,
          content: {
            mode: "preset",
            src: DEMO_IMG.signature,
            label: "Authorized signature",
            caption: "{{signer}}\n{{role|default:Account Executive}}",
            signedAt: "{{env.today|date:short}}",
            showLine: true,
          },
          style: { fontSize: 11, color: "#5c6570", fontFamily: "ui" },
        }),
      ], { margins: { top: 0, right: 40, bottom: 48, left: 40 } }),
      page("Continuation", [
        b("text", {
          name: "Cont reference",
          x: 400,
          y: 100,
          w: 260,
          h: 36,
          content: { text: "{{signer}} · {{ref}}\nPage 2 of 2" },
          style: { ...nlText("nl-caption"), textAlign: "right" },
          zIndex: 1,
        }),
        b("text", {
          name: "Recap subject",
          x: 40,
          y: 140,
          w: 640,
          h: 22,
          content: { text: "Re: {{subject}} — continued" },
          style: { ...nlText("nl-h3") },
        }),
        b("paragraph", {
          name: "Follow-up body EN",
          x: 40,
          y: 178,
          w: 640,
          h: 220,
          content: {
            text: "Dear {{title}} {{name}},\n\nFollowing our schedule, the next steps are straightforward: countersign the enclosed copy, confirm a kickoff slot, and grant read access to the systems listed in Schedule A.\n\nOur team typically completes onboarding within two weeks of signature. During that window we hold a weekly status call and share progress in a shared channel, so your stakeholders always know where things stand.\n\nIf the commercial terms need a small amendment, please mark the PDF and return it — we can usually turn a revised schedule within one business day.",
          },
          style: { ...nlText("nl-body"), lineHeight: 1.55 },
          condition: "vars.language != 'fr'",
        }),
        b("paragraph", {
          name: "Follow-up body FR",
          x: 40,
          y: 178,
          w: 640,
          h: 220,
          content: {
            text: "Madame, Monsieur {{name}},\n\nSuite à notre calendrier, les prochaines étapes sont simples : contre-signer l’exemplaire joint, confirmer un créneau de lancement, et accorder l’accès en lecture aux systèmes de l’Annexe A.\n\nNotre équipe termine généralement l’intégration en deux semaines. Pendant cette période, un point hebdomadaire et un canal partagé tiennent vos parties prenantes informées.\n\nSi les conditions commerciales nécessitent un léger ajustement, annotez le PDF et renvoyez-le — nous livrons généralement un calendrier révisé sous un jour ouvré.",
          },
          style: { ...nlText("nl-body"), lineHeight: 1.55 },
          condition: "vars.language == 'fr'",
        }),
        b("text", {
          name: "Enclosures label",
          x: 40,
          y: 420,
          w: 200,
          h: 20,
          content: { text: "Enclosures" },
          style: { ...nlText("nl-h3") },
        }),
        b("list", {
          name: "Enclosures",
          x: 40,
          y: 448,
          w: 520,
          h: 120,
          content: {
            items: [
              "Countersignature copy (2 × A4)",
              "Schedule A — systems & access list",
              "Onboarding checklist for {{company}}",
              "Data-processing addendum (draft)",
            ],
            markerColor: NL.accent,
          },
          style: { ...nlText("nl-caption"), lineHeight: 1.5, color: "#3d4a5c" },
        }),
        b("paragraph", {
          name: "Postscript",
          x: 40,
          y: 590,
          w: 640,
          h: 80,
          content: {
            text: "P.S. If anyone else at {{company}} should be part of the kickoff, simply reply to this letter and we will extend the invitation. We are also happy to walk through the schedule on a short call at your convenience.",
          },
          style: { ...nlText("nl-caption"), lineHeight: 1.5, color: "#3d4a5c" },
          condition: "vars.language != 'fr'",
        }),
        b("text", {
          name: "Closing again",
          x: 40,
          y: 700,
          w: 280,
          h: 40,
          content: { text: "With kind regards,\n{{signer}}" },
          style: { ...nlText("nl-body") },
        }),
      ], { margins: { top: 0, right: 40, bottom: 48, left: 40 } }),
    ],
    {
      artboard: "letter",
      outputs: outputsFor("preview", "pdf", "print"),
      ...northlineStyleExtras("en"),
      pageChrome: {
        header: {
          enabled: true,
          height: 88,
          background: NL.accentSoft,
          blocks: headerBlocks,
        },
        footer: {
          enabled: true,
          height: 48,
          blocks: footerBlocks,
        },
      },
    },
  );
}

/** @deprecated Retained as a reference for older saved demo layouts. */
export function legacyContract(): Project {
  return shell(
    {
      name: "Service agreement",
      author: "Northline Legal",
      subject: "Two-page contract with schedule table",
      description:
        "Conventional MSA-style first pages: parties, clauses, fees table, approval stamp, signature block.",
    },
    [
      page(
        "Terms",
        [
          b("shape", {
            name: "Letterhead",
            x: 0,
            y: 0,
            w: 720,
            h: 72,
            content: { shape: "rect", filled: true },
            style: { background: "#f3f7f6" },
            zIndex: 0,
            pin: { top: true, left: true, right: true },
          }),
          b("text", {
            name: "Title",
            x: 40,
            y: 24,
            w: 500,
            h: 28,
            content: { text: "MASTER SERVICES AGREEMENT" },
            style: { fontSize: 18, fontWeight: 700, color: "#1c2430" },
            zIndex: 1,
          }),
          b("text", {
            name: "Ref",
            x: 40,
            y: 88,
            w: 620,
            h: 18,
            content: { text: "Agreement No. {{contract_id}} · Effective {{start_date|date:long}}" },
            style: { fontSize: 11, color: "#5c6570" },
          }),
          b("shape", {
            name: "Top rule",
            x: 40,
            y: 116,
            w: 620,
            h: 3,
            content: { shape: "rect", filled: true },
            style: { background: "#0f6b63" },
          }),
          b("paragraph", {
            name: "Parties",
            x: 40,
            y: 136,
            w: 620,
            h: 88,
            content: {
              text: "This Agreement is entered into by {{provider}} (“Provider”) and {{client}} (“Client”). Each party represents it has authority to bind its organization.\n\nThe parties intend this document, together with Schedule A, to constitute the entire agreement concerning the services described herein.",
            },
            style: { fontSize: 11, color: "#1c2430", lineHeight: 1.5 },
          }),
          b("list", {
            name: "Key terms",
            x: 40,
            y: 244,
            w: 400,
            h: 140,
            content: {
              items: [
                "1. Services as described in Schedule A",
                "2. Fees payable within {{net_days}} days",
                "3. Confidentiality for {{term_years}} years",
                "4. Governing law: {{jurisdiction}}",
                "5. Notices in writing to the addresses on file",
              ],
            },
            style: { fontSize: 11, color: "#1c2430", lineHeight: 1.45 },
          }),
          b("picture", {
            name: "Stamp",
            x: 520,
            y: 244,
            w: 72,
            h: 72,
            content: { src: DEMO_IMG.stamp, alt: "Approved" },
            condition: "data.approved == 'yes'",
          }),
          b("paragraph", {
            name: "Clause 5",
            x: 40,
            y: 408,
            w: 620,
            h: 140,
            content: {
              text: "5. Limitation of liability. Except for willful misconduct, Provider’s aggregate liability under this Agreement shall not exceed the fees paid by Client in the twelve (12) months preceding the claim. Neither party is liable for indirect or consequential damages.\n\nClient remains responsible for its own data backups and for verifying that deliverables meet the acceptance criteria in Schedule A before production use.",
            },
            style: { fontSize: 11, color: "#1c2430", lineHeight: 1.5 },
          }),
          b("paragraph", {
            name: "Clause 6",
            x: 40,
            y: 568,
            w: 620,
            h: 120,
            content: {
              text: "6. Termination. Either party may terminate for convenience with {{notice_days}} days’ written notice, or immediately for material breach not cured within fifteen (15) days of notice.\n\nUpon termination, Provider will deliver work-in-progress and Client will pay for accepted services through the effective date.",
            },
            style: { fontSize: 11, color: "#1c2430", lineHeight: 1.5 },
          }),
          b("paragraph", {
            name: "Clause 7",
            x: 40,
            y: 708,
            w: 620,
            h: 100,
            content: {
              text: "7. General. If any provision is held unenforceable, the remainder stays in force. Amendments must be signed by both parties. This Agreement may be executed in counterparts, including electronic signature.",
            },
            style: { fontSize: 11, color: "#1c2430", lineHeight: 1.5 },
          }),
          b("text", {
            name: "Confidential",
            x: 40,
            y: 900,
            w: 640,
            h: 20,
            content: {
              text: "Confidential — {{provider}} / {{client}} · {{contract_id}}",
            },
            style: { fontSize: 9, color: "#5c6570", textAlign: "center" },
            pin: { bottom: true, left: true, right: true },
          }),
        ],
        { margins: { top: 0, right: 40, bottom: 48, left: 40 } },
      ),
      page("Schedule A", [
        b("shape", {
          name: "Header bar",
          x: 0,
          y: 0,
          w: 720,
          h: 56,
          content: { shape: "rect", filled: true },
          style: { background: "#f3f7f6" },
          zIndex: 0,
          pin: { top: true, left: true, right: true },
        }),
        b("text", {
          name: "Schedule title",
          x: 40,
          y: 18,
          w: 500,
          h: 24,
          content: { text: "Schedule A — Fees & deliverables" },
          style: { fontSize: 15, fontWeight: 700, color: "#1c2430" },
          zIndex: 1,
        }),
        b("table", {
          name: "Fee table",
          x: 40,
          y: 80,
          w: 620,
          h: 160,
          content: {
            rows: 4,
            cols: 4,
            cells: [
              ["Item", "Qty", "Unit", "Amount"],
              ["{{line1}}", "{{qty1}}", "{{unit1}}", "{{amt1}}"],
              ["{{line2}}", "{{qty2}}", "{{unit2}}", "{{amt2}}"],
              ["Total", "", "", "{{total}}"],
            ],
          },
          style: { fontSize: 11, color: "#1c2430" },
        }),
        b("paragraph", {
          name: "Acceptance",
          x: 40,
          y: 268,
          w: 620,
          h: 120,
          content: {
            text: "Acceptance. Client will review each deliverable within ten (10) business days. Silence after that window constitutes acceptance. Rejected items must cite specific Schedule A criteria; Provider will remediate once at no extra fee when the rejection is timely and material.\n\nExpenses. Pre-approved travel and third-party costs are billed at cost. Overtime requested by Client outside agreed hours is billed at 1.5× the listed unit rate.",
          },
          style: { fontSize: 11, color: "#1c2430", lineHeight: 1.5 },
        }),
        b("paragraph", {
          name: "Payment notes",
          x: 40,
          y: 412,
          w: 620,
          h: 88,
          content: {
            text: "Invoices reference {{contract_id}} and are due net {{net_days}}. Late amounts may accrue interest at the statutory rate. Disputes must be raised in writing before the due date or the undisputed portion remains payable.",
          },
          style: { fontSize: 11, color: "#1c2430", lineHeight: 1.5 },
        }),
        b("signature", {
          name: "Provider signature",
          x: 40,
          y: 540,
          w: 280,
          h: 120,
          content: {
            mode: "preset",
            src: DEMO_IMG.signature,
            label: "Provider",
            caption:
              "{{signer_name|default:Authorized signatory}}\n{{signer_role|default:Provider}}",
            signedAt: "{{signed_at|date:short}}",
            showLine: true,
          },
          style: { fontSize: 11, color: "#5c6570", fontFamily: "ui" },
        }),
        b("signature", {
          name: "Client signature",
          x: 360,
          y: 540,
          w: 280,
          h: 120,
          content: {
            mode: "open",
            src: "",
            label: "Client — sign here",
            caption: "{{client}}\nPrint name · Title",
            signedAt: "",
            showLine: true,
          },
          style: { fontSize: 11, color: "#5c6570", fontFamily: "ui" },
        }),
        b("text", {
          name: "Footer",
          x: 40,
          y: 900,
          w: 640,
          h: 20,
          content: { text: "Schedule A · {{contract_id}} · {{start_date|date:short}}" },
          style: { fontSize: 9, color: "#5c6570", textAlign: "center" },
          pin: { bottom: true, left: true, right: true },
        }),
      ]),
    ],
    { outputs: outputsFor("preview", "pdf", "print") },
  );
}

export function contract(): Project {
  return contractLong();
}

export function invoice(): Project {
  const bankId = createId();
  const primaryId = createId();
  return shell(
    {
      name: "Commercial invoice",
      author: "Northline Finance",
      subject: "Invoice with line items and totals",
      description:
        "B2B invoice: bill-to, ship-to, SKU line table, tax, bank lookup, product file pack per line.",
    },
    [
      page("Invoice", [
        b("shape", {
          name: "Letterhead",
          x: 0,
          y: 0,
          w: 720,
          h: 80,
          content: { shape: "rect", filled: true },
          style: { background: "#f3f7f6" },
          zIndex: 0,
          pin: { top: true, left: true, right: true },
        }),
        b("picture", {
          name: "Logo",
          x: 40,
          y: 22,
          w: 130,
          h: 38,
          content: { src: DEMO_IMG.logoMark, alt: "Northline" },
          zIndex: 1,
        }),
        b("text", {
          name: "Invoice label",
          x: 420,
          y: 18,
          w: 240,
          h: 40,
          content: { text: "INVOICE\n{{invoice_no}}" },
          style: {
            fontSize: 20,
            fontWeight: 700,
            color: "#1c2430",
            textAlign: "right",
          },
          zIndex: 1,
        }),
        b("text", {
          name: "Meta",
          x: 420,
          y: 96,
          w: 240,
          h: 40,
          content: {
            text: "Date {{invoice_date|date:short}}\nDue {{due_date|date:short}}",
          },
          style: { fontSize: 11, color: "#5c6570", textAlign: "right" },
        }),
        b("paragraph", {
          name: "Bill to",
          x: 40,
          y: 100,
          w: 280,
          h: 80,
          content: {
            text: "Bill to\n{{bill_name}}\n{{bill_company}}\n{{bill_address}}",
          },
          style: { fontSize: 11, color: "#1c2430", lineHeight: 1.45 },
        }),
        b("paragraph", {
          name: "Ship to",
          x: 360,
          y: 148,
          w: 280,
          h: 64,
          content: {
            text: "Ship to\n{{ship_name}}\n{{ship_address}}",
          },
          style: { fontSize: 11, color: "#1c2430", lineHeight: 1.45 },
        }),
        b("table", {
          name: "Lines",
          x: 40,
          y: 236,
          w: 620,
          h: 200,
          content: {
            header: true,
            zebra: true,
            sourcePath: "line_items",
            rows: 2,
            cols: 5,
            cells: [
              ["SKU", "Description", "Qty", "Rate", "Amount"],
              [
                "{{sku}}",
                "{{description}}",
                "{{qty}}",
                "{{rate|currency:EUR}}",
                "{{amount|currency:EUR}}",
              ],
            ],
            headerBackground: "#e8f0ee",
            cellPadding: 8,
          },
          style: { fontSize: 10.5 },
        }),
        b("table", {
          name: "Totals",
          x: 400,
          y: 460,
          w: 260,
          h: 110,
          content: {
            rows: 3,
            cols: 2,
            cells: [
              ["Tax ({{tax_pct}}%)", "{{tax|currency:EUR}}"],
              ["Shipping", "{{shipping|currency:EUR}}"],
              ["Total {{currency}}", "{{total|currency:EUR}}"],
            ],
            showBorders: true,
            borderColor: "#cfc8bc",
          },
          style: { fontSize: 12, fontWeight: 600 },
        }),
        b("paragraph", {
          name: "Terms",
          x: 40,
          y: 460,
          w: 320,
          h: 140,
          content: {
            text: "Payment terms: {{terms}}\nBank: {{bank.bank_name}}\nIBAN: {{bank.iban}}\nBIC: {{bank.bic}}\nAmount due: {{total|currency:EUR}} ({{currency}})\nQuestions: billing@northline.example\n\nInclude {{invoice_no}} on the transfer memo.\n\nProduct pack ({{pack_file_count}} files) — page 3.\nGenerated {{env.today|date:short}}.",
          },
          style: { fontSize: 10, color: "#5c6570", lineHeight: 1.5 },
        }),
        b("text", {
          name: "Past due",
          x: 40,
          y: 628,
          w: 500,
          h: 28,
          content: {
            text: "STATUS: PAST DUE — please remit {{total|currency:EUR}} immediately.",
          },
          style: { fontSize: 12, fontWeight: 700, color: "#b45309" },
          condition: "status == 'past_due'",
        }),
        b("paragraph", {
          name: "Thanks note",
          x: 40,
          y: 680,
          w: 620,
          h: 80,
          content: {
            text: "Thank you for your business. Page two covers remittance; page three lists specification sheets, certificates, and delivery notes for each SKU.",
          },
          style: { fontSize: 11, color: "#3d4a5c", lineHeight: 1.5 },
        }),
        b("text", {
          name: "Footer",
          x: 40,
          y: 900,
          w: 640,
          h: 18,
          content: { text: "{{bill_company}} · {{invoice_no}} · Page 1 of 3" },
          style: { fontSize: 9, color: "#5c6570", textAlign: "center" },
          pin: { bottom: true, left: true, right: true },
        }),
      ]),
      page("Notes & remittance", [
        b("shape", {
          name: "Header bar",
          x: 0,
          y: 0,
          w: 720,
          h: 56,
          content: { shape: "rect", filled: true },
          style: { background: "#f3f7f6" },
          zIndex: 0,
          pin: { top: true, left: true, right: true },
        }),
        b("text", {
          name: "Remit title",
          x: 40,
          y: 18,
          w: 500,
          h: 28,
          content: {
            text: "Invoice {{invoice_no}} — remittance · {{env.today|date:short}}",
          },
          style: { fontSize: 16, fontWeight: 700, color: "#1c2430" },
          zIndex: 1,
        }),
        b("table", {
          name: "Remit stub",
          x: 40,
          y: 80,
          w: 620,
          h: 120,
          content: {
            header: false,
            rows: 4,
            cols: 2,
            cells: [
              ["Amount due ({{currency}})", "{{total|currency:EUR}}"],
              ["Due date", "{{due_date|date:short}}"],
              ["Terms", "{{terms}}"],
              ["Reference", "{{invoice_no}} / {{bill_name}}"],
            ],
          },
          style: { fontSize: 12 },
        }),
        b("text", {
          name: "Bank label",
          x: 40,
          y: 228,
          w: 200,
          h: 20,
          content: { text: "Payment details" },
          style: { fontSize: 12, fontWeight: 700, color: "#1c2430" },
        }),
        b("paragraph", {
          name: "Bank block",
          x: 40,
          y: 256,
          w: 360,
          h: 100,
          content: {
            text: "{{bank.bank_name}}\nIBAN: {{bank.iban}}\nBIC: {{bank.bic}}\nReference: {{invoice_no}}\nAmount: {{total|currency:EUR}}",
          },
          style: { fontSize: 11, lineHeight: 1.5, color: "#3d4a5c" },
          variants: [
            {
              id: id(),
              output: "email",
              content: {
                text: "Pay online with reference {{invoice_no}} — amount {{total|currency:EUR}}. Bank details omitted in email copy.",
              },
            },
          ],
        }),
        b("shape", {
          name: "QR plate",
          x: 460,
          y: 252,
          w: 200,
          h: 108,
          content: { shape: "rect" },
          style: {
            background: "#f2f4f7",
            borderRadius: 6,
            borderWidth: 1,
            borderColor: "#d4d9e0",
          },
          condition: "output.kind != 'email'",
        }),
        b("text", {
          name: "QR hint",
          x: 472,
          y: 288,
          w: 176,
          h: 32,
          content: { text: "Scan-to-pay placeholder" },
          style: { fontSize: 10, color: "#5c6570", textAlign: "center" },
          zIndex: 2,
          condition: "output.kind != 'email'",
        }),
        b("text", {
          name: "Pay online strip",
          x: 460,
          y: 268,
          w: 200,
          h: 72,
          content: {
            text: "Pay online\n{{pay_url|default:https://northline.example/pay}}",
          },
          style: {
            fontSize: 12,
            fontWeight: 600,
            color: "#1c2430",
            textAlign: "center",
            background: "#e8f0ee",
            borderRadius: 6,
          },
          condition: "output.kind == 'email'",
          zIndex: 2,
        }),
        b("text", {
          name: "Line recap label",
          x: 40,
          y: 380,
          w: 300,
          h: 20,
          content: { text: "What am I paying for?" },
          style: { fontSize: 12, fontWeight: 700, color: "#1c2430" },
        }),
        b("table", {
          name: "Line recap",
          x: 40,
          y: 408,
          w: 620,
          h: 120,
          content: {
            header: true,
            zebra: true,
            sourcePath: "line_items",
            rows: 2,
            cols: 4,
            cells: [
              ["SKU", "Item", "Qty", "Amount"],
              ["{{sku}}", "{{description}}", "{{qty}}", "{{amount|currency:EUR}}"],
            ],
            headerBackground: "#e8f0ee",
          },
          style: { fontSize: 11.5, color: "#3d4a5c" },
        }),
        b("signature", {
          name: "Auth signature",
          x: 40,
          y: 560,
          w: 280,
          h: 120,
          content: {
            mode: "preset",
            src: DEMO_IMG.signature,
            label: "Authorized for Northline",
            caption:
              "{{signer_name|default:Billing Office}}\n{{signer_role|default:Accounts receivable}}",
            signedAt: "{{invoice_date|date:short}}",
            showLine: true,
          },
          style: { fontSize: 11, color: "#5c6570", fontFamily: "ui" },
        }),
        b("signature", {
          name: "Customer ack",
          x: 360,
          y: 560,
          w: 280,
          h: 120,
          content: {
            mode: "open",
            src: "",
            label: "Customer acknowledgment",
            caption: "{{bill_name}}\nSign · Date",
            signedAt: "",
            showLine: true,
          },
          style: { fontSize: 11, color: "#5c6570", fontFamily: "ui" },
        }),
        b("paragraph", {
          name: "Late policy",
          x: 40,
          y: 700,
          w: 620,
          h: 80,
          content: {
            text: "Late payments accrue interest at 1% per month above the ECB reference rate. Disputes must be raised in writing within 14 days of {{invoice_date|date:short}}. Cite {{invoice_no}} in all correspondence.",
          },
          style: { fontSize: 11, lineHeight: 1.55, color: "#5c6570" },
        }),
        b("text", {
          name: "Footer",
          x: 40,
          y: 900,
          w: 640,
          h: 20,
          content: { text: "billing@northline.example · Page 2 of 3" },
          style: { fontSize: 9, color: "#5c6570", textAlign: "center" },
          pin: { bottom: true, left: true, right: true },
        }),
      ]),
      page("Product pack", [
        b("shape", {
          name: "Header bar",
          x: 0,
          y: 0,
          w: 720,
          h: 56,
          content: { shape: "rect", filled: true },
          style: { background: "#f3f7f6" },
          zIndex: 0,
          pin: { top: true, left: true, right: true },
        }),
        b("text", {
          name: "Pack title",
          x: 40,
          y: 16,
          w: 520,
          h: 28,
          content: {
            text: "Product pack — {{invoice_no}} · {{pack_file_count}} files",
          },
          style: { fontSize: 16, fontWeight: 700, color: "#1c2430" },
          zIndex: 1,
        }),
        b("paragraph", {
          name: "Pack intro",
          x: 40,
          y: 72,
          w: 620,
          h: 56,
          content: {
            text: "Commercial documentation bundled with this invoice: specs, compliance letters, delivery notes, and signed schedules. Each row below maps to a billed SKU on page one.",
          },
          style: { fontSize: 11, lineHeight: 1.5, color: "#5c6570" },
        }),
        b("table", {
          name: "Product files",
          x: 40,
          y: 140,
          w: 620,
          h: 320,
          content: {
            header: true,
            zebra: true,
            sourcePath: "product_files",
            rows: 2,
            cols: 4,
            cells: [
              ["SKU", "Document", "Type", "Size"],
              [
                "{{sku}}",
                "{{document}}",
                "{{doc_type}}",
                "{{size_kb}} KB",
              ],
            ],
            headerBackground: "#e8f0ee",
            cellPadding: 6,
          },
          style: { fontSize: 10.5 },
        }),
        b("text", {
          name: "Per product label",
          x: 40,
          y: 480,
          w: 320,
          h: 20,
          content: { text: "Files per billed line" },
          style: { fontSize: 12, fontWeight: 700, color: "#1c2430" },
        }),
        b("repeat", {
          name: "Line file summary",
          x: 40,
          y: 508,
          w: 620,
          h: 56,
          content: {
            itemsPath: "line_items",
            itemVar: "item",
            blocks: [
              b("text", {
                name: "Line sku",
                x: 0,
                y: 0,
                w: 96,
                h: 22,
                content: { text: "{{sku}}" },
                style: { fontSize: 11, fontWeight: 700, color: "#0f6b63" },
              }),
              b("text", {
                name: "Line files",
                x: 104,
                y: 0,
                w: 500,
                h: 44,
                content: {
                  text: "{{description}}\n{{files_label}} · HS {{hs_code}}",
                },
                style: { fontSize: 10.5, lineHeight: 1.45, color: "#3d4a5c" },
              }),
              b("files", {
                name: "Line pack",
                x: 0,
                y: 28,
                w: 96,
                h: 24,
                content: { label: "{{file_count}} files", count: 1 },
              }),
            ],
          },
        }),
        b("files", {
          name: "Invoice bundle",
          x: 40,
          y: 780,
          w: 280,
          h: 48,
          content: {
            label: "Full pack ZIP — {{invoice_no}}",
            count: 1,
          },
        }),
        b("paragraph", {
          name: "Pack archive note",
          x: 340,
          y: 776,
          w: 320,
          h: 72,
          content: {
            text: "Archived copies remain available for {{terms}}. Request additional customs or origin certificates by quoting the SKU and document name above.",
          },
          style: { fontSize: 10, lineHeight: 1.5, color: "#5c6570" },
        }),
        b("text", {
          name: "Footer",
          x: 40,
          y: 900,
          w: 640,
          h: 20,
          content: { text: "{{bill_company}} · {{invoice_no}} · Page 3 of 3" },
          style: { fontSize: 9, color: "#5c6570", textAlign: "center" },
          pin: { bottom: true, left: true, right: true },
        }),
      ]),
    ],
    {
      outputs: outputsFor("preview", "pdf", "print", "email"),
      primaryDatasetId: primaryId,
      datasets: [
        {
          id: primaryId,
          name: "primary",
          rows: [],
        },
        {
          id: bankId,
          name: "bank",
          keyField: "currency",
          rows: [
            {
              currency: "EUR",
              bank_name: "Northline Systems BV",
              iban: "BE68 1234 5678 9012",
              bic: "GKCCBEBB",
            },
            {
              currency: "USD",
              bank_name: "Northline Systems Inc",
              iban: "US64 SVBK US6S 3300",
              bic: "SVBKUS6S",
            },
          ],
        },
      ],
    },
  );
}

export function advancedInvoice(): Project {
  const lineChildren = [
    b("text", {
      name: "Line desc",
      x: 8,
      y: 6,
      w: 280,
      h: 22,
      content: { text: "{{description}}" },
      style: { fontSize: 12, color: "#1c2430" },
    }),
    b("text", {
      name: "Line qty",
      x: 300,
      y: 6,
      w: 48,
      h: 22,
      content: { text: "{{qty}}" },
      style: { fontSize: 12, textAlign: "right" },
    }),
    b("text", {
      name: "Line amount",
      x: 360,
      y: 6,
      w: 100,
      h: 22,
      content: { text: "{{amount|currency:EUR}}" },
      style: { fontSize: 12, textAlign: "right" },
    }),
  ];
  return shell(
    {
      name: "Advanced invoice (repeat)",
      author: "Northline Billing",
      subject: "Repeater + filters + #if",
      description:
        "JSON line_items repeater; Status condition axis flips overdue / open / paid on the same Page output.",
    },
    [
      page("Invoice", [
        b("shape", {
          name: "Letterhead",
          x: 0,
          y: 0,
          w: 720,
          h: 68,
          content: { shape: "rect", filled: true },
          style: { background: "#f3f7f6" },
          zIndex: 0,
          pin: { top: true, left: true, right: true },
        }),
        b("text", {
          name: "Title",
          x: 40,
          y: 20,
          w: 400,
          h: 32,
          content: { text: "Invoice {{invoice_no}}" },
          style: { fontSize: 22, fontWeight: 700 },
          zIndex: 1,
        }),
        b("text", {
          name: "Banner overdue",
          x: 40,
          y: 88,
          w: 620,
          h: 36,
          content: {
            text: "OVERDUE — amount {{total|currency:EUR}} was due {{due_date|date:short}}. Pay immediately.",
          },
          style: {
            fontSize: 13,
            fontWeight: 700,
            color: "#ffffff",
            background: "#9b2c2c",
            textAlign: "center",
            verticalAlign: "middle",
          },
          condition: "vars.status == 'past_due'",
        }),
        b("text", {
          name: "Banner open",
          x: 40,
          y: 88,
          w: 620,
          h: 36,
          content: {
            text: "Amount due {{total|currency:EUR}} by {{due_date|date:short}}.",
          },
          style: {
            fontSize: 13,
            fontWeight: 600,
            color: "#1c2430",
            background: "#e8f0ee",
            textAlign: "center",
            verticalAlign: "middle",
          },
          condition: "vars.status == 'open'",
        }),
        b("text", {
          name: "Banner paid",
          x: 40,
          y: 88,
          w: 620,
          h: 36,
          content: { text: "PAID — thank you. No further action on {{invoice_no}}." },
          style: {
            fontSize: 13,
            fontWeight: 700,
            color: "#0f6b63",
            background: "#d8efe8",
            textAlign: "center",
            verticalAlign: "middle",
          },
          condition: "vars.status == 'paid'",
        }),
        b("text", {
          name: "Bill to",
          x: 40,
          y: 140,
          w: 300,
          h: 80,
          content: {
            text: "{{bill_name}}\n{{bill_company}}\n{{bill_address}}",
          },
          style: { fontSize: 12, lineHeight: 1.45 },
        }),
        b("text", {
          name: "Dates",
          x: 420,
          y: 140,
          w: 240,
          h: 56,
          content: {
            text: "Issued {{invoice_date|date:short}}\nDue {{due_date|date:short}}",
          },
          style: { fontSize: 11, textAlign: "right", color: "#5c6570" },
        }),
        b("repeat", {
          name: "Line items",
          x: 40,
          y: 248,
          w: 620,
          h: 64,
          content: {
            itemsPath: "line_items",
            itemVar: "item",
            blocks: lineChildren,
          },
        }),
        b("text", {
          name: "Total",
          x: 400,
          y: 520,
          w: 260,
          h: 32,
          content: { text: "Total {{total|currency:EUR}}" },
          style: { fontSize: 14, fontWeight: 700, textAlign: "right" },
        }),
        b("paragraph", {
          name: "Notes open",
          x: 40,
          y: 580,
          w: 620,
          h: 80,
          content: {
            text: "Please remit by {{due_date|date:short}}. Cite {{invoice_no}} on the transfer. Remittance advice is on page two.",
          },
          style: { fontSize: 11, color: "#5c6570", lineHeight: 1.55 },
          condition: "vars.status != 'paid'",
        }),
        b("paragraph", {
          name: "Notes paid",
          x: 40,
          y: 580,
          w: 620,
          h: 80,
          content: {
            text: "This invoice is settled. Keep this page for your records; remittance advice is archived on page two.",
          },
          style: { fontSize: 11, color: "#5c6570", lineHeight: 1.55 },
          condition: "vars.status == 'paid'",
        }),
        b("text", {
          name: "Footer",
          x: 40,
          y: 900,
          w: 640,
          h: 18,
          content: { text: "Invoice {{invoice_no}} · Page 1 of 2" },
          style: { fontSize: 9, color: "#5c6570", textAlign: "center" },
          pin: { bottom: true, left: true, right: true },
        }),
      ]),
      page("Remittance advice", [
        b("shape", {
          name: "Header bar",
          x: 0,
          y: 0,
          w: 720,
          h: 56,
          content: { shape: "rect", filled: true },
          style: { background: "#f3f7f6" },
          zIndex: 0,
          pin: { top: true, left: true, right: true },
        }),
        b("text", {
          name: "Remit heading",
          x: 40,
          y: 16,
          w: 620,
          h: 28,
          content: {
            text: "Remittance advice — {{invoice_no}} · {{env.today|date:short}}",
          },
          style: { fontSize: 18, fontWeight: 700, color: "#1c2430" },
          zIndex: 1,
        }),
        b("text", {
          name: "Remit status",
          x: 40,
          y: 80,
          w: 620,
          h: 28,
          content: {
            text: "{{#if status == 'paid'}}Marked PAID — no action needed{{else}}Please return the slip below with your payment{{/if}}",
          },
          style: { fontSize: 11.5, color: "#5c6570" },
        }),
        b("table", {
          name: "Remit fields",
          x: 40,
          y: 128,
          w: 620,
          h: 130,
          content: {
            rows: 4,
            cols: 2,
            cells: [
              ["Billed to", "{{bill_name}} · {{bill_company}}"],
              ["Address", "{{bill_address}}"],
              ["Issued / due", "{{invoice_date|date:short}} / {{due_date|date:short}}"],
              ["Total due", "{{total|currency:EUR}}"],
            ],
          },
          style: { fontSize: 12 },
        }),
        b("paragraph", {
          name: "Wire lines",
          x: 40,
          y: 280,
          w: 620,
          h: 56,
          content: {
            text: "Payee: Northline Billing · Amount: {{total|currency:EUR}} · Reference: {{invoice_no}}\nIBAN on file with Accounts — cite {{invoice_no}} on the transfer memo.",
          },
          style: { fontSize: 12, lineHeight: 1.55, color: "#1c2430" },
          variants: [
            {
              id: id(),
              output: "email",
              content: {
                text: "Pay online: {{pay_url|default:https://northline.example/pay}} · Reference {{invoice_no}} · {{total|currency:EUR}}",
              },
            },
          ],
        }),
        b("signature", {
          name: "Auth signature",
          x: 40,
          y: 360,
          w: 280,
          h: 120,
          content: {
            mode: "preset",
            src: DEMO_IMG.signature,
            label: "Authorized for Northline",
            caption:
              "{{signer_name|default:Billing Office}}\n{{signer_role|default:Accounts receivable}}",
            signedAt: "{{invoice_date|date:short}}",
            showLine: true,
          },
          style: { fontSize: 11, color: "#5c6570", fontFamily: "ui" },
        }),
        b("signature", {
          name: "Customer ack",
          x: 360,
          y: 360,
          w: 280,
          h: 120,
          content: {
            mode: "open",
            src: "",
            label: "Customer acknowledgment",
            caption: "{{bill_name}}\nSign · Date",
            signedAt: "",
            showLine: true,
          },
          style: { fontSize: 11, color: "#5c6570", fontFamily: "ui" },
        }),
        b("paragraph", {
          name: "Remit note",
          x: 40,
          y: 508,
          w: 620,
          h: 120,
          content: {
            text: "Keep this page for your records. Line items repeat from {{line_items.length}} entries on page one; amounts include applicable VAT where stated.\n\nWire transfers should cite {{invoice_no}} so cash application is automatic.",
          },
          style: { fontSize: 11, lineHeight: 1.55, color: "#5c6570" },
        }),
        b("text", {
          name: "Footer",
          x: 40,
          y: 900,
          w: 640,
          h: 18,
          content: { text: "{{bill_company}} · {{invoice_no}} · Page 2 of 2" },
          style: { fontSize: 9, color: "#5c6570", textAlign: "center" },
          pin: { bottom: true, left: true, right: true },
        }),
      ]),
    ],
    {
      outputs: outputsFor("preview", "pdf", "print"),
    },
  );
}

export function decisionNotice(): Project {
  return shell(
    {
      name: "Decision notice",
      author: "Northline Compliance",
      subject: "Approval / pending / revoked branches",
      description:
        "Declare a decision condition axis; Preview chips flip the same Page output.",
    },
    [
      page("Notice", [
        b("shape", {
          name: "Letterhead",
          x: 0,
          y: 0,
          w: 720,
          h: 56,
          content: { shape: "rect", filled: true },
          style: { background: "#f3f7f6" },
          zIndex: 0,
          pin: { top: true, left: true, right: true },
        }),
        b("text", {
          name: "Title",
          x: 40,
          y: 16,
          w: 640,
          h: 28,
          content: { text: "Decision notice — {{case_id}}" },
          style: { fontSize: 18, fontWeight: 700, color: "#1c2430" },
          zIndex: 1,
        }),
        b("text", {
          name: "Approved banner",
          x: 40,
          y: 80,
          w: 640,
          h: 40,
          content: { text: "APPROVED — proceed with next steps" },
          style: {
            fontSize: 14,
            fontWeight: 700,
            color: "#ffffff",
            background: "#0f6b63",
            textAlign: "center",
            verticalAlign: "middle",
          },
          condition: "vars.decision == 'approved'",
        }),
        b("text", {
          name: "Pending banner",
          x: 40,
          y: 80,
          w: 640,
          h: 40,
          content: { text: "PENDING — under review" },
          style: {
            fontSize: 14,
            fontWeight: 700,
            color: "#1c2430",
            background: "#e8e4dc",
            textAlign: "center",
            verticalAlign: "middle",
          },
          condition: "vars.decision == 'pending'",
        }),
        b("text", {
          name: "Revoked banner",
          x: 40,
          y: 80,
          w: 640,
          h: 40,
          content: { text: "REVOKED — stop work immediately" },
          style: {
            fontSize: 14,
            fontWeight: 700,
            color: "#ffffff",
            background: "#9b2c2c",
            textAlign: "center",
            verticalAlign: "middle",
          },
          condition: "vars.decision == 'revoked'",
        }),
        b("paragraph", {
          name: "Body",
          x: 40,
          y: 140,
          w: 640,
          h: 120,
          content: {
            text: "Dear {{name}},\n\nRegarding case {{case_id}} dated {{decision_date|date:long}}.\n\n{{reason}}",
          },
          style: { fontSize: 13, lineHeight: 1.55, color: "#1c2430" },
        }),
        b("paragraph", {
          name: "Next approved",
          x: 40,
          y: 280,
          w: 640,
          h: 100,
          content: {
            text: "You may continue delivery against the agreed schedule. Countersign the enclosed schedule and return within five business days.",
          },
          style: { fontSize: 12, lineHeight: 1.5, color: "#3d4a5c" },
          condition: "vars.decision == 'approved'",
        }),
        b("paragraph", {
          name: "Next pending",
          x: 40,
          y: 280,
          w: 640,
          h: 100,
          content: {
            text: "No action is required until review completes. We will notify you when a decision is recorded.",
          },
          style: { fontSize: 12, lineHeight: 1.5, color: "#3d4a5c" },
          condition: "vars.decision == 'pending'",
        }),
        b("paragraph", {
          name: "Next revoked",
          x: 40,
          y: 280,
          w: 640,
          h: 100,
          content: {
            text: "Cease all work under this case. Return materials and revoke access tokens within 48 hours. Contact compliance@northline.example with questions.",
          },
          style: { fontSize: 12, lineHeight: 1.5, color: "#3d4a5c" },
          condition: "vars.decision == 'revoked'",
        }),
        b("text", {
          name: "Footer",
          x: 40,
          y: 900,
          w: 640,
          h: 18,
          content: {
            text: "Northline Compliance · {{case_id}} · {{env.today|date:short}}",
          },
          style: { fontSize: 9, color: "#5c6570", textAlign: "center" },
          pin: { bottom: true, left: true, right: true },
        }),
      ]),
    ],
    {
      outputs: outputsFor("preview", "pdf", "print"),
    },
  );
}

export function memo(): Project {
  return shell(
    {
      name: "Internal memo & agenda",
      author: "Northline PMO",
      subject: "Office memo with agenda table",
      description:
        "Corporate memo header plus agenda table bound to an agenda JSON array.",
    },
    [
      page("Memo", [
        b("shape", {
          name: "Letterhead",
          x: 0,
          y: 0,
          w: 720,
          h: 64,
          content: { shape: "rect", filled: true },
          style: { background: "#f3f7f6" },
          zIndex: 0,
          pin: { top: true, left: true, right: true },
        }),
        b("text", {
          name: "MEMO",
          x: 40,
          y: 22,
          w: 200,
          h: 24,
          content: { text: "MEMORANDUM" },
          style: { fontSize: 14, fontWeight: 700, color: "#0f6b63" },
          zIndex: 1,
        }),
        b("date", {
          name: "Memo date",
          x: 480,
          y: 20,
          w: 200,
          h: 24,
          content: { source: "field", path: "date", format: "long" },
          style: {
            fontSize: 11,
            color: "#5c6570",
            textAlign: "right",
            fontFamily: "ui",
          },
          zIndex: 1,
        }),
        b("table", {
          name: "Header fields",
          x: 40,
          y: 84,
          w: 620,
          h: 90,
          content: {
            rows: 3,
            cols: 2,
            cells: [
              ["To", "{{to}}"],
              ["From", "{{from}}"],
              ["Date", "{{date|date:short}}"],
            ],
            borderColor: "#d4d9e0",
          },
          style: { fontSize: 11 },
        }),
        b("text", {
          name: "Subject",
          x: 40,
          y: 188,
          w: 620,
          h: 28,
          content: { text: "Subject: {{subject}}" },
          style: { fontSize: 13, fontWeight: 700, color: "#1c2430" },
          variants: [
            {
              id: id(),
              language: "fr",
              content: { text: "Objet : {{subject_fr}}" },
            },
          ],
        }),
        b("paragraph", {
          name: "Body",
          x: 40,
          y: 232,
          w: 620,
          h: 140,
          content: {
            text: "{{body}}\n\nPlease read the agenda before the call and come ready with capacity numbers from the shared sheet. Risks not listed below should be raised under AOB.",
          },
          style: { fontSize: 12, color: "#1c2430", lineHeight: 1.55 },
        }),
        b("text", {
          name: "Agenda label",
          x: 40,
          y: 392,
          w: 200,
          h: 20,
          content: { text: "Meeting agenda" },
          style: { fontSize: 12, fontWeight: 700, color: "#1c2430" },
        }),
        b("table", {
          name: "Agenda",
          x: 40,
          y: 420,
          w: 620,
          h: 160,
          content: {
            header: true,
            zebra: true,
            sourcePath: "agenda",
            rows: 2,
            cols: 3,
            cells: [
              ["Time", "Topic", "Owner"],
              ["{{time}}", "{{topic}}", "{{owner}}"],
            ],
            headerBackground: "#e8f0ee",
            cellPadding: 8,
          },
          style: { fontSize: 11 },
        }),
        b("list", {
          name: "Actions",
          x: 40,
          y: 612,
          w: 420,
          h: 120,
          content: {
            items: [
              "Action: {{action1}}",
              "Action: {{action2}}",
              "Decision by: {{decision_date|date:short}}",
              "Circulate notes within 24 hours",
            ],
          },
          style: { fontSize: 11, lineHeight: 1.45 },
        }),
        b("files", {
          name: "Attachments",
          x: 480,
          y: 612,
          w: 180,
          h: 48,
          content: { label: "Attachments", count: 2 },
        }),
        b("text", {
          name: "Footer",
          x: 40,
          y: 900,
          w: 640,
          h: 18,
          content: { text: "{{subject}} · {{date|date:short}} · Page 1 of 2" },
          style: { fontSize: 9, color: "#5c6570", textAlign: "center" },
          pin: { bottom: true, left: true, right: true },
        }),
      ]),
      page("Appendix", [
        b("shape", {
          name: "Header bar",
          x: 0,
          y: 0,
          w: 720,
          h: 52,
          content: { shape: "rect", filled: true },
          style: { background: "#f3f7f6" },
          zIndex: 0,
          pin: { top: true, left: true, right: true },
        }),
        b("text", {
          name: "Appendix title",
          x: 40,
          y: 16,
          w: 500,
          h: 26,
          content: { text: "Appendix — {{subject}}" },
          style: { fontSize: 15, fontWeight: 700, color: "#1c2430" },
          zIndex: 1,
        }),
        b("text", {
          name: "Distribution label",
          x: 40,
          y: 76,
          w: 240,
          h: 20,
          content: { text: "Distribution & owners" },
          style: { fontSize: 12, fontWeight: 700, color: "#1c2430" },
        }),
        b("table", {
          name: "Owner matrix",
          x: 40,
          y: 104,
          w: 620,
          h: 160,
          content: {
            header: true,
            zebra: true,
            sourcePath: "agenda",
            rows: 2,
            cols: 3,
            cells: [
              ["Topic", "Owner", "Follow-up"],
              ["{{topic}}", "{{owner}}", "Notes by {{decision_date}}"],
            ],
            headerBackground: "#e8f0ee",
          },
          style: { fontSize: 11 },
        }),
        b("text", {
          name: "Context label",
          x: 40,
          y: 290,
          w: 240,
          h: 20,
          content: { text: "Background" },
          style: { fontSize: 12, fontWeight: 700, color: "#1c2430" },
        }),
        b("paragraph", {
          name: "Context body",
          x: 40,
          y: 318,
          w: 620,
          h: 140,
          content: {
            text: "Owners above expand from the same agenda array as page one. Capacity numbers referenced in the agenda come from the shared sheet; risk entries mirror the register as of {{date|date:short}}.\n\nNothing in this appendix changes the actions on page one — it exists so nobody has to reverse-engineer the meeting.",
          },
          style: { fontSize: 11.5, lineHeight: 1.55, color: "#3d4a5c" },
        }),
        b("text", {
          name: "Pre-read label",
          x: 40,
          y: 480,
          w: 240,
          h: 20,
          content: { text: "Pre-reads" },
          style: { fontSize: 12, fontWeight: 700, color: "#1c2430" },
        }),
        b("files", {
          name: "Pre-read pack",
          x: 40,
          y: 508,
          w: 220,
          h: 48,
          content: { label: "Pre-read pack (PDF)", count: 3 },
        }),
        b("files", {
          name: "Capacity sheet",
          x: 284,
          y: 508,
          w: 220,
          h: 48,
          content: { label: "Capacity sheet", count: 1 },
        }),
        b("list", {
          name: "Decision checklist",
          x: 40,
          y: 580,
          w: 520,
          h: 110,
          content: {
            items: [
              "Confirm owners for topics 1–3",
              "Sign off capacity asks before {{decision_date}}",
              "Book follow-up for unresolved risks",
              "Publish notes to the project channel",
            ],
            markerColor: "#0f6b63",
          },
          style: { fontSize: 11.5, lineHeight: 1.5, color: "#3d4a5c" },
        }),
        b("paragraph", {
          name: "Action recap",
          x: 40,
          y: 720,
          w: 620,
          h: 64,
          content: {
            text: "Recap of page-one actions: {{action1}} · {{action2}}. Decisions close {{decision_date}}.",
          },
          style: { fontSize: 11, lineHeight: 1.5, color: "#5c6570" },
        }),
        b("text", {
          name: "Footer",
          x: 40,
          y: 900,
          w: 640,
          h: 18,
          content: { text: "{{to}} · {{from}} · Page 2 of 2" },
          style: { fontSize: 9, color: "#5c6570", textAlign: "center" },
          pin: { bottom: true, left: true, right: true },
        }),
      ]),
    ],
    { outputs: outputsFor("preview", "pdf", "email") },
  );
}

export function shippingLabel(): Project {
  const outputs = outputsFor("preview", "pdf", "print");
  return shell(
    {
      name: "Shipping label",
      author: "Northline Logistics",
      subject: "203dpi label printer layout",
      description:
        "Compact label for thermal printers: addresses, barcode field, weight table. Print-device conditions.",
    },
    [
      page("Label", [
        b("shape", {
          name: "Header bar",
          x: 0,
          y: 0,
          w: 720,
          h: 72,
          content: { shape: "rect", filled: true },
          style: { background: "#1c2430" },
          zIndex: 0,
          pin: { top: true, left: true, right: true },
        }),
        b("text", {
          name: "Carrier",
          x: 40,
          y: 16,
          w: 320,
          h: 20,
          content: { text: "{{carrier}} · {{service}}" },
          style: { fontSize: 12, fontWeight: 700, color: "#ffffff" },
          zIndex: 1,
        }),
        b("text", {
          name: "Tracking",
          x: 40,
          y: 40,
          w: 400,
          h: 24,
          content: { text: "{{tracking}}" },
          style: { fontSize: 16, fontWeight: 700, color: "#ffffff" },
          zIndex: 1,
        }),
        b("text", {
          name: "Ship date",
          x: 480,
          y: 40,
          w: 200,
          h: 24,
          content: {
            text: "Ship {{ship_date|date:short}}",
          },
          style: { fontSize: 11, color: "#c8c2b8", textAlign: "right" },
          zIndex: 1,
        }),
        b("paragraph", {
          name: "From",
          x: 40,
          y: 100,
          w: 300,
          h: 100,
          content: { text: "FROM\n{{from_name}}\n{{from_address}}" },
          style: { fontSize: 12, color: "#1c2430", lineHeight: 1.45 },
        }),
        b("paragraph", {
          name: "To",
          x: 380,
          y: 100,
          w: 300,
          h: 110,
          content: { text: "TO\n{{to_name}}\n{{to_address}}" },
          style: { fontSize: 13, fontWeight: 600, color: "#1c2430", lineHeight: 1.45 },
        }),
        b("table", {
          name: "Parcel",
          x: 40,
          y: 240,
          w: 640,
          h: 100,
          content: {
            rows: 2,
            cols: 3,
            cells: [
              ["Weight", "Dims", "Zone"],
              ["{{weight}}", "{{dims}}", "{{zone}}"],
            ],
          },
          style: { fontSize: 12 },
        }),
        b("shape", {
          name: "Barcode area",
          x: 40,
          y: 380,
          w: 640,
          h: 100,
          content: { shape: "rect" },
          style: { background: "#1c2430" },
        }),
        b("text", {
          name: "Barcode text",
          x: 56,
          y: 414,
          w: 608,
          h: 32,
          content: { text: "|||| {{tracking}} ||||" },
          style: {
            fontSize: 20,
            fontWeight: 700,
            color: "#ffffff",
            textAlign: "center",
          },
          zIndex: 2,
        }),
        b("paragraph", {
          name: "Handling",
          x: 40,
          y: 520,
          w: 640,
          h: 120,
          content: {
            text: "Handle with care. Keep upright. Do not stack above 25 kg.\n\nIf the package is damaged on arrival, photograph the carton and contact {{carrier}} with tracking {{tracking}} before opening.",
          },
          style: { fontSize: 12, color: "#3d4a5c", lineHeight: 1.55 },
        }),
        b("text", {
          name: "Device note",
          x: 40,
          y: 680,
          w: 500,
          h: 20,
          content: {
            text: "Print · {{device.media}} @ {{device.dpi}}dpi",
          },
          style: { fontSize: 10, color: "#0f6b63" },
          condition: "output.kind == 'print'",
        }),
        b("text", {
          name: "Footer",
          x: 40,
          y: 900,
          w: 640,
          h: 18,
          content: { text: "{{carrier}} · {{tracking}} · Northline Logistics" },
          style: { fontSize: 9, color: "#5c6570", textAlign: "center" },
          pin: { bottom: true, left: true, right: true },
        }),
      ]),
      page("Customs declaration", [
        b("shape", {
          name: "Header bar",
          x: 0,
          y: 0,
          w: 720,
          h: 56,
          content: { shape: "rect", filled: true },
          style: { background: "#1c2430" },
          zIndex: 0,
          pin: { top: true, left: true, right: true },
        }),
        b("text", {
          name: "CN title",
          x: 40,
          y: 18,
          w: 520,
          h: 22,
          content: { text: "CUSTOMS DECLARATION — CN23 (simplified)" },
          style: { fontSize: 13, fontWeight: 700, color: "#ffffff" },
          zIndex: 1,
        }),
        b("table", {
          name: "CN parties",
          x: 40,
          y: 80,
          w: 520,
          h: 140,
          content: {
            rows: 4,
            cols: 2,
            cells: [
              ["Sender", "{{from_name}} — {{from_address}}"],
              ["Addressee", "{{to_name}}"],
              ["Destination", "{{to_address}}"],
              ["Service", "{{carrier}} {{service}}"],
            ],
          },
          style: { fontSize: 11 },
        }),
        b("table", {
          name: "CN parcel",
          x: 40,
          y: 244,
          w: 520,
          h: 100,
          content: {
            rows: 3,
            cols: 2,
            cells: [
              ["Tracking", "{{tracking}}"],
              ["Total weight", "{{weight}}"],
              ["Dimensions", "{{dims}} (zone {{zone}})"],
            ],
          },
          style: { fontSize: 11 },
        }),
        b("text", {
          name: "Contents label",
          x: 40,
          y: 372,
          w: 300,
          h: 18,
          content: { text: "Contents" },
          style: { fontSize: 12, fontWeight: 700, color: "#1c2430" },
        }),
        b("list", {
          name: "Contents list",
          x: 40,
          y: 400,
          w: 520,
          h: 120,
          content: {
            items: [
              "Merchandise samples — no commercial value beyond €20",
              "Documents and onboarding material",
              "Return label enclosed inside pouch",
              "No dangerous goods · no lithium batteries loose",
            ],
            markerColor: "#0f6b63",
          },
          style: { fontSize: 11, lineHeight: 1.45, color: "#3d4a5c" },
        }),
        b("paragraph", {
          name: "CN remarks",
          x: 40,
          y: 544,
          w: 520,
          h: 100,
          content: {
            text: "I certify the particulars are true to the best of my knowledge. Handling notes for {{carrier}}: fragile contents, this side up.\n\nRetain a copy with the commercial invoice for {{to_name}}.",
          },
          style: { fontSize: 11, lineHeight: 1.5, color: "#5c6570" },
        }),
        b("text", {
          name: "CN sign line",
          x: 40,
          y: 680,
          w: 360,
          h: 24,
          content: { text: "{{from_name}} ________  Date ____________" },
          style: { fontSize: 11, color: "#5c6570" },
        }),
        b("shape", {
          name: "CN barcode strip",
          x: 600,
          y: 80,
          w: 48,
          h: 520,
          content: { shape: "rect" },
          style: { background: "#1c2430", borderRadius: 2 },
        }),
        b("text", {
          name: "CN tracking vertical",
          x: 580,
          y: 620,
          w: 88,
          h: 18,
          content: { text: "{{tracking}}" },
          style: {
            fontSize: 8,
            fontWeight: 700,
            color: "#1c2430",
            textAlign: "center",
          },
        }),
        b("text", {
          name: "Footer",
          x: 40,
          y: 900,
          w: 640,
          h: 18,
          content: { text: "CN23 · {{tracking}} · {{carrier}}" },
          style: { fontSize: 9, color: "#5c6570", textAlign: "center" },
          pin: { bottom: true, left: true, right: true },
        }),
      ]),
    ],
    { outputs },
  );
}

