export const NEWSLETTER_PRODUCT_CSV = `[
  {"preheader":"Your workspace launch kit is ready","title":"Launch Atlas with confidence","first_name":"Maya","intro":"Atlas brings approvals, bulk rendering, and delivery tracking into one workspace.","mod1_title":"Approval lanes","mod1_body":"Route every proof to the right owner.","mod2_title":"Delivery tracking","mod2_body":"Follow email and PDF output from one dashboard.","cta_label":"Open the launch guide","cta_url":"https://product.example/atlas/guide","sender_name":"Sam Ortega","sender_role":"Product lead","email":"maya@client.example","unsub_url":"https://product.example/preferences/unsubscribe","web_version_url":"https://product.example/news/atlas-maya","year":2026,"language":"en","segment":"b2b"},
  {"preheader":"Votre kit de lancement est prêt","title":"Lancez Atlas sereinement","first_name":"Camille","intro":"Atlas réunit les validations, le rendu en série et le suivi des envois.","mod1_title":"Circuits de validation","mod1_body":"Chaque épreuve rejoint la bonne personne.","mod2_title":"Suivi des envois","mod2_body":"Suivez les e-mails et PDF depuis un tableau unique.","cta_label":"Ouvrir le guide","cta_url":"https://product.example/fr/atlas/guide","sender_name":"Sam Ortega","sender_role":"Responsable produit","email":"camille@client.example","unsub_url":"https://product.example/fr/preferences/unsubscribe","web_version_url":"https://product.example/fr/news/atlas-camille","year":2026,"language":"fr","segment":"b2b"},
  {"preheader":"A calmer way to publish","title":"Meet Atlas Home","first_name":"Noah","intro":"Create polished invitations, handouts, and letters without rebuilding layouts.","mod1_title":"Ready-made formats","mod1_body":"Start with A4, Letter, or A5.","mod2_title":"Private by design","mod2_body":"Your source rows stay in your workspace.","cta_label":"Try Atlas Home","cta_url":"https://product.example/atlas/home","sender_name":"Ivy Chen","sender_role":"Community","email":"noah@reader.example","unsub_url":"https://product.example/preferences/unsubscribe","web_version_url":"https://product.example/news/atlas-home-noah","year":2026,"language":"en","segment":"consumer"},
  {"preheader":"Une publication plus simple","title":"Découvrez Atlas Maison","first_name":"Léa","intro":"Créez des invitations, prospectus et courriers sans refaire la mise en page.","mod1_title":"Formats prêts","mod1_body":"Commencez en A4, Letter ou A5.","mod2_title":"Confidentiel par défaut","mod2_body":"Vos données restent dans votre espace.","cta_label":"Essayer Atlas Maison","cta_url":"https://product.example/fr/atlas/home","sender_name":"Ivy Chen","sender_role":"Communauté","email":"lea@reader.example","unsub_url":"https://product.example/fr/preferences/unsubscribe","web_version_url":"https://product.example/fr/news/atlas-home-lea","year":2026,"language":"fr","segment":"consumer"},
  {"preheader":"Les exports groupés arrivent","title":"500 dossiers, un seul lancement","first_name":"Omar","intro":"La nouvelle file d'export traite les campagnes volumineuses sans bloquer l'éditeur.","mod1_title":"File prioritaire","mod1_body":"Réservez la capacité pour les échéances critiques.","mod2_title":"Rapports détaillés","mod2_body":"Téléchargez les erreurs ligne par ligne.","cta_label":"Configurer les exports","cta_url":"https://product.example/fr/atlas/batch","sender_name":"Priya Anand","sender_role":"Ingénierie","email":"omar@client.example","unsub_url":"https://product.example/fr/preferences/unsubscribe","web_version_url":"https://product.example/fr/news/batch-omar","year":2026,"language":"fr","segment":"b2b"},
  {"preheader":"Votre collection d'automne","title":"Des documents prêts à partager","first_name":"Sofia","intro":"Choisissez un modèle, ajoutez vos destinataires et exportez votre série.","mod1_title":"Nouveaux modèles","mod1_body":"Menus, cartes et fiches en trois langues.","mod2_title":"Liens partageables","mod2_body":"Envoyez une version web accessible.","cta_label":"Voir la collection","cta_url":"https://product.example/fr/collection/autumn","sender_name":"Dana Willems","sender_role":"Éditorial","email":"sofia@reader.example","unsub_url":"https://product.example/fr/preferences/unsubscribe","web_version_url":"https://product.example/fr/news/autumn-sofia","year":2026,"language":"fr","segment":"consumer"}
]`;

export const NEWSLETTER_DIGEST_CSV = `[
  {"edition":"Canal Review","edition_number":42,"edition_date":"2026-09-01","digest_title":"Northline Monthly","digest_title_fr":"Le Mensuel Northline","headline":"Local teams turn one template into a publishing desk","headline_fr":"Un modèle devient une rédaction complète","body_col1":"City teams now produce notices in hours while retaining human approval at every release gate.","body_col1_fr":"Les équipes municipales produisent désormais leurs avis en quelques heures tout en conservant une validation humaine.","body_col2":"The pilot reduced corrections and gave operators a clear reconciliation report.","body_col2_fr":"Le pilote a réduit les corrections et fourni un rapport de rapprochement clair.","body_col3":"A shared catalog keeps print and email editions aligned.","body_col3_fr":"Un catalogue commun aligne les éditions imprimées et e-mail.","body_col4":"Next month the program expands to permit renewals.","body_col4_fr":"Le mois prochain, le programme couvrira les renouvellements de permis.","story_2_title":"Proofing without bottlenecks","story_2_title_fr":"Valider sans ralentir","story_4_title":"What comes next","story_4_title_fr":"La suite","cta_label":"Read the full edition","cta_url":"https://digest.example/canal/42","unsub_url":"https://digest.example/preferences","web_version_url":"https://digest.example/canal/42/web","segment":"b2b","language":"en","year":2026},
  {"edition":"Revue Meuse","edition_number":18,"edition_date":"2026-09-08","digest_title":"Operations Digest","digest_title_fr":"La Revue des opérations","headline":"Les ateliers partagés accélèrent la publication bilingue","headline_fr":"Les ateliers partagés accélèrent la publication bilingue","body_col1":"Trois communes mutualisent leurs modèles et leurs contrôles avant impression.","body_col1_fr":"Trois communes mutualisent leurs modèles et leurs contrôles avant impression.","body_col2":"Une liste de vérification commune protège les mentions réglementaires.","body_col2_fr":"Une liste de vérification commune protège les mentions réglementaires.","body_col3":"Les lecteurs reçoivent une version adaptée à leur langue.","body_col3_fr":"Les lecteurs reçoivent une version adaptée à leur langue.","body_col4":"Le prochain atelier portera sur l'accessibilité.","body_col4_fr":"Le prochain atelier portera sur l'accessibilité.","story_2_title":"Un contrôle partagé","story_2_title_fr":"Un contrôle partagé","story_4_title":"Rendez-vous en octobre","story_4_title_fr":"Rendez-vous en octobre","cta_label":"Lire le dossier","cta_url":"https://digest.example/fr/meuse/18","unsub_url":"https://digest.example/fr/preferences","web_version_url":"https://digest.example/fr/meuse/18/web","segment":"consumer","language":"fr","year":2026},
  {"edition":"Harbor Brief","edition_number":7,"edition_date":"2026-09-15","digest_title":"The Harbor Brief","digest_title_fr":"La Lettre du port","headline":"Freight documents move from queue to verified output","headline_fr":"Les documents de fret passent de la file au rendu vérifié","body_col1":"Operators connected manifests to labels, customs pages, and customer notices.","body_col1_fr":"Les opérateurs ont relié les manifestes aux étiquettes, pages douanières et avis clients.","body_col2":"Checksums flag incomplete packs before dispatch.","body_col2_fr":"Les sommes de contrôle signalent les dossiers incomplets avant départ.","body_col3":"A print profile preserves thermal-label geometry.","body_col3_fr":"Un profil d'impression préserve la géométrie des étiquettes thermiques.","body_col4":"The team will add carrier-specific rules next.","body_col4_fr":"L'équipe ajoutera ensuite les règles propres aux transporteurs.","story_2_title":"Verify before loading","story_2_title_fr":"Vérifier avant chargement","story_4_title":"Carrier profiles","story_4_title_fr":"Profils transporteurs","cta_label":"Explore the workflow","cta_url":"https://digest.example/harbor/7","unsub_url":"https://digest.example/preferences","web_version_url":"https://digest.example/harbor/7/web","segment":"b2b","language":"en","year":2026},
  {"edition":"Édition Citoyenne","edition_number":11,"edition_date":"2026-09-22","digest_title":"Citizen Notes","digest_title_fr":"Carnet citoyen","headline":"Des avis plus lisibles sur papier et mobile","headline_fr":"Des avis plus lisibles sur papier et mobile","body_col1":"La nouvelle maquette hiérarchise clairement les montants, dates et voies de recours.","body_col1_fr":"La nouvelle maquette hiérarchise clairement les montants, dates et voies de recours.","body_col2":"Chaque lien possède une destination web fictive et vérifiable.","body_col2_fr":"Chaque lien possède une destination web fictive et vérifiable.","body_col3":"Les variantes françaises sont relues avec le même circuit.","body_col3_fr":"Les variantes françaises sont relues avec le même circuit.","body_col4":"Une version à contraste renforcé est en préparation.","body_col4_fr":"Une version à contraste renforcé est en préparation.","story_2_title":"Des liens utiles","story_2_title_fr":"Des liens utiles","story_4_title":"Accessibilité","story_4_title_fr":"Accessibilité","cta_label":"Consulter l'édition","cta_url":"https://digest.example/fr/citizen/11","unsub_url":"https://digest.example/fr/preferences","web_version_url":"https://digest.example/fr/citizen/11/web","segment":"consumer","language":"fr","year":2026}
]`;

export const CONTRACT_LONG_CSV = `[
  {"contract_id":"MSA-2026-41","start_date":"2026-09-01","provider":"Northline Systems BV","client":"Acme Retail NV","provider_address":"14 Harbor Lane, Antwerp","client_address":"12 Quay Street, Rotterdam","net_days":30,"term_months":24,"jurisdiction":"Brussels","notice_days":30,"status":"executed","approved":"yes","language":"en","portal_url":"https://contracts.example/msa-2026-41","provider_signer":"Jordan Hale","provider_signer_title":"Managing Director","client_signer":"Marcus Chen","client_signer_title":"Procurement Director","signed_at":"2026-08-25","service":"Platform licence","quantity":1,"rate":24000,"line_total":24000,"service_rate":150,"overtime_total":2250,"subtotal":30000,"vat_rate":"21%","tax_rate":"21%","grand_total":36300,"services":[{"service":"Platform licence","quantity":1,"rate":24000,"tax_rate":"21%","line_total":24000},{"service":"Implementation","quantity":20,"rate":300,"tax_rate":"21%","line_total":6000}]},
  {"contract_id":"MSA-2026-42","start_date":"2026-09-15","provider":"Northline Systems BV","client":"Banque du Canal SA","provider_address":"14 Harbor Lane, Antwerp","client_address":"8 Quai Central, Brussels","net_days":30,"term_months":36,"jurisdiction":"Bruxelles","notice_days":60,"status":"executed","approved":"yes","language":"fr","portal_url":"https://contracts.example/fr/msa-2026-42","provider_signer":"Petra Vos","provider_signer_title":"Directrice partenariats","client_signer":"Camille Moreau","client_signer_title":"Directrice des achats","signed_at":"2026-08-28","service":"Abonnement conformité","quantity":12,"rate":1800,"line_total":21600,"service_rate":180,"overtime_total":2700,"subtotal":27600,"vat_rate":"21%","tax_rate":"21%","grand_total":33396,"services":[{"service":"Abonnement conformité","quantity":12,"rate":1800,"tax_rate":"21%","line_total":21600},{"service":"Audit initial","quantity":1,"rate":6000,"tax_rate":"21%","line_total":6000}]},
  {"contract_id":"MSA-2026-43","start_date":"2026-10-01","provider":"Northline Systems BV","client":"Orbit Labs SARL","provider_address":"14 Harbor Lane, Antwerp","client_address":"4 Rue des Étoiles, Liège","net_days":45,"term_months":12,"jurisdiction":"Liège","notice_days":30,"status":"draft","approved":"no","language":"fr","portal_url":"https://contracts.example/fr/msa-2026-43","provider_signer":"Rowan Ellis","provider_signer_title":"Conseil juridique","client_signer":"Léa Martin","client_signer_title":"Directrice générale","signed_at":"2026-09-10","service":"Migration documentaire","quantity":1,"rate":14500,"line_total":14500,"service_rate":165,"overtime_total":0,"subtotal":14500,"vat_rate":"21%","tax_rate":"21%","grand_total":17545,"services":[{"service":"Migration documentaire","quantity":1,"rate":12000,"tax_rate":"21%","line_total":12000},{"service":"Formation","quantity":5,"rate":500,"tax_rate":"21%","line_total":2500}]},
  {"contract_id":"MSA-2026-44","start_date":"2026-10-15","provider":"Northline Systems BV","client":"Clara Health Ltd","provider_address":"14 Harbor Lane, Antwerp","client_address":"40 Meadow Road, Ghent","net_days":60,"term_months":18,"jurisdiction":"Ghent","notice_days":45,"status":"draft","approved":"no","language":"en","portal_url":"https://contracts.example/msa-2026-44","provider_signer":"Jordan Hale","provider_signer_title":"Managing Director","client_signer":"Aiko Tanaka","client_signer_title":"Chief Operating Officer","signed_at":"2026-09-18","service":"Patient communications","quantity":6,"rate":3200,"line_total":19200,"service_rate":175,"overtime_total":1312.5,"subtotal":23200,"vat_rate":"21%","tax_rate":"21%","grand_total":28072,"services":[{"service":"Patient communications","quantity":6,"rate":3200,"tax_rate":"21%","line_total":19200},{"service":"Security review","quantity":1,"rate":4000,"tax_rate":"21%","line_total":4000}]}
]`;

export const CONTRACT_EMPLOYEES_JSON = `[
  {"employee_name":"Maya Chen","employer_signer":"Elise Laurent","employer_title":"People Director","job_title":"Staff Engineer","employment_start":"2026-10-01","employment_type":"Permanent","work_location":"Antwerp hybrid","weekly_hours":38,"annual_salary":92000,"probation_months":3,"notice_days":30,"manager_name":"Priya Anand","language":"en","portal_url":"https://people.example/packs/maya","employees":[{"name":"Maya Chen","role":"Staff Engineer","salary":92000,"start_date":"2026-10-01","language":"en"},{"name":"Noah Berg","role":"Platform Engineer","salary":74000,"start_date":"2026-10-15","language":"en"},{"name":"Sofia Reyes","role":"Product Designer","salary":70000,"start_date":"2026-11-01","language":"en"}]},
  {"employee_name":"Camille Moreau","employer_signer":"Élise Laurent","employer_title":"Directrice des ressources humaines","job_title":"Responsable opérations","employment_start":"2026-10-05","employment_type":"Contrat à durée indéterminée","work_location":"Bruxelles hybride","weekly_hours":38,"annual_salary":78000,"probation_months":3,"notice_days":30,"manager_name":"Omar Haddad","language":"fr","portal_url":"https://people.example/fr/packs/camille","employees":[{"name":"Camille Moreau","role":"Responsable opérations","salary":78000,"start_date":"2026-10-05","language":"fr"},{"name":"Léa Martin","role":"Analyste qualité","salary":56000,"start_date":"2026-10-12","language":"fr"},{"name":"Amélie Dupont","role":"Coordinatrice","salary":52000,"start_date":"2026-10-19","language":"fr"}]},
  {"employee_name":"Omar Haddad","employer_signer":"Élise Laurent","employer_title":"Directrice des ressources humaines","job_title":"Architecte solutions","employment_start":"2026-11-02","employment_type":"Contrat à durée indéterminée","work_location":"Liège","weekly_hours":40,"annual_salary":88000,"probation_months":6,"notice_days":45,"manager_name":"Jordan Hale","language":"fr","portal_url":"https://people.example/fr/packs/omar","employees":[{"name":"Omar Haddad","role":"Architecte solutions","salary":88000,"start_date":"2026-11-02","language":"fr"},{"name":"Nora Petit","role":"Consultante","salary":65000,"start_date":"2026-11-09","language":"fr"},{"name":"Hugo Lambert","role":"Ingénieur support","salary":58000,"start_date":"2026-11-16","language":"fr"}]}
]`;

export const AFFIDAVIT_CSV = `[
  {"deponent_name":"Marcus Chen","deponent_address":"12 Quay Street, Rotterdam","deponent_role":"Records custodian","matter_title":"Harbor access review","purpose":"the applicant's access petition","fact_one":"I exported the access ledger from the ordinary records system.","fact_two":"I verified each entry against the signed visitor register.","event_date":"2026-08-12","authority":"Administrative Court of Example","docket_no":"AFF-2026-81","docket_url":"https://dockets.example/aff-2026-81","sworn":"yes","sworn_date":"2026-08-20","sworn_place":"Rotterdam","identity_method":"passport","witness_name":"Iris van Dijk","witness_capacity":"Civil-law notary","witness_registration":"NL-EX-1042","language":"en"},
  {"deponent_name":"Camille Moreau","deponent_address":"8 Quai Central, Bruxelles","deponent_role":"responsable des archives","matter_title":"Contrôle des autorisations","purpose":"la demande de réexamen","fact_one":"j'ai extrait le registre depuis le système d'archives courant.","fact_two":"j'ai comparé chaque entrée avec les validations signées.","event_date":"2026-08-14","authority":"Tribunal administratif Exemple","docket_no":"AFF-2026-82","docket_url":"https://dockets.example/fr/aff-2026-82","sworn":"yes","sworn_date":"2026-08-22","sworn_place":"Bruxelles","identity_method":"carte d'identité","witness_name":"Nora Petit","witness_capacity":"Notaire","witness_registration":"BE-EX-2041","language":"fr"},
  {"deponent_name":"Léa Martin","deponent_address":"4 Rue des Étoiles, Liège","deponent_role":"directrice de programme","matter_title":"Dossier de subvention","purpose":"la confirmation des dépenses admissibles","fact_one":"j'ai reçu les factures originales des fournisseurs.","fact_two":"les montants ont été rapprochés du grand livre du projet.","event_date":"2026-08-18","authority":"Commission régionale Exemple","docket_no":"AFF-2026-83","docket_url":"https://dockets.example/fr/aff-2026-83","sworn":"no","sworn_date":"2026-08-25","sworn_place":"Liège","identity_method":"passeport","witness_name":"Hugo Lambert","witness_capacity":"Greffier habilité","witness_registration":"BE-EX-2077","language":"fr"},
  {"deponent_name":"Aiko Tanaka","deponent_address":"40 Meadow Road, Ghent","deponent_role":"Clinical systems director","matter_title":"Patient notice audit","purpose":"the compliance investigation","fact_one":"I supervised the notice export and retained its checksum.","fact_two":"the delivery report was sealed before review.","event_date":"2026-08-21","authority":"Health Review Board Example","docket_no":"AFF-2026-84","docket_url":"https://dockets.example/aff-2026-84","sworn":"no","sworn_date":"2026-08-28","sworn_place":"Ghent","identity_method":"national identity card","witness_name":"Rowan Ellis","witness_capacity":"Commissioner for oaths","witness_registration":"BE-EX-2110","language":"en"}
]`;

export const RENTAL_HOUSE_JSON = `[
  {"landlord_name":"Harbor Homes BV","landlord_address":"14 Harbor Lane, Antwerp","tenant_name":"Maya Chen","tenant_address":"12 Linden Street, Antwerp","property_address":"8 Canal View, Antwerp","lease_id":"LEASE-2601","lease_start":"2026-10-01","lease_end":"2027-09-30","monthly_rent":1450,"deposit":2900,"payment_day":1,"days_late":3,"utilities_terms":"Tenant pays metered energy; landlord pays building charges.","inventory_ref":"INV-LEASE-2601","furnished":"yes","language":"en","portal_url":"https://rentals.example/lease-2601","agent_name":"Elise Laurent","inventory":[{"item":"Living room sofa","condition":"Good","quantity":1,"notes":"Minor wear on left arm"},{"item":"Dining chairs","condition":"Excellent","quantity":4,"notes":"No visible damage"},{"item":"Bedroom wardrobe","condition":"Good","quantity":1,"notes":"Two keys supplied"}]},
  {"landlord_name":"Maisons du Canal SA","landlord_address":"8 Quai Central, Bruxelles","tenant_name":"Camille Moreau","tenant_address":"22 Rue Haute, Bruxelles","property_address":"31 Avenue Exemple, Bruxelles","lease_id":"LEASE-2602","lease_start":"2026-10-15","lease_end":"2027-10-14","monthly_rent":1320,"deposit":2640,"payment_day":5,"days_late":0,"utilities_terms":"Le locataire paie les consommations individuelles; le bailleur paie les charges structurelles.","inventory_ref":"INV-LEASE-2602","furnished":"no","language":"fr","portal_url":"https://rentals.example/fr/lease-2602","agent_name":"Nora Petit","inventory":[{"item":"Séjour","condition":"Bon","quantity":1,"notes":"Parquet récemment vitrifié"},{"item":"Cuisine","condition":"Très bon","quantity":1,"notes":"Électroménager non inclus"},{"item":"Chambre","condition":"Bon","quantity":2,"notes":"Murs blancs"}]},
  {"landlord_name":"Résidences Meuse SRL","landlord_address":"4 Rue des Étoiles, Liège","tenant_name":"Léa Martin","tenant_address":"9 Rue du Parc, Liège","property_address":"16 Place Exemple, Liège","lease_id":"LEASE-2603","lease_start":"2026-11-01","lease_end":"2027-10-31","monthly_rent":980,"deposit":1960,"payment_day":3,"days_late":7,"utilities_terms":"Provision mensuelle de 120 EUR avec régularisation annuelle.","inventory_ref":"INV-LEASE-2603","furnished":"yes","language":"fr","portal_url":"https://rentals.example/fr/lease-2603","inventory":[{"item":"Canapé-lit","condition":"Bon","quantity":1,"notes":"Housse neuve"},{"item":"Table","condition":"Usage normal","quantity":1,"notes":"Petite marque au plateau"},{"item":"Lampes","condition":"Excellent","quantity":3,"notes":"Ampoules incluses"}]}
]`;

export const RENTAL_CAR_JSON = `[
  {"rental_id":"CAR-2601","renter_name":"Marcus Chen","licence_no":"EX-113804","vehicle_make":"Volta","vehicle_model":"City E","registration":"EX-2601","pickup_location":"Antwerp Central","return_location":"Antwerp Central","pickup_at":"2026-09-04","return_at":"2026-09-08","rental_days":4,"daily_rate":65,"rental_total":310,"vehicle_deposit":500,"included_km":600,"excess_km_rate":0.35,"excess_total":0,"odometer_out":18420,"energy_out":"92% charge","existing_damage":"Small scratch on rear bumper","insurance":"included","language":"en","portal_url":"https://mobility.example/rentals/car-2601","accessories":"Charging cable; warning triangle","agent_name":"Sofia Reyes","extras":[{"item":"child-seat","quantity":1,"rate":12.5,"amount":50,"label":"Child seat"}]},
  {"rental_id":"CAR-2602","renter_name":"Camille Moreau","licence_no":"EX-220941","vehicle_make":"Arden","vehicle_model":"Tourer","registration":"EX-2602","pickup_location":"Bruxelles Midi","return_location":"Liège Centre","pickup_at":"2026-09-10","return_at":"2026-09-13","rental_days":3,"daily_rate":65,"rental_total":240,"vehicle_deposit":650,"included_km":450,"excess_km_rate":0.4,"excess_total":15,"odometer_out":22108,"energy_out":"Plein","existing_damage":"Aucun dommage déclaré","insurance":"included","language":"fr","portal_url":"https://mobility.example/fr/rentals/car-2602","accessories":"Gilet; triangle; câble USB","agent_name":"Nora Petit","extras":[{"item":"gps","quantity":1,"rate":10,"amount":30,"label":"Navigation GPS"}]},
  {"rental_id":"CAR-2603","renter_name":"Léa Martin","licence_no":"EX-331572","vehicle_make":"Fjord","vehicle_model":"Compact","registration":"EX-2603","pickup_location":"Liège Airport","return_location":"Liège Airport","pickup_at":"2026-09-18","return_at":"2026-09-23","rental_days":5,"daily_rate":65,"rental_total":365,"vehicle_deposit":700,"included_km":750,"excess_km_rate":0.45,"excess_total":0,"odometer_out":9034,"energy_out":"88% charge","existing_damage":"Éclat mineur sur le capot","insurance":"declined","language":"fr","portal_url":"https://mobility.example/fr/rentals/car-2603","accessories":"Câble de recharge; kit sécurité","agent_name":"Hugo Lambert","extras":[{"item":"additional-driver","quantity":1,"rate":8,"amount":40,"label":"Conducteur additionnel"}]}
]`;

export const LEGAL_DECISION_CSV = `[
  {"case_id":"DEC-2601","decision":"approved","matter_title":"Operating permit renewal","applicant_name":"Harbor Workshop BV","application_date":"2026-07-01","authority_name":"Example Licensing Authority","authority_signer":"Rowan Ellis","authority_signer_title":"Presiding officer","decision_date":"2026-08-24","effective_date":"2026-09-01","due_date":"2026-09-30","docket_no":"DKT-2601","docket_url":"https://dockets.example/dec-2601","appeal_url":"https://appeals.example/dec-2601","appeal_body":"Example Administrative Appeals Board","appeal_days":30,"legal_basis":"Article 18 of the Example Licensing Code","finding_one":"the application is complete and timely","finding_one_fr":"la demande est complète et présentée dans les délais","finding_two":"the proposed safeguards satisfy the statutory test","finding_two_fr":"les garanties proposées satisfont au critère légal","evidence":"Upload completion certificate","operative_text":"The operating permit is renewed for twenty-four months.","operative_text_fr":"Le permis d'exploitation est renouvelé pour vingt-quatre mois.","order":"File the completion certificate","responsible":"Harbor Workshop BV","service_date":"2026-08-25","service_method":"registered email","service_officer":"Iris van Dijk","base_fine":0,"has_fine":"no","language":"en","orders":[{"order":"File the completion certificate","responsible":"Harbor Workshop BV","due_date":"2026-09-30","evidence":"Signed certificate"}]},
  {"case_id":"DEC-2602","decision":"pending","matter_title":"Demande d'autorisation temporaire","applicant_name":"Atelier du Canal SA","application_date":"2026-07-12","authority_name":"Autorité administrative Exemple","authority_signer":"Nora Petit","authority_signer_title":"Présidente de section","decision_date":"2026-08-26","effective_date":"2026-09-10","due_date":"2026-09-20","docket_no":"DKT-2602","docket_url":"https://dockets.example/fr/dec-2602","appeal_url":"https://appeals.example/fr/dec-2602","appeal_body":"Commission de recours Exemple","appeal_days":30,"legal_basis":"article 12 du Code Exemple","finding_one":"additional evidence remains outstanding","finding_one_fr":"des pièces complémentaires restent attendues","finding_two":"a final decision requires the acoustic report","finding_two_fr":"une décision définitive exige le rapport acoustique","evidence":"Rapport acoustique signé","operative_text":"The application remains pending until the requested report is filed.","operative_text_fr":"La demande reste en instance jusqu'au dépôt du rapport demandé.","order":"Déposer le rapport acoustique","responsible":"Atelier du Canal SA","service_date":"2026-08-27","service_method":"courrier recommandé","service_officer":"Hugo Lambert","base_fine":0,"has_fine":"no","language":"fr","orders":[{"order":"Déposer le rapport acoustique","responsible":"Atelier du Canal SA","due_date":"2026-09-20","evidence":"Rapport signé"}]},
  {"case_id":"DEC-2603","decision":"revoked","matter_title":"Retrait d'un accès réglementé","applicant_name":"Services Meuse SRL","application_date":"2026-06-18","authority_name":"Autorité administrative Exemple","authority_signer":"Élise Laurent","authority_signer_title":"Directrice","decision_date":"2026-08-28","effective_date":"2026-08-29","due_date":"2026-09-05","docket_no":"DKT-2603","docket_url":"https://dockets.example/fr/dec-2603","appeal_url":"https://appeals.example/fr/dec-2603","appeal_body":"Commission de recours Exemple","appeal_days":15,"legal_basis":"article 31 du Code Exemple","finding_one":"the access conditions were materially breached","finding_one_fr":"les conditions d'accès ont été gravement méconnues","finding_two":"immediate revocation is proportionate","finding_two_fr":"le retrait immédiat est proportionné","evidence":"Preuve de restitution des badges","operative_text":"All regulated access rights are revoked immediately.","operative_text_fr":"Tous les droits d'accès réglementé sont retirés immédiatement.","order":"Restituer les badges","responsible":"Services Meuse SRL","service_date":"2026-08-29","service_method":"remise en main propre","service_officer":"Camille Moreau","base_fine":1200,"has_fine":"yes","language":"fr","orders":[{"order":"Restituer les badges","responsible":"Services Meuse SRL","due_date":"2026-09-05","evidence":"Reçu de restitution"}]},
  {"case_id":"DEC-2604","decision":"rejected","matter_title":"Late market permit request","applicant_name":"Orbit Market Ltd","application_date":"2026-08-20","authority_name":"Example Licensing Authority","authority_signer":"Rowan Ellis","authority_signer_title":"Presiding officer","decision_date":"2026-08-30","effective_date":"2026-08-30","due_date":"2026-09-15","docket_no":"DKT-2604","docket_url":"https://dockets.example/dec-2604","appeal_url":"https://appeals.example/dec-2604","appeal_body":"Example Administrative Appeals Board","appeal_days":20,"legal_basis":"Article 9 of the Example Market Code","finding_one":"the statutory filing deadline expired","finding_one_fr":"le délai légal de dépôt est expiré","finding_two":"no exceptional ground justifies an extension","finding_two_fr":"aucun motif exceptionnel ne justifie une prolongation","evidence":"Acknowledgment of site closure","operative_text":"The permit request is rejected as out of time.","operative_text_fr":"La demande de permis est rejetée comme tardive.","order":"Cease market setup","responsible":"Orbit Market Ltd","service_date":"2026-08-31","service_method":"secure portal","service_officer":"Iris van Dijk","base_fine":450,"has_fine":"yes","language":"en","orders":[{"order":"Cease market setup","responsible":"Orbit Market Ltd","due_date":"2026-09-15","evidence":"Site photographs"}]}
]`;

export const HOSPITAL_BILL_JSON = `[
  {"bill_no":"HOS-2601","patient_name":"Maya Chen","patient_address":"12 Linden Street, Antwerp","patient_id":"PT-10421","visit_date":"2026-08-02","issue_date":"2026-08-18","due_date":"2026-09-17","insurer":"Example Mutual","claim_no":"CL-88201","coverage":"partial","language":"en","line1_qty":2,"line1_rate":80,"subtotal":310,"vat_total":0,"total":310,"patient_due":46.5,"insurance_total":263.5,"invoice_checksum_total":310,"line_checksum_total":310,"copay_rate_text":"15% co-pay","vat_rate_text":"0% medical exemption","pay_url":"https://payments.example/hospital/hos-2601","portal_url":"https://patients.example/bills/hos-2601","line_items":[{"code":"CONS-01","label":"Specialist consultation","qty":1,"unit_rate":150,"amount":150},{"code":"LAB-08","label":"Diagnostic panel","qty":2,"unit_rate":80,"amount":160}]},
  {"bill_no":"HOS-2602","patient_name":"Camille Moreau","patient_address":"22 Rue Haute, Bruxelles","patient_id":"PT-10422","visit_date":"2026-08-05","issue_date":"2026-08-20","due_date":"2026-09-19","insurer":"Mutuelle Exemple","claim_no":"CL-88202","coverage":"full","language":"fr","line1_qty":1,"line1_rate":95,"subtotal":245,"vat_total":0,"total":245,"patient_due":0,"insurance_total":245,"invoice_checksum_total":245,"line_checksum_total":245,"copay_rate_text":"Prise en charge intégrale","vat_rate_text":"0 % exonération médicale","pay_url":"https://payments.example/fr/hospital/hos-2602","portal_url":"https://patients.example/fr/bills/hos-2602","line_items":[{"code":"CONS-02","label":"Consultation","qty":1,"unit_rate":150,"amount":150},{"code":"IMG-04","label":"Imagerie","qty":1,"unit_rate":95,"amount":95}]},
  {"bill_no":"HOS-2603","patient_name":"Léa Martin","patient_address":"9 Rue du Parc, Liège","patient_id":"PT-10423","visit_date":"2026-08-09","issue_date":"2026-08-22","due_date":"2026-09-21","insurer":"Aucune","claim_no":"SANS-CLAIM","coverage":"none","language":"fr","line1_qty":3,"line1_rate":80,"subtotal":390,"vat_total":0,"total":390,"patient_due":390,"insurance_total":0,"invoice_checksum_total":390,"line_checksum_total":390,"copay_rate_text":"100 % patient","vat_rate_text":"0 % exonération médicale","pay_url":"https://payments.example/fr/hospital/hos-2603","portal_url":"https://patients.example/fr/bills/hos-2603","line_items":[{"code":"URG-01","label":"Accueil ambulatoire","qty":1,"unit_rate":150,"amount":150},{"code":"LAB-08","label":"Analyses","qty":3,"unit_rate":80,"amount":240}]}
]`;

export const RATES_FINES_JSON = `[
  {"rate_card_no":"RATE-2601","notice_no":"FINE-2601","recipient_name":"Marcus Chen","fine_type":"parking","language":"en","hours":4,"overtime_rate":75,"quote_total":300,"quote_checksum_total":300,"days_overdue":2,"daily_rate_text":"EUR 12 per day","fine_total":84,"fine_cap":150,"fine_checksum_total":84,"late_penalty_total":24,"base_fine":60,"pay_url":"https://payments.example/fines/2601","contest_url":"https://appeals.example/fines/2601","officer_name":"Iris van Dijk","officer_title":"Enforcement officer","issue_date":"2026-08-20","due_date":"2026-09-20","effective_date":"2026-09-01","incident_date":"2026-08-12","location":"Example Square, Antwerp","case_ref":"CASE-F-2601","cancel_hours":24,"minimum_hours":2,"rates":[{"code":"OPS-01","label":"Site inspection","rate":95,"unit":"hour"},{"code":"OPS-02","label":"Permit review","rate":120,"unit":"file"}]},
  {"rate_card_no":"RATE-2602","notice_no":"FINE-2602","recipient_name":"Camille Moreau","fine_type":"admin","language":"fr","hours":6,"overtime_rate":75,"quote_total":450,"quote_checksum_total":450,"days_overdue":5,"daily_rate_text":"12 EUR par jour","fine_total":560,"fine_cap":750,"fine_checksum_total":560,"late_penalty_total":60,"base_fine":500,"pay_url":"https://payments.example/fr/fines/2602","contest_url":"https://appeals.example/fr/fines/2602","officer_name":"Nora Petit","officer_title":"Agente de contrôle","issue_date":"2026-08-22","due_date":"2026-09-22","effective_date":"2026-09-01","incident_date":"2026-08-15","location":"Quai Exemple, Bruxelles","case_ref":"CASE-F-2602","cancel_hours":48,"minimum_hours":3,"rates":[{"code":"ADM-01","label":"Contrôle de dossier","rate":110,"unit":"heure"},{"code":"ADM-02","label":"Certificat","rate":85,"unit":"dossier"}]},
  {"rate_card_no":"RATE-2603","notice_no":"FINE-2603","recipient_name":"Léa Martin","fine_type":"late_fee","language":"fr","hours":3,"overtime_rate":75,"quote_total":225,"quote_checksum_total":225,"days_overdue":8,"daily_rate_text":"12 EUR par jour","fine_total":216,"fine_cap":300,"fine_checksum_total":216,"late_penalty_total":96,"base_fine":120,"pay_url":"https://payments.example/fr/fines/2603","contest_url":"https://appeals.example/fr/fines/2603","officer_name":"Hugo Lambert","officer_title":"Agent administratif","issue_date":"2026-08-25","due_date":"2026-09-25","effective_date":"2026-09-01","incident_date":"2026-08-18","location":"Place Exemple, Liège","case_ref":"CASE-F-2603","cancel_hours":24,"minimum_hours":2,"rates":[{"code":"LATE-01","label":"Traitement tardif","rate":75,"unit":"heure"},{"code":"LATE-02","label":"Notification","rate":35,"unit":"avis"}]}
]`;

export const COMPANY_CHART_CSV = `[
  {"language":"en","view":"leadership","ceo_name":"Jordan Hale","ops_lead":"Omar Haddad","product_lead":"Sam Ortega","engineering_lead":"Priya Anand","revenue_lead":"Petra Vos","engineering_ic_1":"Maya Chen","engineering_ic_2":"Noah Berg","engineering_ic_3":"Ivy Chen","ops_ic_1":"Sofia Reyes","ops_ic_2":"Marcus Chen","ops_ic_3":"Elif Kaya","product_ic_1":"Aiko Tanaka","product_ic_2":"Tom Ikeda","product_ic_3":"Dana Willems","revenue_ic_1":"Camille Moreau","revenue_ic_2":"Léa Martin","revenue_ic_3":"Amir Said","company_url":"https://company.example/about","careers_url":"https://company.example/careers"},
  {"language":"fr","view":"full","ceo_name":"Jordan Hale","ops_lead":"Omar Haddad","product_lead":"Sam Ortega","engineering_lead":"Priya Anand","revenue_lead":"Petra Vos","engineering_ic_1":"Maya Chen","engineering_ic_2":"Noah Berg","engineering_ic_3":"Ivy Chen","ops_ic_1":"Sofia Reyes","ops_ic_2":"Marcus Chen","ops_ic_3":"Elif Kaya","product_ic_1":"Aiko Tanaka","product_ic_2":"Tom Ikeda","product_ic_3":"Dana Willems","revenue_ic_1":"Camille Moreau","revenue_ic_2":"Léa Martin","revenue_ic_3":"Amir Said","company_url":"https://company.example/fr/a-propos","careers_url":"https://company.example/fr/carrieres"}
]`;

export const A5_HANDOUT_CSV = `[
  {"date":"2026-09-12","title":"Open studio","title_fr":"Atelier ouvert","title_nl":"Open atelier","body":"Meet the team and build a multilingual handout from your own data.","body_fr":"Rencontrez l'équipe et créez un prospectus multilingue avec vos données.","body_nl":"Ontmoet het team en maak een meertalige flyer met je eigen gegevens.","company":"Northline Learning","contact":"events@northline.example","highlight_1":"Live merge demo","highlight_2":"Print-safe A5","highlight_3":"Accessible web edition","agenda_1":"09:30 Welcome","agenda_2":"10:00 Build","agenda_3":"11:30 Review","info_url":"https://events.example/open-studio","rsvp_url":"https://events.example/open-studio/rsvp","language":"en"},
  {"date":"2026-09-19","title":"Community print lab","title_fr":"Laboratoire d'impression","title_nl":"Gemeenschappelijk printlab","body":"A practical session for reliable event materials.","body_fr":"Une session pratique pour des supports événementiels fiables.","body_nl":"Een praktische sessie voor betrouwbaar evenementmateriaal.","company":"Northline Learning","contact":"atelier@northline.example","highlight_1":"Modèles réutilisables","highlight_2":"Contrôle des données","highlight_3":"QR vers l'inscription","agenda_1":"Accueil","agenda_2":"Atelier guidé","agenda_3":"Questions","info_url":"https://events.example/fr/print-lab","rsvp_url":"https://events.example/fr/print-lab/rsvp","language":"fr"},
  {"date":"2026-09-26","title":"Publishing clinic","title_fr":"Clinique de publication","title_nl":"Publicatiekliniek","body":"Bring one difficult document and leave with a maintainable template.","body_fr":"Apportez un document difficile et repartez avec un modèle maintenable.","body_nl":"Breng een moeilijk document mee en vertrek met een onderhoudbaar sjabloon.","company":"Northline Learning","contact":"clinic@northline.example","highlight_1":"Voorbeelden beoordelen","highlight_2":"Varianten bouwen","highlight_3":"Uitvoer testen","agenda_1":"Intake","agenda_2":"Bouwen","agenda_3":"Testen","info_url":"https://events.example/nl/clinic","rsvp_url":"https://events.example/nl/clinic/rsvp","language":"nl"}
]`;

export const HANDOUT_WORKSHOP_CSV = `[
  {"title":"Reliable document pipelines","title_fr":"Chaînes documentaires fiables","body":"Design a workflow that validates source data before rendering and delivery.","body_fr":"Concevez un flux qui valide les données avant le rendu et l'envoi.","venue":"Harbor Studio","date":"2026-10-03","segment":"in-person","platform":"Example Meet","language":"en","rsvp_url":"https://workshops.example/pipelines/rsvp","agenda_1":"Map the workflow","agenda_2":"Define checks","agenda_3":"Build outputs","agenda_4":"Review failures","outcome_1":"Spot unsafe assumptions","outcome_2":"Design validation gates","outcome_3":"Separate channels","outcome_4":"Plan recovery","session_1":"Workflow map","session_2":"Data contracts","session_3":"Output lab","session_4":"Failure review","session_1_fr":"Cartographie","session_2_fr":"Contrats de données","session_3_fr":"Atelier sorties","session_4_fr":"Revue des échecs","time_1":"09:00","time_2":"10:00","time_3":"11:15","time_4":"13:30","lead_1":"Priya Anand","lead_2":"Maya Chen","lead_3":"Noah Berg","lead_4":"Omar Haddad","company":"Northline Learning","contact":"learning@northline.example"},
  {"title":"Atelier de publication bilingue","title_fr":"Atelier de publication bilingue","body":"Build one layout that serves French and English readers.","body_fr":"Créez une mise en page unique pour les lecteurs francophones et anglophones.","venue":"Maison du Canal","date":"2026-10-10","segment":"in-person","platform":"Example Meet","language":"fr","rsvp_url":"https://workshops.example/fr/bilingual/rsvp","agenda_1":"Inventaire des contenus","agenda_2":"Axes de langue","agenda_3":"Épreuves","agenda_4":"Validation","outcome_1":"Structurer les variantes","outcome_2":"Réduire les duplications","outcome_3":"Tester les longueurs","outcome_4":"Valider l'accessibilité","session_1":"Content inventory","session_2":"Language axes","session_3":"Proofing","session_4":"Approval","session_1_fr":"Inventaire","session_2_fr":"Axes de langue","session_3_fr":"Épreuves","session_4_fr":"Validation","time_1":"09:30","time_2":"10:30","time_3":"11:30","time_4":"14:00","lead_1":"Camille Moreau","lead_2":"Léa Martin","lead_3":"Nora Petit","lead_4":"Hugo Lambert","company":"Northline Learning","contact":"atelier@northline.example"},
  {"title":"Remote output clinic","title_fr":"Clinique des sorties à distance","body":"Diagnose PDF, email, and print differences with a shared sample pack.","body_fr":"Diagnostiquez les différences PDF, e-mail et impression avec un dossier partagé.","venue":"Online","date":"2026-10-17","segment":"online","platform":"Example Meet","language":"fr","rsvp_url":"https://workshops.example/fr/remote/rsvp","agenda_1":"Collecte des symptômes","agenda_2":"Inspection des sorties","agenda_3":"Corrections","agenda_4":"Plan de test","outcome_1":"Comparer les canaux","outcome_2":"Isoler les écarts","outcome_3":"Corriger sans duplication","outcome_4":"Automatiser les contrôles","session_1":"Intake","session_2":"Output inspection","session_3":"Fix lab","session_4":"Test plan","session_1_fr":"Accueil","session_2_fr":"Inspection","session_3_fr":"Atelier corrections","session_4_fr":"Plan de test","time_1":"13:00","time_2":"13:45","time_3":"14:45","time_4":"16:00","lead_1":"Priya Anand","lead_2":"Camille Moreau","lead_3":"Maya Chen","lead_4":"Omar Haddad","company":"Northline Learning","contact":"remote@northline.example"}
]`;

export const HANDOUT_PROMO_CSV = `[
  {"product_name":"Atlas Pack","offer_label":"LAUNCH OFFER","offer_label_fr":"OFFRE DE LANCEMENT","title":"Carry less. Publish more.","title_fr":"Transportez moins. Publiez plus.","body":"Choose a tier, use the launch code, and keep every campaign asset together.","body_fr":"Choisissez une formule, utilisez le code de lancement et centralisez vos supports.","base_price":89,"plus_price":149,"pro_price":239,"promo_code":"ATLAS26","store_url":"https://store.example/atlas","language":"en","company":"Northline Commerce","contact":"shop@northline.example"},
  {"product_name":"Kit Canal","offer_label":"AUTUMN SAVING","offer_label_fr":"OFFRE D'AUTOMNE","title":"A complete event kit","title_fr":"Un kit événementiel complet","body":"Handouts, signs, and follow-up emails from one reusable data set.","body_fr":"Prospectus, signalétique et e-mails de suivi depuis un jeu de données réutilisable.","base_price":75,"plus_price":125,"pro_price":210,"promo_code":"CANAL26","store_url":"https://store.example/fr/canal","language":"fr","company":"Northline Commerce","contact":"boutique@northline.example"},
  {"product_name":"Studio Pro","offer_label":"TEAM EDITION","offer_label_fr":"ÉDITION ÉQUIPE","title":"Proof together. Ship once.","title_fr":"Validez ensemble. Livrez une fois.","body":"Give every reviewer a clear lane before the final export.","body_fr":"Attribuez un circuit clair à chaque relecteur avant l'export final.","base_price":120,"plus_price":195,"pro_price":320,"promo_code":"STUDIO26","store_url":"https://store.example/fr/studio","language":"fr","company":"Northline Commerce","contact":"equipes@northline.example"}
]`;

export const TICKET_CONCERT_CSV = `[
  {"ticket_code":"LIVE-2601","event_name":"Northline Live","venue":"Harbor Hall · Antwerp","event_date":"2026-10-17 20:00","holder_name":"Maya Chen","email":"maya@example.com","language":"en","status":"valid","checkin_url":"https://tickets.example/checkin/live-2601"},
  {"ticket_code":"LIVE-2602","event_name":"Northline en concert","venue":"Salle du Canal · Bruxelles","event_date":"2026-10-18 20:30","holder_name":"Camille Moreau","email":"camille@example.com","language":"fr","status":"valid","checkin_url":"https://tickets.example/fr/checkin/live-2602"},
  {"ticket_code":"JAZZ-2603","event_name":"Harbor Jazz Night","venue":"Dock Studio · Rotterdam","event_date":"2026-11-02 19:30","holder_name":"Noah Berg","email":"noah@example.com","language":"en","status":"used","checkin_url":"https://tickets.example/checkin/jazz-2603"},
  {"ticket_code":"CANAL-2604","event_name":"Nuit acoustique","venue":"Maison de la Meuse · Liège","event_date":"2026-11-08 19:00","holder_name":"Léa Martin","email":"lea@example.com","language":"fr","status":"cancelled","checkin_url":"https://tickets.example/fr/checkin/canal-2604"}
]`;

export const TICKET_TRIP_CSV = `[
  {"pnr":"TRIP-8K4M","route":"Antwerp → Paris","carrier":"Example Rail · Car 4 · Seat 18A","departure_at":"2026-10-21 08:42","holder_name":"Marcus Chen","email":"marcus@example.com","language":"en","status":"valid","checkin_url":"https://travel.example/checkin/trip-8k4m"},
  {"pnr":"VOY-7F2Q","route":"Bruxelles → Lyon","carrier":"Rail Exemple · Voiture 7 · Place 22B","departure_at":"2026-10-24 09:17","holder_name":"Camille Moreau","email":"camille@example.com","language":"fr","status":"valid","checkin_url":"https://travel.example/fr/checkin/voy-7f2q"},
  {"pnr":"AIR-3P9L","route":"Amsterdam → Lisbon","carrier":"Example Air · Flight EX104","departure_at":"2026-11-03 14:10","holder_name":"Sofia Reyes","email":"sofia@example.com","language":"en","status":"used","checkin_url":"https://travel.example/checkin/air-3p9l"},
  {"pnr":"VOY-1C6R","route":"Liège → Strasbourg","carrier":"Rail Exemple · Voiture 2 · Place 09C","departure_at":"2026-11-12 07:55","holder_name":"Omar Haddad","email":"omar@example.com","language":"fr","status":"cancelled","checkin_url":"https://travel.example/fr/checkin/voy-1c6r"}
]`;

export const TICKET_GIFT_CSV = `[
  {"code":"GIFT-2601","gift_name":"Weekend pottery workshop","message":"A creative day for two at Harbor Studio","valid_until":"Valid until 2027-03-31","holder_name":"Ivy Chen","email":"ivy@example.com","language":"en","status":"valid","redeem_url":"https://gifts.example/redeem/gift-2601"},
  {"code":"CADEAU-2602","gift_name":"Dégustation au bord du canal","message":"Une soirée gourmande pour deux","valid_until":"Valable jusqu'au 31 mars 2027","holder_name":"Amélie Dupont","email":"amelie@example.com","language":"fr","status":"valid","redeem_url":"https://gifts.example/fr/redeem/cadeau-2602"},
  {"code":"GIFT-2603","gift_name":"Design museum membership","message":"One year of exhibitions and member previews","valid_until":"Valid until 2027-08-31","holder_name":"Aiko Tanaka","email":"aiko@example.com","language":"en","status":"used","redeem_url":"https://gifts.example/redeem/gift-2603"},
  {"code":"CADEAU-2604","gift_name":"Escapade bien-être","message":"Une journée de détente à la Maison Meuse","valid_until":"Valable jusqu'au 30 juin 2027","holder_name":"Nora Petit","email":"nora@example.com","language":"fr","status":"cancelled","redeem_url":"https://gifts.example/fr/redeem/cadeau-2604"}
]`;
