import type { Project } from "../../document";
import { DEMO_IMG } from "../assets";
import { b, page, shell, id, outputsFor } from "../helpers";
import { northlineStyleExtras } from "../brand/northlineStyles";

export {
  email,
  newsletterDigest,
  newsletterProduct,
} from "./newsletters";
export {
  a5Handout,
  handoutPromo,
  handoutWorkshop,
} from "./handouts";

export function paper(): Project {
  return shell(
    {
      name: "Research paper",
      author: "Northline Research",
      subject: "Cover, article body, figures & references",
      description:
        "Multi-page research article: cover with date, abstract reprise, sections, figures, references stub.",
    },
    [
      page("Cover", [
        b("shape", {
          name: "Letterhead",
          x: 0,
          y: 0,
          w: 720,
          h: 64,
          content: { shape: "rect", filled: true },
          style: { background: "#f3f7f6" },
          zIndex: 0,
          pin: { top: true, left: true, right: true },
        }),
        b("text", {
          name: "Journal",
          x: 40,
          y: 14,
          w: 440,
          h: 18,
          content: { text: "{{journal}} · Vol. {{volume}} · {{year}}" },
          style: { fontSize: 11, color: "#0f6b63" },
          zIndex: 1,
        }),
        b("date", {
          name: "Issue date",
          x: 500,
          y: 12,
          w: 180,
          h: 20,
          content: {
            source: "today",
            format: "long",
            label: "",
          },
          style: { fontSize: 10, color: "#5c6570", textAlign: "right", fontFamily: "ui" },
          zIndex: 1,
        }),
        b("paragraph", {
          name: "Title",
          x: 40,
          y: 88,
          w: 620,
          h: 88,
          content: { text: "{{paper_title}}" },
          style: {
            fontSize: 22,
            fontWeight: 700,
            color: "#1c2430",
            textAlign: "center",
            lineHeight: 1.25,
          },
        }),
        b("text", {
          name: "Authors",
          x: 40,
          y: 192,
          w: 620,
          h: 24,
          content: { text: "{{authors}}" },
          style: { fontSize: 13, color: "#1c2430", textAlign: "center" },
        }),
        b("text", {
          name: "Affiliation",
          x: 40,
          y: 224,
          w: 620,
          h: 20,
          content: { text: "{{affiliation}}" },
          style: { fontSize: 11, color: "#5c6570", textAlign: "center" },
        }),
        b("shape", {
          name: "Top rule",
          x: 120,
          y: 260,
          w: 480,
          h: 2,
          content: { shape: "rect", filled: true },
          style: { background: "#0f6b63" },
        }),
        b("text", {
          name: "Abstract label",
          x: 40,
          y: 284,
          w: 120,
          h: 18,
          content: { text: "Abstract" },
          style: { fontSize: 12, fontWeight: 700, color: "#1c2430" },
        }),
        b("paragraph", {
          name: "Abstract",
          x: 40,
          y: 308,
          w: 620,
          h: 200,
          content: {
            text: "{{abstract}}\n\nWe discuss implications for operators who batch thousands of personalized documents nightly and for researchers studying sparse-data regimes in template engines.",
          },
          style: { fontSize: 11, color: "#1c2430", lineHeight: 1.55 },
        }),
        b("text", {
          name: "Keywords",
          x: 40,
          y: 528,
          w: 620,
          h: 28,
          content: { text: "Keywords: {{keywords}}" },
          style: { fontSize: 11, color: "#5c6570" },
        }),
        b("picture", {
          name: "Figure",
          x: 180,
          y: 576,
          w: 360,
          h: 160,
          content: { src: DEMO_IMG.chartThumb, alt: "Figure 1" },
        }),
        b("text", {
          name: "Caption",
          x: 100,
          y: 752,
          w: 520,
          h: 24,
          content: { text: "Figure 1. {{figure_caption}}" },
          style: { fontSize: 10, color: "#5c6570", textAlign: "center" },
        }),
        b("text", {
          name: "Footer",
          x: 40,
          y: 900,
          w: 640,
          h: 18,
          content: {
            text: "© {{year}} {{affiliation}} · {{env.today|date:long}}",
          },
          style: { fontSize: 9, color: "#5c6570", textAlign: "center" },
          pin: { bottom: true, left: true, right: true },
        }),
      ]),
      page("Article", [
        b("shape", {
          name: "Header bar",
          x: 0,
          y: 0,
          w: 720,
          h: 44,
          content: { shape: "rect", filled: true },
          style: { background: "#f8fafb" },
          zIndex: 0,
          pin: { top: true, left: true, right: true },
        }),
        b("text", {
          name: "Running head",
          x: 40,
          y: 14,
          w: 640,
          h: 18,
          content: { text: "{{journal}} · {{paper_title}}" },
          style: { fontSize: 9.5, color: "#5c6570", textAlign: "center" },
          zIndex: 1,
        }),
        b("text", {
          name: "Abstract reprise label",
          x: 40,
          y: 64,
          w: 200,
          h: 18,
          content: { text: "1. Motivation" },
          style: { fontSize: 13, fontWeight: 700, color: "#1c2430" },
        }),
        b("paragraph", {
          name: "Motivation",
          x: 40,
          y: 90,
          w: 620,
          h: 110,
          content: {
            text: "{{abstract}}\n\nThis section restates the problem for readers who skip the cover abstract: how conditional blocks and output-aware workflows behave when source rows are incomplete.",
          },
          style: { fontSize: 11, color: "#1c2430", lineHeight: 1.55 },
        }),
        b("text", {
          name: "Method label",
          x: 40,
          y: 220,
          w: 200,
          h: 18,
          content: { text: "2. Method" },
          style: { fontSize: 13, fontWeight: 700, color: "#1c2430" },
        }),
        b("paragraph", {
          name: "Method col A",
          x: 40,
          y: 248,
          w: 300,
          h: 220,
          content: {
            text: "We evaluate letter and invoice corpora under three merge strategies: static templates, expression-gated blocks, and output-kind variants. Each strategy is scored on correction rate, render latency, and reviewer minutes per thousand documents.",
          },
          style: { fontSize: 11, color: "#1c2430", lineHeight: 1.55 },
        }),
        b("paragraph", {
          name: "Method col B",
          x: 360,
          y: 248,
          w: 300,
          h: 220,
          content: {
            text: "Sandboxed expressions isolate template injection risk. Pinned chrome keeps letterhead and footer consistent across batches. Language variants exercise ADR 0015 document language without forking the layout.",
          },
          style: { fontSize: 11, color: "#1c2430", lineHeight: 1.55 },
        }),
        b("text", {
          name: "Discussion label",
          x: 40,
          y: 492,
          w: 200,
          h: 18,
          content: { text: "3. Discussion" },
          style: { fontSize: 13, fontWeight: 700, color: "#1c2430" },
        }),
        b("paragraph", {
          name: "Discussion",
          x: 40,
          y: 520,
          w: 620,
          h: 160,
          content: {
            text: "Operators prefer a single master template with variants over forked language files. Date filters (`|date:long`) and `env.today` keep journal footers current without editing the project JSON. Keywords: {{keywords}}.",
          },
          style: { fontSize: 11, color: "#1c2430", lineHeight: 1.55 },
        }),
        b("text", {
          name: "Footer",
          x: 40,
          y: 900,
          w: 640,
          h: 18,
          content: {
            text: "{{journal}} · page 2 · {{env.today|date:long}}",
          },
          style: { fontSize: 9, color: "#5c6570", textAlign: "center" },
          pin: { bottom: true, left: true, right: true },
        }),
      ]),
      page("Figures & references", [
        b("shape", {
          name: "Header bar",
          x: 0,
          y: 0,
          w: 720,
          h: 44,
          content: { shape: "rect", filled: true },
          style: { background: "#f8fafb" },
          zIndex: 0,
          pin: { top: true, left: true, right: true },
        }),
        b("text", {
          name: "Running head",
          x: 40,
          y: 14,
          w: 640,
          h: 18,
          content: { text: "{{journal}} · {{paper_title}}" },
          style: { fontSize: 9.5, color: "#5c6570", textAlign: "center" },
          zIndex: 1,
        }),
        b("picture", {
          name: "Figure 2",
          x: 60,
          y: 68,
          w: 280,
          h: 170,
          content: { src: DEMO_IMG.chartThumb, alt: "Figure 2" },
        }),
        b("text", {
          name: "Caption 2",
          x: 40,
          y: 252,
          w: 320,
          h: 40,
          content: {
            text: "Figure 2. Correction rate by merge strategy across the invoice corpus.",
          },
          style: { fontSize: 10, color: "#5c6570", textAlign: "center" },
        }),
        b("picture", {
          name: "Figure 3",
          x: 380,
          y: 68,
          w: 280,
          h: 170,
          content: { src: DEMO_IMG.chartThumb, alt: "Figure 3" },
        }),
        b("text", {
          name: "Caption 3",
          x: 360,
          y: 252,
          w: 320,
          h: 40,
          content: {
            text: "Figure 3. Human review minutes per 1,000 documents under sparse-data conditions.",
          },
          style: { fontSize: 10, color: "#5c6570", textAlign: "center" },
        }),
        b("text", {
          name: "Results label",
          x: 40,
          y: 316,
          w: 240,
          h: 20,
          content: { text: "Key results" },
          style: { fontSize: 12, fontWeight: 700, color: "#1c2430" },
        }),
        b("list", {
          name: "Findings",
          x: 40,
          y: 344,
          w: 620,
          h: 140,
          content: {
            items: [
              "Conditional blocks reduced manual corrections by 38% versus static templates.",
              "Output-aware workflows cut average render time to 120 ms per document.",
              "Sandboxed expressions eliminated all template-injection incidents in the corpus.",
              "Operators preferred pinned chrome for letterhead/footer consistency across batches.",
            ],
            markerColor: "#0f6b63",
          },
          style: { fontSize: 11.5, lineHeight: 1.55, color: "#1c2430" },
        }),
        b("text", {
          name: "References label",
          x: 40,
          y: 508,
          w: 240,
          h: 20,
          content: { text: "References" },
          style: { fontSize: 12, fontWeight: 700, color: "#1c2430" },
        }),
        b("paragraph", {
          name: "References",
          x: 40,
          y: 536,
          w: 620,
          h: 180,
          content: {
            text: "[1] Ng, A., Costa, M., & Berg, L. ({{year}}). Sparse-data regimes in bulk document generation. {{journal}}, {{volume}}(2), 114–131.\n[2] Ferreira, J. (2025). Merge-field semantics for conditional rendering. Proc. DocEng Workshop, 22–30.\n[3] Okafor, D. (2024). Trust boundaries in templating runtimes. Journal of Applied Templates, 12(4), 301–318.\n[4] Hale, J. (2023). Layout density heuristics for print proofs. Preprint.",
          },
          style: { fontSize: 10.5, lineHeight: 1.6, color: "#3d4a5c" },
        }),
        b("paragraph", {
          name: "Correspondence",
          x: 40,
          y: 740,
          w: 620,
          h: 64,
          content: {
            text: "Correspondence: {{authors}}, {{affiliation}}. Keywords cross-reference: {{keywords}}.",
          },
          style: { fontSize: 10, lineHeight: 1.5, color: "#5c6570" },
        }),
        b("text", {
          name: "Footer",
          x: 40,
          y: 900,
          w: 640,
          h: 18,
          content: {
            text: "© {{year}} {{affiliation}} · {{env.today|date:long}}",
          },
          style: { fontSize: 9, color: "#5c6570", textAlign: "center" },
          pin: { bottom: true, left: true, right: true },
        }),
      ]),
    ],
    { outputs: outputsFor("preview", "pdf", "print") },
  );
}

export function newspaper(): Project {
  return shell(
    {
      name: "City newspaper",
      author: "Northline Press",
      subject: "Broadsheet front page with columns",
      description:
        "Masthead, edition date, multi-column body, pull quote, byline, folio. EN/FR headline variants; slim email column.",
    },
    [
      page("Front page", [
        b("shape", {
          name: "Masthead wash",
          x: 0,
          y: 0,
          w: 960,
          h: 88,
          content: { shape: "rect", filled: true },
          style: { background: "#1c2430" },
          zIndex: 0,
          pin: { top: true, left: true, right: true },
        }),
        b("text", {
          name: "Masthead",
          x: 32,
          y: 18,
          w: 560,
          h: 40,
          content: { text: "The {{edition}} Herald" },
          style: {
            fontSize: 28,
            fontWeight: 700,
            color: "#f7f4ef",
            fontFamily: "display",
          },
          zIndex: 1,
        }),
        b("date", {
          name: "Edition date",
          x: 620,
          y: 28,
          w: 300,
          h: 24,
          content: { source: "today", format: "long", label: "" },
          style: {
            fontSize: 12,
            color: "#c8c2b8",
            textAlign: "right",
            fontFamily: "ui",
          },
          zIndex: 1,
        }),
        b("text", {
          name: "Dateline",
          x: 32,
          y: 100,
          w: 896,
          h: 18,
          content: {
            text: "{{city}} · Vol. {{volume|default:42}} · {{env.today|date:short}}",
          },
          style: { fontSize: 11, color: "#5c6570", letterSpacing: 0.04 },
        }),
        b("shape", {
          name: "Rule",
          x: 32,
          y: 124,
          w: 896,
          h: 2,
          content: { shape: "rect", filled: true },
          style: { background: "#1c2430" },
        }),
        b("text", {
          name: "Headline",
          x: 32,
          y: 140,
          w: 600,
          h: 64,
          content: { text: "{{headline}}" },
          style: {
            fontSize: 26,
            fontWeight: 700,
            color: "#1c2430",
            lineHeight: 1.15,
            fontFamily: "display",
          },
          variants: [
            {
              id: id(),
              language: "fr",
              content: { text: "{{headline_fr}}" },
            },
            {
              id: id(),
              output: "email",
              w: 896,
              x: 32,
              style: { fontSize: 22, fontWeight: 700, color: "#1c2430" },
            },
          ],
        }),
        b("paragraph", {
          name: "Lede",
          x: 32,
          y: 212,
          w: 600,
          h: 72,
          content: { text: "{{lede}}" },
          style: { fontSize: 13, color: "#1c2430", lineHeight: 1.45, fontWeight: 600 },
          variants: [
            {
              id: id(),
              language: "fr",
              content: { text: "{{lede_fr}}" },
            },
            {
              id: id(),
              output: "email",
              w: 896,
              x: 32,
            },
          ],
        }),
        b("paragraph", {
          name: "Col 1",
          x: 32,
          y: 296,
          w: 288,
          h: 180,
          content: {
            text: "{{body_col1|default:City officials confirmed overnight that the new document pipeline will cut print turnaround for municipal notices. Residents will see personalized letters instead of generic flyers starting next quarter.}}",
          },
          style: { fontSize: 11, color: "#1c2430", lineHeight: 1.5 },
          condition: "output.kind != 'email'",
        }),
        b("paragraph", {
          name: "Col 2",
          x: 336,
          y: 296,
          w: 288,
          h: 180,
          content: {
            text: "{{body_col2|default:Editors praised the merge-field approach for keeping French and Dutch editions in sync without duplicating layouts. A slim email edition strips side columns for inbox reading.}}",
          },
          style: { fontSize: 11, color: "#1c2430", lineHeight: 1.5 },
          condition: "output.kind != 'email'",
        }),
        b("paragraph", {
          name: "Pull quote",
          x: 640,
          y: 140,
          w: 288,
          h: 140,
          content: {
            text: "“{{pull_quote|default:One master page. Many languages. Zero paste errors.}}”",
          },
          style: {
            fontSize: 15,
            fontWeight: 600,
            color: "#0f6b63",
            lineHeight: 1.35,
            fontFamily: "display",
            background: "#f3f7f6",
            borderRadius: 4,
          },
          condition: "output.kind != 'email'",
        }),
        b("paragraph", {
          name: "Email body",
          x: 32,
          y: 300,
          w: 896,
          h: 140,
          content: {
            text: "{{body_col1|default:City officials confirmed overnight that the new document pipeline will cut print turnaround for municipal notices.}}\n\n{{body_col2|default:Editors praised merge fields for keeping language editions in sync.}}",
          },
          style: { fontSize: 12, color: "#1c2430", lineHeight: 1.5 },
          condition: "output.kind == 'email'",
        }),
        b("text", {
          name: "Byline",
          x: 32,
          y: 488,
          w: 480,
          h: 20,
          content: { text: "By {{byline}} · {{city}}" },
          style: { fontSize: 10, fontWeight: 600, color: "#5c6570" },
        }),
        b("text", {
          name: "Folio",
          x: 520,
          y: 488,
          w: 408,
          h: 20,
          content: {
            text: "A1 · {{edition}} Herald · {{env.today|date:short}}",
          },
          style: { fontSize: 10, color: "#5c6570", textAlign: "right" },
        }),
      ]),
    ],
    {
      artboard: "landscape",
      outputs: outputsFor("preview", "pdf", "print", "email"),
      ...northlineStyleExtras("en"),
    },
  );
}

export function landscapeSlide(): Project {
  return shell(
    {
      name: "Landscape slide",
      author: "texLooper Samples",
      subject: "960×540 artboard",
      description:
        "Wide slide layout — header and footer pinned; body and callout split columns. Output kinds show different chrome.",
    },
    [
      page(
        "Slide",
        [
          b("shape", {
            name: "Header bar",
            x: 0,
            y: 0,
            w: 960,
            h: 72,
            pin: { top: true, left: true, right: true },
            content: { shape: "rect", filled: true },
            style: { background: "#0f6b63" },
            zIndex: 0,
          }),
          b("shape", {
            name: "Accent stripe",
            x: 0,
            y: 72,
            w: 960,
            h: 4,
            pin: { top: true, left: true, right: true },
            content: { shape: "rect", filled: true },
            style: { background: "#c45c26" },
            zIndex: 1,
          }),
          b("text", {
            name: "Title",
            x: 48,
            y: 22,
            w: 580,
            h: 36,
            pin: { top: true, left: true },
            content: { text: "{{title}}" },
            style: { fontSize: 26, fontWeight: 700, color: "#ffffff" },
            zIndex: 2,
          }),
          b("text", {
            name: "Company",
            x: 640,
            y: 28,
            w: 272,
            h: 24,
            pin: { top: true, right: true },
            content: { text: "{{company}}" },
            style: {
              fontSize: 13,
              fontWeight: 600,
              color: "#d4ece8",
              textAlign: "right",
            },
            zIndex: 2,
          }),
          b("paragraph", {
            name: "Body",
            x: 48,
            y: 96,
            w: 528,
            h: 340,
            content: {
              text: "{{body}}\n\nOutput kind: {{output.kind}}",
            },
            style: { fontSize: 16, color: "#2a2622", lineHeight: 1.55 },
          }),
          b("shape", {
            name: "Column rule",
            x: 592,
            y: 96,
            w: 2,
            h: 340,
            content: { shape: "rect", filled: true },
            style: { background: "#e2ddd4" },
          }),
          b("paragraph", {
            name: "Screen only callout",
            x: 608,
            y: 96,
            w: 304,
            h: 168,
            condition: "output.kind == 'preview'",
            content: {
              text: "Screen preview callout\n\nThis panel is hidden on PDF, print, and email outputs. Switch output kind in Automation to compare.",
            },
            style: {
              fontSize: 13,
              background: "#eef6f5",
              padding: 14,
              color: "#0f6b63",
              lineHeight: 1.45,
            },
          }),
          b("shape", {
            name: "Footer bar",
            x: 0,
            y: 492,
            w: 960,
            h: 48,
            pin: { bottom: true, left: true, right: true },
            content: { shape: "rect", filled: true },
            style: { background: "#f3f0ea" },
            zIndex: 0,
          }),
          b("text", {
            name: "Email subject",
            x: 48,
            y: 504,
            w: 864,
            h: 24,
            pin: { bottom: true, left: true, right: true },
            condition: "output.kind == 'email'",
            content: { text: "Subject: {{title}} — {{company}}" },
            style: { fontSize: 14, fontWeight: 600, color: "#1c2430" },
            zIndex: 1,
          }),
          b("text", {
            name: "Print note",
            x: 48,
            y: 506,
            w: 864,
            h: 22,
            pin: { bottom: true, left: true, right: true },
            condition: "output.kind == 'pdf' || output.kind == 'print'",
            content: { text: "{{company}} · Confidential · print/PDF only" },
            style: { fontSize: 11, color: "#6b6560", textAlign: "center" },
            zIndex: 1,
          }),
          b("text", {
            name: "Screen footer",
            x: 48,
            y: 506,
            w: 864,
            h: 22,
            pin: { bottom: true, left: true, right: true },
            condition: "output.kind == 'preview'",
            content: { text: "Screen · {{output.kind}} · {{company}}" },
            style: { fontSize: 11, color: "#6b6560", textAlign: "center" },
            zIndex: 1,
          }),
        ],
        {
          spread: false,
          margins: { top: 0, right: 0, bottom: 0, left: 0 },
          background: "#ffffff",
        },
      ),
    ],
    {
      artboard: "landscape",
      outputs: outputsFor("preview", "pdf", "image", "email"),
    },
  );
}
