import type { Project } from "../../document";
import {
  defaultOutputs,
  optionalOutputTemplates,
} from "../../workflow";
import { DEMO_IMG } from "../assets";
import { b, page, shell } from "../helpers";
import { northlineStyleExtras, nlText, NL } from "../brand/northlineStyles";

export function email(): Project {
  const api = optionalOutputTemplates().find((o) => o.kind === "api");
  return shell(
    {
      name: "Email newsletter",
      author: "Northline Lifecycle",
      subject: "Transactional + marketing email frame",
      description:
        "Email-safe single column: preheader, logo, hero, modules, footer unsubscribe. API output ready.",
    },
    [
      page("Message", [
        b("shape", {
          name: "Header bar",
          x: 0,
          y: 0,
          w: 720,
          h: 48,
          content: { shape: "rect", filled: true },
          style: { background: "#eef2f6" },
          zIndex: 0,
          pin: { top: true, left: true, right: true },
        }),
        b("text", {
          name: "Preheader",
          x: 48,
          y: 16,
          w: 520,
          h: 16,
          content: { text: "{{preheader}}" },
          style: { fontSize: 9, color: "#9aa3ad" },
          zIndex: 1,
        }),
        b("shape", {
          name: "Canvas",
          x: 40,
          y: 56,
          w: 640,
          h: 780,
          content: { shape: "rect" },
          style: { background: "#ffffff", borderRadius: 2 },
          zIndex: 0,
        }),
        b("picture", {
          name: "Logo",
          x: 64,
          y: 72,
          w: 120,
          h: 36,
          content: { src: DEMO_IMG.logoMark, alt: "Northline" },
          zIndex: 1,
        }),
        b("picture", {
          name: "Hero",
          x: 64,
          y: 124,
          w: 592,
          h: 180,
          content: { src: DEMO_IMG.productHero, alt: "Feature" },
          zIndex: 1,
        }),
        b("text", {
          name: "Title",
          x: 64,
          y: 324,
          w: 592,
          h: 32,
          content: { text: "{{title}}" },
          style: { fontSize: 20, fontWeight: 700, color: "#1c2430" },
          zIndex: 1,
        }),
        b("paragraph", {
          name: "Intro",
          x: 64,
          y: 368,
          w: 592,
          h: 120,
          content: {
            text: "Hi {{first_name}},\n\n{{intro}}\n\nWe put the important updates below so you can skim in under a minute — then dig into the full changelog when you have time.",
          },
          style: { fontSize: 13, color: "#3d4a5c", lineHeight: 1.55 },
          zIndex: 1,
        }),
        b("table", {
          name: "Modules",
          x: 64,
          y: 508,
          w: 592,
          h: 120,
          content: {
            rows: 3,
            cols: 2,
            cells: [
              ["Update", "Detail"],
              ["{{mod1_title}}", "{{mod1_body}}"],
              ["{{mod2_title}}", "{{mod2_body}}"],
            ],
          },
          style: { fontSize: 11 },
          zIndex: 1,
        }),
        b("text", {
          name: "CTA EN",
          x: 64,
          y: 652,
          w: 400,
          h: 28,
          content: { text: "→ {{cta_label}}" },
          style: { ...nlText("nl-h3"), color: NL.accent },
          zIndex: 1,
          condition: "vars.language != 'fr'",
        }),
        b("text", {
          name: "CTA FR",
          x: 64,
          y: 652,
          w: 400,
          h: 28,
          content: { text: "→ {{cta_label}}" },
          style: { ...nlText("nl-h3"), color: NL.accent },
          zIndex: 1,
          condition: "vars.language == 'fr'",
        }),
        b("picture", {
          name: "Avatar",
          x: 64,
          y: 700,
          w: 48,
          h: 48,
          content: { src: DEMO_IMG.headshot, alt: "Author" },
          zIndex: 1,
        }),
        b("text", {
          name: "From",
          x: 124,
          y: 708,
          w: 360,
          h: 40,
          content: { text: "{{sender_name}}\n{{sender_role}}" },
          style: { fontSize: 11, color: "#5c6570" },
          zIndex: 1,
        }),
        b("text", {
          name: "Footer",
          x: 64,
          y: 900,
          w: 592,
          h: 40,
          content: {
            text: "You’re receiving this because you subscribed as {{email}}.\nUnsubscribe · {{unsub_url}} · © {{year}} Northline",
          },
          style: { fontSize: 9, color: "#9aa3ad", textAlign: "center" },
          zIndex: 1,
          pin: { bottom: true, left: true, right: true },
        }),
        b("text", {
          name: "API hint",
          x: 64,
          y: 860,
          w: 400,
          h: 16,
          content: { text: "Emit via API · {{output.apiMethod}} {{output.apiUrl}}" },
          style: { fontSize: 9, color: "#0f6b63" },
          condition: "output.kind == 'api'",
          zIndex: 1,
        }),
      ]),
      page("Plain-text version", [
        b("shape", {
          name: "Header bar",
          x: 0,
          y: 0,
          w: 720,
          h: 40,
          content: { shape: "rect", filled: true },
          style: { background: "#f2f4f7" },
          zIndex: 0,
          pin: { top: true, left: true, right: true },
        }),
        b("text", {
          name: "PT subject",
          x: 40,
          y: 56,
          w: 620,
          h: 22,
          content: { text: "Subject: {{title}}" },
          style: { fontSize: 13, fontWeight: 700, color: "#1c2430" },
        }),
        b("text", {
          name: "PT preheader",
          x: 40,
          y: 84,
          w: 620,
          h: 18,
          content: { text: "{{preheader}}" },
          style: { fontSize: 11, color: "#5c6570" },
        }),
        b("shape", {
          name: "Top rule",
          x: 40,
          y: 112,
          w: 620,
          h: 1,
          content: { variant: "line" },
          style: { borderWidth: 1, borderColor: "#d4d9e0" },
        }),
        b("paragraph", {
          name: "PT greeting + intro",
          x: 40,
          y: 132,
          w: 620,
          h: 160,
          content: {
            text: "Hi {{first_name}},\n\n{{intro}}\n\nWe keep this plain-text edition short so it renders anywhere — including clients that strip HTML. If images matter, open the HTML version from your inbox archive.",
          },
          style: { fontSize: 12, lineHeight: 1.55, color: "#1c2430" },
        }),
        b("paragraph", {
          name: "PT module 1",
          x: 40,
          y: 316,
          w: 620,
          h: 88,
          content: {
            text: "* {{mod1_title}}\n  {{mod1_body}}",
          },
          style: { fontSize: 12, lineHeight: 1.5, color: "#1c2430" },
        }),
        b("paragraph", {
          name: "PT module 2",
          x: 40,
          y: 424,
          w: 620,
          h: 88,
          content: {
            text: "* {{mod2_title}}\n  {{mod2_body}}",
          },
          style: { fontSize: 12, lineHeight: 1.5, color: "#1c2430" },
        }),
        b("text", {
          name: "PT cta",
          x: 40,
          y: 536,
          w: 620,
          h: 28,
          content: { text: "{{cta_label}}: {{cta_url}}" },
          style: { fontSize: 12, fontWeight: 600, color: "#0f6b63" },
        }),
        b("shape", {
          name: "PT rule 2",
          x: 40,
          y: 584,
          w: 620,
          h: 1,
          content: { variant: "line" },
          style: { borderWidth: 1, borderColor: "#d4d9e0" },
        }),
        b("paragraph", {
          name: "PT signature",
          x: 40,
          y: 608,
          w: 620,
          h: 100,
          content: {
            text: "— {{sender_name}}, {{sender_role}}\nReply to this email with questions; a human reads every response.\n\nPrefer fewer emails? Update preferences anytime from your account settings.",
          },
          style: { fontSize: 11, lineHeight: 1.5, color: "#3d4a5c" },
        }),
        b("paragraph", {
          name: "Footer",
          x: 40,
          y: 880,
          w: 620,
          h: 44,
          content: {
            text: "You are receiving this because you subscribed as {{email}}.\nUnsubscribe: {{unsub_url}} · © {{year}} Northline",
          },
          style: { fontSize: 9, lineHeight: 1.5, color: "#9aa3ad", textAlign: "center" },
          pin: { bottom: true, left: true, right: true },
        }),
      ]),
    ],
    {
      outputs: api ? [...defaultOutputs(), api] : defaultOutputs(),
      ...northlineStyleExtras("en"),
    },
  );
}

export function paper(): Project {
  return shell(
    {
      name: "Research paper cover",
      author: "Northline Research",
      subject: "Academic-style title page + abstract",
      description:
        "Paper cover: title, authors, affiliation, abstract, keywords, figure placeholder.",
    },
    [
      page("Cover", [
        b("shape", {
          name: "Letterhead",
          x: 0,
          y: 0,
          w: 720,
          h: 64,
          content: { shape: "rect", filled: true },
          style: { background: "#f3f7f6" },
          zIndex: 0,
          pin: { top: true, left: true, right: true },
        }),
        b("text", {
          name: "Journal",
          x: 40,
          y: 24,
          w: 640,
          h: 18,
          content: { text: "{{journal}} · Vol. {{volume}} · {{year}}" },
          style: { fontSize: 11, color: "#0f6b63" },
          zIndex: 1,
        }),
        b("paragraph", {
          name: "Title",
          x: 40,
          y: 88,
          w: 620,
          h: 88,
          content: { text: "{{paper_title}}" },
          style: { fontSize: 22, fontWeight: 700, color: "#1c2430", textAlign: "center", lineHeight: 1.25 },
        }),
        b("text", {
          name: "Authors",
          x: 40,
          y: 192,
          w: 620,
          h: 24,
          content: { text: "{{authors}}" },
          style: { fontSize: 13, color: "#1c2430", textAlign: "center" },
        }),
        b("text", {
          name: "Affiliation",
          x: 40,
          y: 224,
          w: 620,
          h: 20,
          content: { text: "{{affiliation}}" },
          style: { fontSize: 11, color: "#5c6570", textAlign: "center" },
        }),
        b("shape", {
          name: "Top rule",
          x: 120,
          y: 260,
          w: 480,
          h: 2,
          content: { shape: "rect", filled: true },
          style: { background: "#0f6b63" },
        }),
        b("text", {
          name: "Abstract label",
          x: 40,
          y: 284,
          w: 120,
          h: 18,
          content: { text: "Abstract" },
          style: { fontSize: 12, fontWeight: 700, color: "#1c2430" },
        }),
        b("paragraph", {
          name: "Abstract",
          x: 40,
          y: 308,
          w: 620,
          h: 200,
          content: {
            text: "{{abstract}}\n\nWe discuss implications for operators who batch thousands of personalized documents nightly and for researchers studying sparse-data regimes in template engines.",
          },
          style: { fontSize: 11, color: "#1c2430", lineHeight: 1.55 },
        }),
        b("text", {
          name: "Keywords",
          x: 40,
          y: 528,
          w: 620,
          h: 28,
          content: { text: "Keywords: {{keywords}}" },
          style: { fontSize: 11, color: "#5c6570" },
        }),
        b("picture", {
          name: "Figure",
          x: 180,
          y: 576,
          w: 360,
          h: 160,
          content: { src: DEMO_IMG.chartThumb, alt: "Figure 1" },
        }),
        b("text", {
          name: "Caption",
          x: 100,
          y: 752,
          w: 520,
          h: 24,
          content: { text: "Figure 1. {{figure_caption}}" },
          style: { fontSize: 10, color: "#5c6570", textAlign: "center" },
        }),
        b("text", {
          name: "Footer",
          x: 40,
          y: 900,
          w: 640,
          h: 18,
          content: { text: "© {{year}} {{affiliation}} · CC BY 4.0" },
          style: { fontSize: 9, color: "#5c6570", textAlign: "center" },
          pin: { bottom: true, left: true, right: true },
        }),
      ]),
      page("Figures & references", [
        b("shape", {
          name: "Header bar",
          x: 0,
          y: 0,
          w: 720,
          h: 44,
          content: { shape: "rect", filled: true },
          style: { background: "#f8fafb" },
          zIndex: 0,
          pin: { top: true, left: true, right: true },
        }),
        b("text", {
          name: "Running head",
          x: 40,
          y: 14,
          w: 640,
          h: 18,
          content: { text: "{{journal}} · {{paper_title}}" },
          style: { fontSize: 9.5, color: "#5c6570", textAlign: "center" },
          zIndex: 1,
        }),
        b("picture", {
          name: "Figure 2",
          x: 60,
          y: 68,
          w: 280,
          h: 170,
          content: { src: DEMO_IMG.chartThumb, alt: "Figure 2" },
        }),
        b("text", {
          name: "Caption 2",
          x: 40,
          y: 252,
          w: 320,
          h: 40,
          content: {
            text: "Figure 2. Correction rate by merge strategy across the invoice corpus.",
          },
          style: { fontSize: 10, color: "#5c6570", textAlign: "center" },
        }),
        b("picture", {
          name: "Figure 3",
          x: 380,
          y: 68,
          w: 280,
          h: 170,
          content: { src: DEMO_IMG.chartThumb, alt: "Figure 3" },
        }),
        b("text", {
          name: "Caption 3",
          x: 360,
          y: 252,
          w: 320,
          h: 40,
          content: {
            text: "Figure 3. Human review minutes per 1,000 documents under sparse-data conditions.",
          },
          style: { fontSize: 10, color: "#5c6570", textAlign: "center" },
        }),
        b("text", {
          name: "Results label",
          x: 40,
          y: 316,
          w: 240,
          h: 20,
          content: { text: "Key results" },
          style: { fontSize: 12, fontWeight: 700, color: "#1c2430" },
        }),
        b("list", {
          name: "Findings",
          x: 40,
          y: 344,
          w: 620,
          h: 140,
          content: {
            items: [
              "Conditional blocks reduced manual corrections by 38% versus static templates.",
              "Output-aware workflows cut average render time to 120 ms per document.",
              "Sandboxed expressions eliminated all template-injection incidents in the corpus.",
              "Operators preferred pinned chrome for letterhead/footer consistency across batches.",
            ],
            markerColor: "#0f6b63",
          },
          style: { fontSize: 11.5, lineHeight: 1.55, color: "#1c2430" },
        }),
        b("text", {
          name: "References label",
          x: 40,
          y: 508,
          w: 240,
          h: 20,
          content: { text: "References" },
          style: { fontSize: 12, fontWeight: 700, color: "#1c2430" },
        }),
        b("paragraph", {
          name: "References",
          x: 40,
          y: 536,
          w: 620,
          h: 180,
          content: {
            text: "[1] Ng, A., Costa, M., & Berg, L. ({{year}}). Sparse-data regimes in bulk document generation. {{journal}}, {{volume}}(2), 114–131.\n[2] Ferreira, J. (2025). Merge-field semantics for conditional rendering. Proc. DocEng Workshop, 22–30.\n[3] Okafor, D. (2024). Trust boundaries in templating runtimes. Journal of Applied Templates, 12(4), 301–318.\n[4] Hale, J. (2023). Layout density heuristics for print proofs. Preprint.",
          },
          style: { fontSize: 10.5, lineHeight: 1.6, color: "#3d4a5c" },
        }),
        b("paragraph", {
          name: "Correspondence",
          x: 40,
          y: 740,
          w: 620,
          h: 64,
          content: {
            text: "Correspondence: {{authors}}, {{affiliation}}. Keywords cross-reference: {{keywords}}.",
          },
          style: { fontSize: 10, lineHeight: 1.5, color: "#5c6570" },
        }),
        b("text", {
          name: "Footer",
          x: 40,
          y: 900,
          w: 640,
          h: 18,
          content: { text: "© {{year}} {{affiliation}} · CC BY 4.0" },
          style: { fontSize: 9, color: "#5c6570", textAlign: "center" },
          pin: { bottom: true, left: true, right: true },
        }),
      ]),
    ],
  );
}

export function landscapeSlide(): Project {
  return shell(
    {
      name: "Landscape slide",
      author: "texLooper Samples",
      subject: "960×540 artboard",
      description:
        "Wide slide layout — header and footer pinned; body and callout split columns. Output kinds show different chrome.",
    },
    [
      page(
        "Slide",
        [
          b("shape", {
            name: "Header bar",
            x: 0,
            y: 0,
            w: 960,
            h: 72,
            pin: { top: true, left: true, right: true },
            content: { shape: "rect", filled: true },
            style: { background: "#0f6b63" },
            zIndex: 0,
          }),
          b("shape", {
            name: "Accent stripe",
            x: 0,
            y: 72,
            w: 960,
            h: 4,
            pin: { top: true, left: true, right: true },
            content: { shape: "rect", filled: true },
            style: { background: "#c45c26" },
            zIndex: 1,
          }),
          b("text", {
            name: "Title",
            x: 48,
            y: 22,
            w: 580,
            h: 36,
            pin: { top: true, left: true },
            content: { text: "{{title}}" },
            style: { fontSize: 26, fontWeight: 700, color: "#ffffff" },
            zIndex: 2,
          }),
          b("text", {
            name: "Company",
            x: 640,
            y: 28,
            w: 272,
            h: 24,
            pin: { top: true, right: true },
            content: { text: "{{company}}" },
            style: {
              fontSize: 13,
              fontWeight: 600,
              color: "#d4ece8",
              textAlign: "right",
            },
            zIndex: 2,
          }),
          b("paragraph", {
            name: "Body",
            x: 48,
            y: 96,
            w: 528,
            h: 340,
            content: {
              text: "{{body}}\n\nOutput kind: {{output.kind}}",
            },
            style: { fontSize: 16, color: "#2a2622", lineHeight: 1.55 },
          }),
          b("shape", {
            name: "Column rule",
            x: 592,
            y: 96,
            w: 2,
            h: 340,
            content: { shape: "rect", filled: true },
            style: { background: "#e2ddd4" },
          }),
          b("paragraph", {
            name: "Screen only callout",
            x: 608,
            y: 96,
            w: 304,
            h: 168,
            condition: "output.kind == 'preview'",
            content: {
              text: "Screen preview callout\n\nThis panel is hidden on PDF, print, and email outputs. Switch output kind in Automation to compare.",
            },
            style: {
              fontSize: 13,
              background: "#eef6f5",
              padding: 14,
              color: "#0f6b63",
              lineHeight: 1.45,
            },
          }),
          b("shape", {
            name: "Footer bar",
            x: 0,
            y: 492,
            w: 960,
            h: 48,
            pin: { bottom: true, left: true, right: true },
            content: { shape: "rect", filled: true },
            style: { background: "#f3f0ea" },
            zIndex: 0,
          }),
          b("text", {
            name: "Email subject",
            x: 48,
            y: 504,
            w: 864,
            h: 24,
            pin: { bottom: true, left: true, right: true },
            condition: "output.kind == 'email'",
            content: { text: "Subject: {{title}} — {{company}}" },
            style: { fontSize: 14, fontWeight: 600, color: "#1c2430" },
            zIndex: 1,
          }),
          b("text", {
            name: "Print note",
            x: 48,
            y: 506,
            w: 864,
            h: 22,
            pin: { bottom: true, left: true, right: true },
            condition: "output.kind == 'pdf' || output.kind == 'print'",
            content: { text: "{{company}} · Confidential · print/PDF only" },
            style: { fontSize: 11, color: "#6b6560", textAlign: "center" },
            zIndex: 1,
          }),
          b("text", {
            name: "Screen footer",
            x: 48,
            y: 506,
            w: 864,
            h: 22,
            pin: { bottom: true, left: true, right: true },
            condition: "output.kind == 'preview'",
            content: { text: "Screen · {{output.kind}} · {{company}}" },
            style: { fontSize: 11, color: "#6b6560", textAlign: "center" },
            zIndex: 1,
          }),
        ],
        {
          spread: false,
          margins: { top: 0, right: 0, bottom: 0, left: 0 },
          background: "#ffffff",
        },
      ),
    ],
    { artboard: "landscape" },
  );
}

export function a5Handout(): Project {
  return shell(
    {
      name: "A5 handout",
      author: "texLooper Samples",
      subject: "505×714 compact flyer",
      description:
        "Portrait A5 one-pager: pinned header/footer, merge fields, and output-specific notes.",
    },
    [
      page(
        "Handout",
        [
          b("shape", {
            name: "Header bar",
            x: 0,
            y: 0,
            w: 505,
            h: 56,
            pin: { top: true, left: true, right: true },
            content: { shape: "rect", filled: true },
            style: { background: "#0f6b63" },
            zIndex: 0,
          }),
          b("text", {
            name: "Company",
            x: 32,
            y: 18,
            w: 200,
            h: 22,
            pin: { top: true, left: true },
            content: { text: "{{company}}" },
            style: { fontSize: 14, fontWeight: 700, color: "#ffffff" },
            zIndex: 1,
          }),
          b("text", {
            name: "Date",
            x: 273,
            y: 20,
            w: 200,
            h: 18,
            pin: { top: true, right: true },
            content: { text: "{{date|date:short}}" },
            style: { fontSize: 11, color: "#d4ece8", textAlign: "right" },
            zIndex: 1,
          }),
          b("text", {
            name: "Title",
            x: 32,
            y: 72,
            w: 441,
            h: 32,
            content: { text: "{{title}}" },
            style: { fontSize: 22, fontWeight: 700, color: "#1c2430" },
          }),
          b("paragraph", {
            name: "Body",
            x: 32,
            y: 116,
            w: 441,
            h: 320,
            content: { text: "{{body}}" },
            style: { fontSize: 12, color: "#2a2622", lineHeight: 1.55 },
          }),
          b("list", {
            name: "Highlights",
            x: 32,
            y: 448,
            w: 441,
            h: 120,
            content: {
              items: [
                "{{highlight_1}}",
                "{{highlight_2}}",
                "{{highlight_3}}",
              ],
              markerColor: "#0f6b63",
            },
            style: { fontSize: 11.5, lineHeight: 1.5, color: "#3d4a5c" },
          }),
          b("paragraph", {
            name: "Screen callout",
            x: 32,
            y: 580,
            w: 441,
            h: 56,
            condition: "output.kind == 'preview'",
            content: {
              text: "Screen note — contact block below is omitted on email.",
            },
            style: {
              fontSize: 10,
              background: "#eef6f5",
              padding: 10,
              color: "#0f6b63",
            },
          }),
          b("text", {
            name: "Contact",
            x: 32,
            y: 648,
            w: 441,
            h: 36,
            pin: { bottom: true, left: true, right: true },
            condition: "output.kind != 'email'",
            content: {
              text: "{{contact}} · {{company}}",
            },
            style: { fontSize: 10, color: "#5c6570", textAlign: "center" },
          }),
          b("text", {
            name: "Email lead",
            x: 32,
            y: 648,
            w: 441,
            h: 36,
            pin: { bottom: true, left: true, right: true },
            condition: "output.kind == 'email'",
            content: { text: "Reply to: {{contact}}" },
            style: { fontSize: 11, fontWeight: 600, color: "#1c2430", textAlign: "center" },
          }),
        ],
        {
          margins: { top: 0, right: 32, bottom: 40, left: 32 },
          background: "#ffffff",
        },
      ),
    ],
    { artboard: "a5" },
  );
}

