import type { Project } from "../../document";
import { createId } from "../../document";
import {
  defaultOutputs,
  optionalOutputTemplates,
} from "../../workflow";
import { DEMO_IMG } from "../assets";
import { b, page, shell } from "../helpers";
import { northlineStyleExtras } from "../brand/northlineStyles";

const ACCENT = "#0f6b63";
const INK = "#1c2430";
const MUTED = "#5c6570";

export function welcome(): Project {
  const blockA = createId();
  const FULL =
    "output.kind != 'sms' && output.kind != 'email' && output.kind != 'mobile'";
  const EN = "vars.language == 'en'";
  const FR = "vars.language == 'fr'";
  const NL = "vars.language == 'nl'";
  const SMS = "output.kind == 'sms'";
  const EMAIL = "output.kind == 'email'";
  const channelOutputs = optionalOutputTemplates().filter(
    (o) => o.kind === "sms" || o.kind === "print",
  );
  return shell(
    {
      name: "Welcome to texLooper",
      author: "You",
      subject: "Quickstart sample — {{name|default:friend}}",
      description:
        "Multi-language (EN/FR/NL) × multi-output (Screen/PDF/Email/SMS/Print) showcase. Switch Preview row language and output kind for channel-specific layouts. Also demos merge fields, filters, typography, lists, tables, shapes, and groups.",
    },
    [
      page(
        "Features",
        [
          /* ── SMS × language ── */
          b("text", {
            name: "SMS greeting EN",
            x: 40,
            y: 860,
            w: 640,
            h: 36,
            content: { text: "Hi {{name|default:there}}, welcome to texLooper!" },
            style: { fontFamily: "ui", fontSize: 14, fontWeight: 600, color: "#1c2430" },
            condition: `${SMS} && ${EN}`,
          }),
          b("text", {
            name: "SMS greeting FR",
            x: 40,
            y: 860,
            w: 640,
            h: 36,
            content: { text: "Bonjour {{name|default:là}}, bienvenue sur texLooper !" },
            style: { fontFamily: "ui", fontSize: 14, fontWeight: 600, color: "#1c2430" },
            condition: `${SMS} && ${FR}`,
          }),
          b("text", {
            name: "SMS greeting NL",
            x: 40,
            y: 860,
            w: 640,
            h: 36,
            content: { text: "Hoi {{name|default:daar}}, welkom bij texLooper!" },
            style: { fontFamily: "ui", fontSize: 14, fontWeight: 600, color: "#1c2430" },
            condition: `${SMS} && ${NL}`,
          }),
          b("text", {
            name: "SMS body EN",
            x: 40,
            y: 902,
            w: 640,
            h: 36,
            content: { text: "This is the SMS version — short, plain text only. Reply STOP to {{opt_out_code}}." },
            style: { fontFamily: "ui", fontSize: 12, color: "#1c2430" },
            condition: `${SMS} && ${EN}`,
          }),
          b("text", {
            name: "SMS body FR",
            x: 40,
            y: 902,
            w: 640,
            h: 36,
            content: { text: "Version SMS — texte court uniquement. Passez en Aperçu ou PDF pour le document complet." },
            style: { fontFamily: "ui", fontSize: 12, color: "#1c2430" },
            condition: `${SMS} && ${FR}`,
          }),
          b("text", {
            name: "SMS body NL",
            x: 40,
            y: 902,
            w: 640,
            h: 36,
            content: { text: "Dit is de SMS-versie — kort en zonder opmaak. Kies Preview of PDF voor het volledige document." },
            style: { fontFamily: "ui", fontSize: 12, color: "#1c2430" },
            condition: `${SMS} && ${NL}`,
          }),
          b("text", {
            name: "SMS closing EN",
            x: 40,
            y: 944,
            w: 640,
            h: 16,
            content: { text: "texlooper.app" },
            style: { fontFamily: "mono", fontSize: 9, color: "#5c6570" },
            condition: `${SMS} && ${EN}`,
          }),
          b("text", {
            name: "SMS closing FR",
            x: 40,
            y: 944,
            w: 640,
            h: 16,
            content: { text: "texlooper.app · FR" },
            style: { fontFamily: "mono", fontSize: 9, color: "#5c6570" },
            condition: `${SMS} && ${FR}`,
          }),
          b("text", {
            name: "SMS closing NL",
            x: 40,
            y: 944,
            w: 640,
            h: 16,
            content: { text: "texlooper.app · NL" },
            style: { fontFamily: "mono", fontSize: 9, color: "#5c6570" },
            condition: `${SMS} && ${NL}`,
          }),

          /* ── Email-only message (fair HTML preview) ── */
          b("text", {
            name: "Email brand",
            x: 40,
            y: 40,
            w: 520,
            h: 24,
            content: { text: "texLooper" },
            style: {
              fontFamily: "ui",
              fontSize: 13,
              fontWeight: 700,
              color: ACCENT,
              letterSpacing: 0.4,
            },
            condition: EMAIL,
          }),
          b("text", {
            name: "Email title EN",
            x: 40,
            y: 80,
            w: 520,
            h: 40,
            content: { text: "Hello {{name|upper|default:THERE}}" },
            style: {
              fontFamily: "display",
              fontSize: 26,
              fontWeight: 700,
              color: INK,
            },
            condition: `${EMAIL} && ${EN}`,
          }),
          b("text", {
            name: "Email title FR",
            x: 40,
            y: 80,
            w: 520,
            h: 40,
            content: { text: "Bonjour {{name|upper|default:LÀ}}" },
            style: {
              fontFamily: "display",
              fontSize: 26,
              fontWeight: 700,
              color: INK,
            },
            condition: `${EMAIL} && ${FR}`,
          }),
          b("text", {
            name: "Email title NL",
            x: 40,
            y: 80,
            w: 520,
            h: 40,
            content: { text: "Hoi {{name|upper|default:DAAR}}" },
            style: {
              fontFamily: "display",
              fontSize: 26,
              fontWeight: 700,
              color: INK,
            },
            condition: `${EMAIL} && ${NL}`,
          }),
          b("text", {
            name: "Email role",
            x: 40,
            y: 128,
            w: 520,
            h: 22,
            content: { text: "Role: {{role}}" },
            style: { fontFamily: "ui", fontSize: 13, color: MUTED },
            condition: EMAIL,
          }),
          b("paragraph", {
            name: "Email body EN",
            x: 40,
            y: 164,
            w: 520,
            h: 90,
            content: {
              text: "This is the email channel — a stacked HTML message, not the page canvas. Merged values resolve from the row; empty fields stay visible as {{tokens}} so you can spot gaps before send.\n\nCompany: {{company|default:texLooper}}\nNote: {{optional_note}}",
            },
            style: { fontSize: 13, lineHeight: 1.55, color: INK },
            condition: `${EMAIL} && ${EN}`,
          }),
          b("paragraph", {
            name: "Email body FR",
            x: 40,
            y: 164,
            w: 520,
            h: 90,
            content: {
              text: "Canal e-mail — message HTML empilé, pas le canevas page. Les champs fusionnés viennent de la ligne ; les vides restent visibles en {{jetons}}.\n\nSociété : {{company|default:texLooper}}\nNote : {{optional_note}}",
            },
            style: { fontSize: 13, lineHeight: 1.55, color: INK },
            condition: `${EMAIL} && ${FR}`,
          }),
          b("paragraph", {
            name: "Email body NL",
            x: 40,
            y: 164,
            w: 520,
            h: 90,
            content: {
              text: "E-mailkanaal — gestapelde HTML, niet het paginacanvas. Ontbrekende velden blijven zichtbaar als {{tokens}}.\n\nBedrijf: {{company|default:texLooper}}\nNotitie: {{optional_note}}",
            },
            style: { fontSize: 13, lineHeight: 1.55, color: INK },
            condition: `${EMAIL} && ${NL}`,
          }),
          b("link", {
            name: "Email CTA",
            x: 40,
            y: 270,
            w: 200,
            h: 36,
            content: {
              label: "Open in texLooper",
              target: "https://texlooper.app",
            },
            style: {
              fontFamily: "ui",
              fontSize: 13,
              fontWeight: 600,
              color: "#ffffff",
              background: ACCENT,
              padding: 10,
              borderRadius: 6,
              textAlign: "center",
            },
            condition: EMAIL,
          }),
          b("text", {
            name: "Email footer",
            x: 40,
            y: 330,
            w: 520,
            h: 20,
            content: { text: "You are receiving this because {{email}} is on the sample list." },
            style: { fontFamily: "ui", fontSize: 11, color: MUTED },
            condition: EMAIL,
          }),

          /* ── Full document (Screen / PDF / Print / Image) ── */
          /* ── Header ── */
          b("shape", {
            name: "Letterhead",
            x: 0,
            y: 0,
            w: 720,
            h: 72,
            content: { shape: "rect", filled: true },
            style: { background: "#f3f7fb" },
            zIndex: 0,
            pin: { top: true, left: true, right: true },
            condition: FULL,
          }),
          b("picture", {
            name: "Logo",
            x: 40,
            y: 16,
            w: 140,
            h: 40,
            content: { src: DEMO_IMG.logoMark, alt: "Northline" },
            condition: FULL,
            zIndex: 1,
          }),
          b("text", {
            name: "Sender",
            x: 200,
            y: 24,
            w: 480,
            h: 22,
            content: { text: "texLooper · Quickstart guide" },
            style: { fontFamily: "ui", fontSize: 11, color: "#5c6570", textAlign: "right" },
            condition: FULL,
            zIndex: 1,
          }),
          b("text", {
            name: "Title EN",
            x: 40,
            y: 88,
            w: 640,
            h: 48,
            content: { text: "Hello {{name|upper}}" },
            style: { fontFamily: "display", fontSize: 28, fontWeight: 700, color: "#1c2430" },
            bindings: { text: "name" },
            condition: `${FULL} && ${EN}`,
          }),
          b("text", {
            name: "Title FR",
            x: 40,
            y: 88,
            w: 640,
            h: 48,
            content: { text: "Bonjour {{name|upper}}" },
            style: { fontFamily: "display", fontSize: 28, fontWeight: 700, color: "#1c2430" },
            bindings: { text: "name" },
            condition: `${FULL} && ${FR}`,
          }),
          b("text", {
            name: "Title NL",
            x: 40,
            y: 88,
            w: 640,
            h: 48,
            content: { text: "Hallo {{name|upper}}" },
            style: { fontFamily: "display", fontSize: 28, fontWeight: 700, color: "#1c2430" },
            bindings: { text: "name" },
            condition: `${FULL} && ${NL}`,
          }),
          b("text", {
            name: "Role line",
            x: 40,
            y: 140,
            w: 300,
            h: 20,
            content: { text: "Role: {{role}}" },
            style: { fontFamily: "ui", fontSize: 12, fontWeight: 600, color: "#2383e2" },
            condition: "data.role && " + FULL,
          }),
          b("shape", {
            name: "Top rule",
            x: 40,
            y: 168,
            w: 640,
            h: 3,
            content: { shape: "rect" },
            style: { background: "#2383e2", borderRadius: 2 },
            condition: FULL,
          }),

          /* ── Merge fields & filters ── */
          b("text", {
            name: "Heading merge",
            x: 40,
            y: 176,
            w: 300,
            h: 16,
            content: { text: "MERGE FIELDS & FILTERS" },
            style: {
              fontFamily: "ui", fontSize: 10, fontWeight: 700,
              textTransform: "uppercase", letterSpacing: 1.6, color: "#2383e2",
            },
            condition: FULL,
          }),
          {
            ...b("paragraph", {
              name: "Greeting EN",
              x: 40,
              y: 198,
              w: 640,
              h: 60,
              content: {
                text: "Hello {{name|upper}}, welcome to {{company|default:texLooper}}. This starter project demonstrates merge fields, conditional rendering, and every building block the editor offers. Bind data in the Data tab and watch this page update in real time.",
              },
              style: { fontSize: 12, lineHeight: 1.55, color: "#1c2430" },
              condition: `${FULL} && ${EN}`,
            }),
            id: blockA,
          },
          b("paragraph", {
            name: "Greeting FR",
            x: 40,
            y: 198,
            w: 640,
            h: 60,
            content: {
              text: "Bonjour {{name|upper}}, bienvenue chez {{company|default:texLooper}}. Ce projet de démarrage montre les champs de fusion, le rendu conditionnel et chaque bloc de l'éditeur. Liez les données dans l'onglet Data et regardez la page se mettre à jour.",
            },
            style: { fontSize: 12, lineHeight: 1.55, color: "#1c2430" },
            condition: `${FULL} && ${FR}`,
          }),
          b("paragraph", {
            name: "Greeting NL",
            x: 40,
            y: 198,
            w: 640,
            h: 60,
            content: {
              text: "Hallo {{name|upper}}, welkom bij {{company|default:texLooper}}. Dit startproject toont samenvoegvelden, conditionele weergave en elk bouwblok van de editor. Koppel data in het Data-tabblad en zie de pagina live bijwerken.",
            },
            style: { fontSize: 12, lineHeight: 1.55, color: "#1c2430" },
            condition: `${FULL} && ${NL}`,
          }),
          b("paragraph", {
            name: "Body",
            x: 40,
            y: 264,
            w: 640,
            h: 56,
            content: {
              text: "Every field here is live. Replace the sample data with your own rows — CSV or JSON — and the preview adapts instantly. The |upper filter capitalises names; |default supplies fallback text when a field is empty.",
            },
            style: { fontSize: 12, lineHeight: 1.55, color: "#1c2430" },
            condition: FULL,
          }),
          b("text", {
            name: "Device line",
            x: 40,
            y: 326,
            w: 640,
            h: 30,
            content: { text: "Output: {{output.kind}} · Device: {{device.media}} · DPI: {{device.dpi}}" },
            style: { fontFamily: "mono", fontSize: 10, color: "#5c6570" },
            condition: FULL,
          }),

          /* ── Typography ── */
          b("text", {
            name: "Heading typo",
            x: 40,
            y: 368,
            w: 300,
            h: 16,
            content: { text: "TYPOGRAPHY" },
            style: {
              fontFamily: "ui", fontSize: 10, fontWeight: 700,
              textTransform: "uppercase", letterSpacing: 1.6, color: "#2383e2",
            },
            condition: FULL,
          }),
          b("text", {
            name: "Italic",
            x: 40,
            y: 390,
            w: 640,
            h: 26,
            content: { text: "This text is italic — fontStyle: italic adds emphasis without changing weight." },
            style: { fontSize: 12, fontStyle: "italic", color: "#3d4a5c" },
            condition: FULL,
          }),
          b("text", {
            name: "Underline",
            x: 40,
            y: 422,
            w: 640,
            h: 24,
            content: { text: "Underlined text for emphasis and inline links." },
            style: { fontSize: 12, textDecoration: "underline", color: "#2383e2" },
            condition: FULL,
          }),
          b("text", {
            name: "Letter-spacing",
            x: 40,
            y: 452,
            w: 640,
            h: 24,
            content: { text: "LETTERS WITH EXTRA SPACING — letterSpacing: 3px" },
            style: { fontSize: 12, fontWeight: 700, letterSpacing: 3, color: "#1c2430" },
            condition: FULL,
          }),
          b("text", {
            name: "Text-transform",
            x: 40,
            y: 482,
            w: 640,
            h: 24,
            content: { text: "text-transform: uppercase applied to this block" },
            style: { fontSize: 12, textTransform: "uppercase", letterSpacing: 1.2, color: "#5c6570" },
            condition: FULL,
          }),
          b("text", {
            name: "Mono font",
            x: 40,
            y: 512,
            w: 640,
            h: 28,
            content: { text: "Monospaced font (fontFamily: mono): const x = 42;" },
            style: { fontFamily: "mono", fontSize: 12, color: "#3d4a5c" },
            condition: FULL,
          }),

          /* ── Lists & tables ── */
          b("text", {
            name: "Heading lists",
            x: 40,
            y: 552,
            w: 300,
            h: 16,
            content: { text: "LISTS & TABLES" },
            style: {
              fontFamily: "ui", fontSize: 10, fontWeight: 700,
              textTransform: "uppercase", letterSpacing: 1.6, color: "#2383e2",
            },
            condition: FULL,
          }),
          b("list", {
            name: "Disc list",
            x: 40,
            y: 574,
            w: 280,
            h: 120,
            content: {
              items: [
                "Disc marker (default)",
                "Supports arbitrary depth",
                "Marker colour is configurable",
                "Line height adjusts spacing",
                "Font size is fully flexible",
                "List style: disc",
              ],
              markerColor: "#2383e2",
            },
            style: { fontSize: 11.5, lineHeight: 1.45, color: "#1c2430", listStyle: "disc" },
            condition: FULL,
          }),
          b("list", {
            name: "Decimal list",
            x: 340,
            y: 574,
            w: 160,
            h: 88,
            content: {
              items: ["First step", "Second step", "Third step", "Fourth step"],
              markerColor: "#2383e2",
            },
            style: { fontSize: 11.5, lineHeight: 1.45, color: "#1c2430", listStyle: "decimal" },
            condition: FULL,
          }),
          b("table", {
            name: "Mini table",
            x: 520,
            y: 574,
            w: 160,
            h: 108,
            content: {
              rows: 5,
              cols: 2,
              cells: [
                ["Feature", "Status"],
                ["Merge fields", "✓"],
                ["Conditions", "✓"],
                ["Filters", "✓"],
                ["Page numbers", "✓"],
              ],
            },
            style: { fontSize: 10, color: "#1c2430" },
            condition: FULL,
          }),

          /* ── Building blocks ── */
          b("text", {
            name: "Heading blocks",
            x: 40,
            y: 706,
            w: 300,
            h: 16,
            content: { text: "BUILDING BLOCKS" },
            style: {
              fontFamily: "ui", fontSize: 10, fontWeight: 700,
              textTransform: "uppercase", letterSpacing: 1.6, color: "#2383e2",
            },
            condition: FULL,
          }),
          b("shape", {
            name: "Card shape",
            x: 40,
            y: 728,
            w: 180,
            h: 80,
            content: { shape: "rect" },
            style: { background: "#e3f2fd", borderRadius: 8, borderWidth: 2, borderColor: "#2383e2" },
            condition: FULL,
          }),
          b("group", {
            name: "Feature cards",
            x: 240,
            y: 728,
            w: 440,
            h: 80,
            content: {
              blocks: [
                b("shape", {
                  name: "Card A",
                  x: 0,
                  y: 0,
                  w: 130,
                  h: 72,
                  content: { shape: "rect" },
                  style: { background: "#e8f5e9", borderRadius: 8 },
                }),
                b("shape", {
                  name: "Card B",
                  x: 140,
                  y: 0,
                  w: 130,
                  h: 72,
                  content: { shape: "rect" },
                  style: { background: "#fff3e0", borderRadius: 8 },
                }),
                b("shape", {
                  name: "Card C",
                  x: 280,
                  y: 0,
                  w: 140,
                  h: 72,
                  content: { shape: "rect" },
                  style: { background: "#fce4ec", borderRadius: 8, shadow: true },
                }),
              ],
            },
            style: {
              layout: "flex",
              direction: "row",
              justify: "start",
              alignItems: "stretch",
              gap: 12,
            },
            condition: FULL,
          }),
          b("files", {
            name: "Attachments",
            x: 40,
            y: 822,
            w: 180,
            h: 48,
            content: { label: "Attached files", count: 3 },
            condition: FULL,
          }),
          b("shape", {
            name: "Opacity demo",
            x: 240,
            y: 822,
            w: 200,
            h: 48,
            content: { shape: "rect" },
            style: { background: "#2383e2", borderRadius: 6, opacity: 0.25 },
            condition: FULL,
          }),
          b("text", {
            name: "Padding demo",
            x: 460,
            y: 822,
            w: 220,
            h: 48,
            content: { text: "Padded block\npadding: 8px" },
            style: { fontSize: 11, color: "#1c2430", padding: 8, background: "#f2f4f7", borderRadius: 6 },
            condition: FULL,
          }),
          b("shape", {
            name: "Rotate stamp",
            x: 600,
            y: 760,
            w: 88,
            h: 36,
            content: { shape: "rect" },
            style: {
              background: "#0f6b63",
              borderRadius: 4,
              rotate: -14,
              shadow: true,
            },
            condition: FULL,
            zIndex: 2,
          }),
          b("text", {
            name: "Rotate stamp label",
            x: 600,
            y: 768,
            w: 88,
            h: 20,
            content: { text: "ROTATE" },
            style: {
              fontFamily: "ui",
              fontSize: 11,
              fontWeight: 700,
              textAlign: "center",
              color: "#fff",
              letterSpacing: 1,
              rotate: -14,
            },
            condition: FULL,
            zIndex: 3,
          }),
          b("text", {
            name: "Print-only",
            x: 40,
            y: 882,
            w: 400,
            h: 20,
            content: { text: "LABEL · {{device.media}} · {{device.dpi}}dpi" },
            style: { fontSize: 10, color: "#0f6b63" },
            condition: "output.kind == 'print' && device.media == 'label'",
          }),
          b("text", {
            name: "Footer",
            x: 40,
            y: 910,
            w: 640,
            h: 18,
            content: { text: "texLooper · {{company|default:texLooper}} · Open Samples for more templates" },
            style: { fontSize: 9, color: "#5c6570", textAlign: "center" },
            condition: FULL,
            pin: { bottom: true, left: true, right: true },
          }),
        ],
        { pageNumber: { mode: "all", format: "{n}" } },
      ),
      page(
        "More features",
        [
          b("shape", {
            name: "Header bar",
            x: 0,
            y: 0,
            w: 720,
            h: 48,
            content: { shape: "rect", filled: true },
            style: { background: "#f3f7fb" },
            zIndex: 0,
            pin: { top: true, left: true, right: true },
            condition: FULL,
          }),
          b("text", {
            name: "Page 2 title",
            x: 40,
            y: 14,
            w: 400,
            h: 24,
            content: { text: "More features" },
            style: { fontFamily: "display", fontSize: 18, fontWeight: 700, color: "#1c2430" },
            condition: FULL,
            zIndex: 1,
          }),
          b("shape", {
            name: "Top rule",
            x: 40,
            y: 64,
            w: 640,
            h: 2,
            content: { variant: "line" },
            style: { borderWidth: 1, borderColor: "#d4d9e0" },
            condition: FULL,
          }),

          /* ── Page numbers ── */
          b("text", {
            name: "Heading pages",
            x: 40,
            y: 84,
            w: 300,
            h: 16,
            content: { text: "PAGE NUMBERS" },
            style: {
              fontFamily: "ui", fontSize: 10, fontWeight: 700,
              textTransform: "uppercase", letterSpacing: 1.6, color: "#2383e2",
            },
            condition: FULL,
          }),
          b("paragraph", {
            name: "Page number text",
            x: 40,
            y: 106,
            w: 640,
            h: 40,
            content: {
              text: "This page has automatic page numbering enabled. Check the bottom of each page in the preview — the number appears automatically.",
            },
            style: { fontSize: 12, lineHeight: 1.5, color: "#1c2430" },
            condition: FULL,
          }),

          /* ── Conditional content ── */
          b("text", {
            name: "Heading cond",
            x: 40,
            y: 164,
            w: 400,
            h: 16,
            content: { text: "CONDITIONAL CONTENT" },
            style: {
              fontFamily: "ui", fontSize: 10, fontWeight: 700,
              textTransform: "uppercase", letterSpacing: 1.6, color: "#2383e2",
            },
            condition: FULL,
          }),
          b("paragraph", {
            name: "Conditional text",
            x: 40,
            y: 188,
            w: 640,
            h: 64,
            content: {
              text: "{{#if role}}You are listed as {{role}} in the data. {{/if}}Conditional blocks let you show or hide content based on data values, output mode, or environment flags.",
            },
            style: { fontSize: 12, lineHeight: 1.55, color: "#1c2430" },
            condition: FULL,
          }),
          b("text", {
            name: "Print-only 2",
            x: 40,
            y: 268,
            w: 640,
            h: 28,
            content: { text: "This line only appears in print or PDF output." },
            style: { fontSize: 11, fontStyle: "italic", color: "#5c6570" },
            condition: "output.kind == 'print' || output.kind == 'pdf'",
          }),

          /* ── Data filters ── */
          b("text", {
            name: "Heading filters",
            x: 40,
            y: 312,
            w: 400,
            h: 16,
            content: { text: "DATA FILTERS" },
            style: {
              fontFamily: "ui", fontSize: 10, fontWeight: 700,
              textTransform: "uppercase", letterSpacing: 1.6, color: "#2383e2",
            },
            condition: FULL,
          }),
          b("text", {
            name: "Lower filter",
            x: 40,
            y: 340,
            w: 640,
            h: 24,
            content: { text: "|lower: {{name|lower}} · |capitalize: {{name|capitalize}} · |title: {{role|title}}" },
            style: { fontSize: 12, color: "#1c2430" },
            condition: FULL,
          }),
          b("text", {
            name: "Upper filter",
            x: 40,
            y: 368,
            w: 640,
            h: 24,
            content: { text: "|upper: {{name|upper}} · |number: {{qty|number:0}} · |currency: {{price|currency:EUR}}" },
            style: { fontSize: 12, color: "#1c2430" },
            condition: FULL,
          }),
          b("text", {
            name: "Date filters",
            x: 40,
            y: 396,
            w: 640,
            h: 24,
            content: {
              text: "|date:short {{event_date|date:short}} · |date:long {{event_date|date:long}} · today {{env.today|date:short}}",
            },
            style: { fontSize: 12, color: "#1c2430" },
            condition: FULL,
          }),

          /* ── Style gallery ── */
          b("text", {
            name: "Heading styles",
            x: 40,
            y: 448,
            w: 400,
            h: 16,
            content: { text: "STYLE GALLERY" },
            style: {
              fontFamily: "ui", fontSize: 10, fontWeight: 700,
              textTransform: "uppercase", letterSpacing: 1.6, color: "#2383e2",
            },
            condition: FULL,
          }),
          b("shape", {
            name: "Style card 1",
            x: 40,
            y: 468,
            w: 200,
            h: 90,
            content: { shape: "rect" },
            style: { background: "#2383e2", borderRadius: 8, opacity: 0.15 },
            condition: FULL,
          }),
          b("shape", {
            name: "Style card 2",
            x: 260,
            y: 468,
            w: 200,
            h: 90,
            content: { shape: "rect" },
            style: { background: "#ffffff", borderRadius: 8, borderWidth: 2, borderColor: "#2383e2" },
            condition: FULL,
          }),
          b("shape", {
            name: "Style card 3",
            x: 480,
            y: 468,
            w: 200,
            h: 90,
            content: { shape: "rect" },
            style: { background: "#f2f4f7", borderRadius: 8, shadow: true },
            condition: FULL,
          }),

          /* ── Font presets ── */
          b("text", {
            name: "Heading fonts",
            x: 40,
            y: 584,
            w: 400,
            h: 16,
            content: { text: "FONT PRESETS" },
            style: {
              fontFamily: "ui", fontSize: 10, fontWeight: 700,
              textTransform: "uppercase", letterSpacing: 1.6, color: "#2383e2",
            },
            condition: FULL,
          }),
          b("text", {
            name: "Doc font",
            x: 40,
            y: 612,
            w: 640,
            h: 24,
            content: { text: "Document font (Source Serif) — serif body text for readability." },
            style: { fontFamily: "doc", fontSize: 12, color: "#1c2430" },
            condition: FULL,
          }),
          b("text", {
            name: "UI font",
            x: 40,
            y: 648,
            w: 640,
            h: 24,
            content: { text: "Interface font (Sora) — clean sans-serif for UI chrome." },
            style: { fontFamily: "ui", fontSize: 12, color: "#1c2430" },
            condition: FULL,
          }),
          b("text", {
            name: "Mono font 2",
            x: 40,
            y: 684,
            w: 640,
            h: 24,
            content: { text: "Monospace font — code, tracking numbers, technical data." },
            style: { fontFamily: "mono", fontSize: 12, color: "#3d4a5c" },
            condition: FULL,
          }),
          b("text", {
            name: "Inter font",
            x: 40,
            y: 720,
            w: 640,
            h: 24,
            content: { text: "Display font — headlines and hero titles." },
            style: { fontFamily: "display", fontSize: 12, color: "#1c2430" },
            condition: FULL,
          }),
          b("paragraph", {
            name: "Next steps EN",
            x: 40,
            y: 768,
            w: 640,
            h: 72,
            content: {
              text: "Next: open Samples, load another template, and flip Data rows or the language chip. Every merge field updates live; SMS FR vs PDF EN show different conditions.",
            },
            style: { fontSize: 12, lineHeight: 1.55, color: "#3d4a5c" },
            condition: `${FULL} && ${EN}`,
          }),
          b("paragraph", {
            name: "Next steps FR",
            x: 40,
            y: 768,
            w: 640,
            h: 72,
            content: {
              text: "Ensuite : ouvrez Samples, chargez un autre modèle, et changez la ligne de données ou la langue. Les champs de fusion se mettent à jour ; SMS FR et PDF EN utilisent des conditions différentes.",
            },
            style: { fontSize: 12, lineHeight: 1.55, color: "#3d4a5c" },
            condition: `${FULL} && ${FR}`,
          }),
          b("paragraph", {
            name: "Next steps NL",
            x: 40,
            y: 768,
            w: 640,
            h: 72,
            content: {
              text: "Vervolg: open Samples, laad een ander sjabloon en wissel data-rijen of taal. Samenvoegvelden updaten live; SMS NL versus PDF EN tonen andere voorwaarden.",
            },
            style: { fontSize: 12, lineHeight: 1.55, color: "#3d4a5c" },
            condition: `${FULL} && ${NL}`,
          }),
          b("text", {
            name: "Footer",
            x: 40,
            y: 900,
            w: 640,
            h: 18,
            content: { text: "texLooper · page 2 · {{company|default:texLooper}}" },
            style: { fontSize: 9, color: "#5c6570", textAlign: "center" },
            condition: FULL,
            pin: { bottom: true, left: true, right: true },
          }),
        ],
        { pageNumber: { mode: "all", format: "{n}" } },
      ),
    ],
    {
      comments: [
        {
          id: createId(),
          blockId: blockA,
          body: "Open Samples for full letter, contract, invoice, email, and more.",
          author: "Guide",
          createdAt: new Date().toISOString(),
        },
      ],
      outputs: [...defaultOutputs(), ...channelOutputs],
      ...northlineStyleExtras("en"),
    },
  );
}

function sectionHeading(text: string, x: number, y: number, w: number) {
  return b("text", {
    name: `Heading ${text}`,
    x,
    y,
    w,
    h: 20,
    content: { text },
    style: {
      fontFamily: "ui",
      fontSize: 11,
      fontWeight: 700,
      textTransform: "uppercase",
      letterSpacing: 1.6,
      color: ACCENT,
    },
  });
}

function jobEntry(
  y: number,
  f: { period: string; title: string; company: string; p1: string; p2: string; p3: string },
) {
  return [
    b("text", {
      name: `Job period ${f.period}`,
      x: 56,
      y,
      w: 96,
      h: 20,
      content: { text: f.period },
      style: {
        fontFamily: "ui",
        fontSize: 10,
        fontWeight: 600,
        color: MUTED,
        verticalAlign: "middle",
      },
    }),
    b("text", {
      name: `Job role ${f.title}`,
      x: 164,
      y,
      w: 292,
      h: 20,
      content: { text: f.title },
      style: {
        fontFamily: "ui",
        fontSize: 12.5,
        fontWeight: 700,
        color: INK,
        verticalAlign: "middle",
      },
    }),
    b("list", {
      name: `Job bullets ${f.company}`,
      x: 164,
      y: y + 26,
      w: 292,
      h: 108,
      content: {
        items: [f.p1, f.p2, f.p3],
        markerColor: ACCENT,
      },
      style: {
        fontSize: 11.5,
        lineHeight: 1.35,
        color: INK,
        listStyle: "disc",
      },
    }),
  ];
}

export function resume(): Project {
  return shell(
    {
      name: "Resume — merge-field template",
      author: "texLooper samples",
      subject: "CV + cover letter driven by Data rows",
      description:
        "Two-page resume with every field bound to data, plus a matching cover letter page. Load the ten sample profiles in Data and flip the preview row to render each candidate.",
    },
    [
      page("Resume", [
        // ---- Header ----
        b("picture", {
          name: "Portrait",
          x: 560,
          y: 44,
          w: 104,
          h: 104,
          content: { src: "", alt: "Portrait", fit: "cover" },
          style: { borderRadius: 52, borderWidth: 2, borderColor: ACCENT },
        }),
        b("text", {
          name: "Candidate name",
          x: 56,
          y: 48,
          w: 480,
          h: 56,
          content: { text: "{{full_name}}" },
          style: {
            fontFamily: "display",
            fontSize: 34,
            fontWeight: 700,
            color: INK,
          },
        }),
        b("text", {
          name: "Role line",
          x: 56,
          y: 104,
          w: 480,
          h: 22,
          content: { text: "{{role}}" },
          style: {
            fontFamily: "ui",
            fontSize: 13,
            fontWeight: 600,
            textTransform: "uppercase",
            letterSpacing: 2.4,
            color: ACCENT,
            verticalAlign: "middle",
          },
        }),
        b("text", {
          name: "Contact block",
          x: 56,
          y: 130,
          w: 400,
          h: 40,
          content: {
            text: "{{email}} · {{phone}}\n{{location}} · {{website}}",
          },
          style: {
            fontFamily: "ui",
            fontSize: 10.5,
            lineHeight: 1.5,
            color: MUTED,
          },
        }),
        b("shape", {
          name: "Top rule",
          x: 56,
          y: 172,
          w: 608,
          h: 3,
          content: { variant: "rect" },
          style: { background: ACCENT, borderRadius: 2 },
        }),

        // ---- Main column ----
        sectionHeading("Profile", 56, 192, 200),
        b("paragraph", {
          name: "Summary",
          x: 56,
          y: 214,
          w: 400,
          h: 84,
          content: { text: "{{summary}}" },
          style: { fontSize: 11.5, lineHeight: 1.55, color: INK },
        }),
        sectionHeading("Experience", 56, 318, 200),
        ...jobEntry(342, {
          period: "{{j1_period}}",
          title: "{{j1_title}} — {{j1_company}}",
          company: "j1",
          p1: "{{j1_p1}}",
          p2: "{{j1_p2}}",
          p3: "{{j1_p3}}",
        }),
        ...jobEntry(478, {
          period: "{{j2_period}}",
          title: "{{j2_title}} — {{j2_company}}",
          company: "j2",
          p1: "{{j2_p1}}",
          p2: "{{j2_p2}}",
          p3: "{{j2_p3}}",
        }),
        ...jobEntry(614, {
          period: "{{j3_period}}",
          title: "{{j3_title}} — {{j3_company}}",
          company: "j3",
          p1: "{{j3_p1}}",
          p2: "{{j3_p2}}",
          p3: "{{j3_p3}}",
        }),

        // ---- Sidebar ----
        b("shape", {
          name: "Aside wash",
          x: 488,
          y: 212,
          w: 176,
          h: 556,
          content: { variant: "rect" },
          style: {
            background: "#f3f6fa",
            borderRadius: 8,
            shadow: true,
          },
        }),
        sectionHeading("Skills", 500, 228, 152),
        b("list", {
          name: "Skills list",
          x: 502,
          y: 252,
          w: 150,
          h: 150,
          content: {
            items: [
              "{{skill1}}",
              "{{skill2}}",
              "{{skill3}}",
              "{{skill4}}",
              "{{skill5}}",
              "{{skill6}}",
            ],
            markerColor: ACCENT,
          },
          style: {
            fontSize: 11,
            lineHeight: 1.45,
            color: INK,
            listStyle: "square",
          },
        }),
        sectionHeading("Education", 500, 430, 152),
        b("text", {
          name: "Education entries",
          x: 500,
          y: 454,
          w: 152,
          h: 120,
          content: {
            text: "{{edu1_degree}}\n{{edu1_school}}, {{edu1_years}}\n\n{{edu2_degree}}\n{{edu2_school}}, {{edu2_years}}",
          },
          style: { fontSize: 10.5, lineHeight: 1.45, color: INK },
        }),
        sectionHeading("Languages", 500, 600, 152),
        b("text", {
          name: "Languages line",
          x: 500,
          y: 624,
          w: 152,
          h: 70,
          content: { text: "{{languages}}" },
          style: { fontSize: 10.5, lineHeight: 1.5, color: INK },
        }),

        // ---- Footer ----
        b("shape", {
          name: "Bottom rule",
          x: 56,
          y: 792,
          w: 608,
          h: 1,
          content: { variant: "line" },
          style: { borderWidth: 1, borderColor: "#d4d9e0" },
        }),
        b("text", {
          name: "Footer",
          x: 56,
          y: 900,
          w: 608,
          h: 18,
          content: {
            text: "References available on request · {{website}}",
          },
          style: {
            fontFamily: "ui",
            fontSize: 9.5,
            letterSpacing: 0.4,
            color: MUTED,
            textAlign: "center",
          },
          pin: { bottom: true, left: true, right: true },
        }),
      ]),
      page("Cover letter", [
        b("shape", {
          name: "Letterhead",
          x: 0,
          y: 0,
          w: 720,
          h: 48,
          content: { shape: "rect", filled: true },
          style: { background: "#f7f9fc" },
          zIndex: 0,
          pin: { top: true, left: true, right: true },
        }),
        b("text", {
          name: "CL sender",
          x: 56,
          y: 64,
          w: 400,
          h: 56,
          content: {
            text: "{{full_name}}\n{{email}} · {{phone}}\n{{location}}",
          },
          style: { fontFamily: "ui", fontSize: 10.5, lineHeight: 1.5, color: MUTED },
        }),
        b("picture", {
          name: "CL portrait",
          x: 560,
          y: 60,
          w: 104,
          h: 104,
          content: { src: "", alt: "Portrait", fit: "cover" },
          style: { borderRadius: 52, borderWidth: 2, borderColor: ACCENT },
        }),
        b("shape", {
          name: "Top rule",
          x: 56,
          y: 140,
          w: 608,
          h: 3,
          content: { variant: "rect" },
          style: { background: ACCENT, borderRadius: 2 },
        }),
        b("text", {
          name: "CL subject",
          x: 56,
          y: 164,
          w: 460,
          h: 20,
          content: { text: "Application: {{role}}" },
          style: {
            fontFamily: "ui",
            fontSize: 11,
            fontWeight: 700,
            textTransform: "uppercase",
            letterSpacing: 1.6,
            color: ACCENT,
          },
        }),
        b("text", {
          name: "CL recipient",
          x: 56,
          y: 196,
          w: 420,
          h: 44,
          content: {
            text: "Hiring Team\n[Company name]\n[Office address]",
          },
          style: { fontFamily: "ui", fontSize: 11, lineHeight: 1.45, color: INK },
        }),
        b("text", {
          name: "CL salutation",
          x: 56,
          y: 260,
          w: 608,
          h: 22,
          content: { text: "Dear Hiring Team," },
          style: { fontFamily: "ui", fontSize: 12, color: INK },
        }),
        b("paragraph", {
          name: "CL opening",
          x: 56,
          y: 296,
          w: 608,
          h: 120,
          content: {
            text: "I am applying for the {{role}} position. {{summary}} The short version: I like owning outcomes end to end, and I measure my work by the numbers it moves.\n\nI am writing because your team’s problems match the work I do best — clear systems, honest metrics, and delivery that compounds.",
          },
          style: { fontFamily: "ui", fontSize: 11.5, lineHeight: 1.6, color: INK },
        }),
        b("paragraph", {
          name: "CL proof",
          x: 56,
          y: 436,
          w: 608,
          h: 140,
          content: {
            text: "Most recently at {{j1_company}}, {{j1_p1|lower}} — and before that, {{j2_p1|lower}}. Earlier in my career at {{j3_company}} I learned to ship small, measure honestly, and write things down so the next person moves faster.\n\nThose habits travel: I still keep a weekly review of what shipped, what slipped, and what I would change next time.",
          },
          style: { fontFamily: "ui", fontSize: 11.5, lineHeight: 1.6, color: INK },
        }),
        b("paragraph", {
          name: "CL fit",
          x: 56,
          y: 596,
          w: 608,
          h: 110,
          content: {
            text: "What draws me to your team is the chance to bring {{skill1}}, {{skill2}} and {{skill3}} to problems that matter, alongside people who care about craft. My toolkit also covers {{skill4}} and {{skill5}}, picked up while delivering {{edu1_degree}}-level coursework and everything since.",
          },
          style: { fontFamily: "ui", fontSize: 11.5, lineHeight: 1.6, color: INK },
        }),
        b("paragraph", {
          name: "CL closing",
          x: 56,
          y: 724,
          w: 608,
          h: 72,
          content: {
            text: "My full CV is on page one; references are available on request. Thank you for your time and consideration — I would welcome a conversation about where I can help your team most.",
          },
          style: { fontFamily: "ui", fontSize: 11.5, lineHeight: 1.6, color: INK },
        }),
        b("text", {
          name: "CL sign-off",
          x: 56,
          y: 812,
          w: 608,
          h: 48,
          content: {
            text: "Kind regards,\n{{full_name}}\n{{website}}",
          },
          style: { fontFamily: "ui", fontSize: 11.5, lineHeight: 1.5, color: INK },
        }),
        b("text", {
          name: "Footer",
          x: 56,
          y: 900,
          w: 608,
          h: 18,
          content: { text: "{{full_name}} · {{role}} · Confidential" },
          style: { fontFamily: "ui", fontSize: 9, color: MUTED, textAlign: "center" },
          pin: { bottom: true, left: true, right: true },
        }),
      ]),
    ],
  );
}

export const RESUME_PROFILES_CSV = `full_name,role,email,phone,location,website,summary,j1_period,j1_title,j1_company,j1_p1,j1_p2,j1_p3,j2_period,j2_title,j2_company,j2_p1,j2_p2,j2_p3,j3_period,j3_title,j3_company,j3_p1,j3_p2,j3_p3,skill1,skill2,skill3,skill4,skill5,skill6,edu1_degree,edu1_school,edu1_years,edu2_degree,edu2_school,edu2_years,languages
Jonas Weber,DevOps Engineer,jonas.weber@example.com,+49 151 2345 678,"Berlin, Germany",jonasweber.dev,"Platform engineer focused on Kubernetes, observability and developer joy. Cut deploy times from hours to minutes for teams of 100+.",2022 — Now,Staff Platform Engineer,Wolke Systems,"Designed multi-region K8s platform at 99.95% SLA","Reduced mean deploy time from 45 to 6 minutes","Introduced OpenTelemetry tracing org-wide",2019 — 2022,DevOps Engineer,Funkhaus Media,"Terraformed full AWS estate as code","Built self-service preview environments per PR","Handled migration of 40 services to EKS",2016 — 2019,System Administrator,Bergwerk IT,"Automated patching for 300+ servers with Ansible","Consolidated monitoring onto Prometheus stack","Wrote runbooks adopted as company standard",Kubernetes,Terraform,AWS,Observability,Go,CI/CD design,BSc Information Systems, TU Munich,2016,Ausbildung IT Specialist,Berufsschule München,2013,"German — native · English — fluent"
Marcus Chen,Data Scientist,marcus.chen@example.com,+31 6 2345 6789,"Amsterdam, Netherlands",marcuschen.io,"Data scientist specialising in forecasting and experimentation. Turns messy pipelines into decision-grade models and clear stakeholder narratives.",2022 — Now,Lead Data Scientist,Delta Logistics,"Owns demand-forecast platform steering €120M inventory","Cut forecast error 28% with gradient-boosted ensembles","Built churn early-warning saving €1.8M annually",2019 — 2022,Data Scientist,Kanaal Bank,"Deployed credit-risk models under ECB review","Automated feature store cutting release cycle 3x","Published internal uplift-modelling toolkit",2017 — 2019,Analytics Consultant,Bright Data Co,"Delivered 15 dashboard projects for retail clients","Migrated reporting estate from Excel to dbt","Trained client teams on SQL and experiment design",Python,dbt,Airflow,SQL,Forecasting,Experimentation,MSc Statistics,Delft University of Technology,2017,BSc Mathematics,Utrecht University,2015,"English — fluent · Dutch — fluent · Mandarin — native"
Amara Okafor,Product Manager,amara.okafor@example.com,+44 7700 900 123,"London, UK",amaraokafor.com,"Product manager bridging research, design and engineering for B2B SaaS. Launched three zero-to-one products and scaled pricing to £8M ARR.",2023 — Now,Principal Product Manager,Fleetwise,"Owns telematics platform roadmap across 3 squads","Launched usage-based pricing growing ARR 22%","Ran discovery programme interviewing 60 fleet operators",2020 — 2023,Senior Product Manager,Dispatchly,"Shipped driver mobile app rated 4.8 on stores","Introduced OKR cadence adopted company-wide","Reduced onboarding drop-off 35% via redesign",2017 — 2020,Associate Product Manager,MarketMuse,"Grew activation 18% through lifecycle emails","Managed integrations partnership roadmap","Founded internal product-guild community",Product strategy,Discovery,Roadmapping,SQL,Analytics,Pricing,MSc Management,London Business School,2017,BSc Economics,University of Lagos,2014,"English — native · Igbo — native · French — A2"
Sofia Reyes,UX Designer,sofia.reyes@example.com,+34 612 345 678,"Barcelona, Spain",sofiareyes.design,"Product designer crafting calm, research-led interfaces for fintech and health. Runs continuous discovery and designs in systems, not screens.",2021 — Now,Lead Product Designer,Clara Health,"Redesigned patient portal raising task success 41%","Built token-based design system across web and app","Coached squad designers on accessibility practice",2018 — 2021,Product Designer,Pago Fintech,"Simplified KYC flow cutting abandonment 26%","Ran quarterly benchmark usability programmes","Prototyped award-winning onboarding in Figma",2016 — 2018,Visual Designer,Estudio Norte,"Delivered brand systems for 12 startups","Introduced motion guidelines to the studio","Supported sales with interactive demos",Figma,Design systems,User research,Prototyping,Accessibility,Interaction design,BA Interaction Design,ELISAVA Barcelona,2016,Foundation Art & Design,Escola Eina,2013,"Spanish — native · Catalan — native · English — C1"
Tomás Ferreira,Backend Engineer,tomas.ferreira@example.com,+351 912 345 678,"Porto, Portugal",tomasferreira.dev,"Backend engineer focused on payment rails and event-driven systems. Keeps ledgers correct under load and writes the runbooks nobody dreads.",2020 — Now,Senior Backend Engineer,Miro Pay,"Owns ledger service clearing €40M monthly with zero reconciliation drift","Cut p99 transfer latency from 900 to 120 ms via write batching","Led PCI-DSS scope reduction saving €180k in audit effort",2017 — 2020,Backend Engineer,Ticketline PT,"Rebuilt queueing for flash sales sustaining 60k checkouts/minute","Introduced outbox pattern eliminating duplicate emails","Migrated monolith billing module to Go services",2015 — 2017,Junior Developer,Sapo Labs,"Shipped notification pipeline for carrier partners","Automated contract testing across 12 integrations",PostgreSQL,Banking domain,Kafka,Go,Event sourcing,Observability,BSc Computer Engineering,University of Porto,2015,Postgraduate Distributed Systems,Instituto Superior Técnico,2017,"Portuguese — native · English — fluent · Spanish — B2"
Hana Suzuki,Mobile Engineer,hana.suzuki@example.com,+31 6 8765 4321,"Amsterdam, Netherlands",hanasuzuki.app,"Mobile engineer shipping native-feeling apps on tight budgets. Cares about cold-start time, offline behaviour and review scores above 4.6.",2022 — Now,Senior iOS Engineer,Fietsfinder,"Rewrote navigation stack cutting cold start to 800 ms","Shipped offline maps used by 200k riders monthly","Reduced crash-free sessions gap between platforms to 0.3%",2019 — 2022,Mobile Engineer,Stadsapp BV,"Launched parking app adopted by three municipalities","Built OTA feature flags removing release bottlenecks","Introduced Swift Concurrency patterns team-wide",2017 — 2019,Junior Android Developer,Tulip Media,"Delivered news app widgets with 30% DAU lift","Owned Play Store release pipeline automation",Swift,Kotlin,Offline sync,CI/CD,Performance,Accessibility,BSc Interaction Technology,Utrecht University of Applied Sciences,2017,iOS Specialisation Stanford Online,2019,"Japanese — native · English — fluent · Dutch — B1"
Liam O'Connor,Site Reliability Engineer,liam.oconnor.example@gmail.com,+353 87 123 4567,"Dublin, Ireland",liamoconnor.ie,"SRE who treats reliability as a product feature. Blames systems, not people; automates toil until the pager goes quiet.",2021 — Now,Staff SRE,Cloudharbor,"Error budgets now gate releases across 40 services","Cut MTTR 55% by rebuilding incident command process","Designed multi-region failover surviving annual game-day drills",2018 — 2021,SRE,Riverdock Hosting,"Terraformed bare-metal fleet of 600 hosts","Built SLO tooling adopted by five product teams","Eliminated 70% of manual capacity planning",2016 — 2018,Systems Administrator,Eircom Cloud,"Automated DNS and certificate rotation org-wide","Wrote first incident-response playbook",Kubernetes,SLO design,Terraform,Incident response,Go,Grafana,BSc Computer Science,Trinity College Dublin,2016,Certificate Enterprise Architecture,IMI Dublin,2019,"English — native · Irish — fluent"
Fatima Zahra El Amrani,Growth Analyst,fatima.elamrani@example.com,+32 471 987 654,"Brussels, Belgium",fatimazehra.be,"Growth analyst pairing rigorous experimentation with honest storytelling. Turns funnel noise into a prioritised backlog leadership actually trusts.",2022 — Now,Senior Growth Analyst,Lumen Learning,"Grew activation 24% through onboarding experiment programme","Built self-serve metrics layer replacing weekly ad-hoc reports","Ran pricing research informing tier redesign at €6M scale",2020 — 2022,Growth Analyst,Velodrop,"Scaled referral loop contributing 18% of signups","Introduced Bayesian A/B evaluation replacing peak peeking","Automated LTV reporting across six markets",2018 — 2020,Marketing Data Intern,Shoply,"Dashboarded campaign ROI for 20+ channels","Cleaned tracking taxonomy cutting attribution disputes","SQL,dbt,Experimentation,Amplitude,Python,Data storytelling,BSc Business Analytics,Solvay Brussels School,2018,MSc Marketing Intelligence,VU Amsterdam,2020,"Arabic — native · French — fluent · Dutch — fluent · English — fluent"
Viktor Lindgren,Security Engineer,viktor.lindgren@example.com,+46 70 123 45 67,"Stockholm, Sweden",viktorlindgren.se,"Security engineer embedding secure defaults into developer workflows. Ships paved roads, not gates; measures security work by tickets developers no longer file.",2021 — Now,Senior Security Engineer,Nordbank IT,"Led supply-chain hardening after industry-wide xz-style scare","Cut critical findings per audit from 14 to 2 across two years","Built internal threat-modelling guild training 80 engineers",2019 — 2021,Application Security Engineer,Fastighetspay,"Secured open-banking flows ahead of PSD2 deadline","Introduced dependency scanning blocking 100% of known CVEs","Wrote secure-coding curriculum for onboarding squads",2017 — 2019,Security Consultant,Härd Security,"Ran pentests for 25 fintech and retail clients","Disclosed three CVEs in widely-used Nordic banking SDKs",Threat modelling,AppSec,CI/CD hardening,Cryptography basics,Python,Public speaking,MSc Information Security,KTH Royal Institute of Technology,2017,OSCP,Offensive Security,2019,"Swedish — native · English — fluent"`;

