import type { Project } from "../../document";
import { createId } from "../../document";
import {
  defaultOutputs,
  optionalOutputTemplates,
} from "../../workflow";
import { DEMO_IMG } from "../assets";
import { b, page, shell } from "../helpers";
import { northlineStyleExtras } from "../brand/northlineStyles";
import {
  mergeSkillChipSlot,
  paletteAccentRule,
  paletteSectionHeading,
  paletteVariants,
  resumePalette,
  resumePaletteCondition,
} from "./resumeShared";

export { RESUME_PROFILES_CSV, RESUME_ENGINEERING_SAMPLE } from "./resumeData";

const ACCENT = "#0f6b63";
const INK = "#1c2430";
const MUTED = "#5c6570";

export function welcome(): Project {
  const blockA = createId();
  const FULL =
    "output.kind != 'sms' && output.kind != 'email' && output.kind != 'mobile'";
  const EN = "vars.language == 'en'";
  const FR = "vars.language == 'fr'";
  const NL = "vars.language == 'nl'";
  const SMS = "output.kind == 'sms'";
  const EMAIL = "output.kind == 'email'";
  const channelOutputs = optionalOutputTemplates().filter(
    (o) => o.kind === "sms" || o.kind === "print",
  );
  return shell(
    {
      name: "Welcome to texLooper",
      author: "You",
      subject: "Quickstart sample — {{name|default:friend}}",
      description:
        "Multi-language (EN/FR/NL) × multi-output (Screen/PDF/Email/SMS/Print) showcase. Switch Preview row language and output kind for channel-specific layouts. Also demos merge fields, filters, typography, lists, tables, shapes, and groups.",
    },
    [
      page(
        "Features",
        [
          /* ── SMS × language ── */
          b("text", {
            name: "SMS greeting EN",
            x: 40,
            y: 860,
            w: 640,
            h: 36,
            content: { text: "Hi {{name|default:there}}, welcome to texLooper!" },
            style: { fontFamily: "ui", fontSize: 14, fontWeight: 600, color: "#1c2430" },
            condition: `${SMS} && ${EN}`,
          }),
          b("text", {
            name: "SMS greeting FR",
            x: 40,
            y: 860,
            w: 640,
            h: 36,
            content: { text: "Bonjour {{name|default:là}}, bienvenue sur texLooper !" },
            style: { fontFamily: "ui", fontSize: 14, fontWeight: 600, color: "#1c2430" },
            condition: `${SMS} && ${FR}`,
          }),
          b("text", {
            name: "SMS greeting NL",
            x: 40,
            y: 860,
            w: 640,
            h: 36,
            content: { text: "Hoi {{name|default:daar}}, welkom bij texLooper!" },
            style: { fontFamily: "ui", fontSize: 14, fontWeight: 600, color: "#1c2430" },
            condition: `${SMS} && ${NL}`,
          }),
          b("text", {
            name: "SMS body EN",
            x: 40,
            y: 902,
            w: 640,
            h: 36,
            content: { text: "This is the SMS version — short, plain text only. Reply STOP to {{opt_out_code}}." },
            style: { fontFamily: "ui", fontSize: 12, color: "#1c2430" },
            condition: `${SMS} && ${EN}`,
          }),
          b("text", {
            name: "SMS body FR",
            x: 40,
            y: 902,
            w: 640,
            h: 36,
            content: { text: "Version SMS — texte court uniquement. Passez en Aperçu ou PDF pour le document complet." },
            style: { fontFamily: "ui", fontSize: 12, color: "#1c2430" },
            condition: `${SMS} && ${FR}`,
          }),
          b("text", {
            name: "SMS body NL",
            x: 40,
            y: 902,
            w: 640,
            h: 36,
            content: { text: "Dit is de SMS-versie — kort en zonder opmaak. Kies Preview of PDF voor het volledige document." },
            style: { fontFamily: "ui", fontSize: 12, color: "#1c2430" },
            condition: `${SMS} && ${NL}`,
          }),
          b("text", {
            name: "SMS closing EN",
            x: 40,
            y: 944,
            w: 640,
            h: 16,
            content: { text: "texlooper.app" },
            style: { fontFamily: "mono", fontSize: 9, color: "#5c6570" },
            condition: `${SMS} && ${EN}`,
          }),
          b("text", {
            name: "SMS closing FR",
            x: 40,
            y: 944,
            w: 640,
            h: 16,
            content: { text: "texlooper.app · FR" },
            style: { fontFamily: "mono", fontSize: 9, color: "#5c6570" },
            condition: `${SMS} && ${FR}`,
          }),
          b("text", {
            name: "SMS closing NL",
            x: 40,
            y: 944,
            w: 640,
            h: 16,
            content: { text: "texlooper.app · NL" },
            style: { fontFamily: "mono", fontSize: 9, color: "#5c6570" },
            condition: `${SMS} && ${NL}`,
          }),

          /* ── Email-only message (fair HTML preview) ── */
          b("text", {
            name: "Email brand",
            x: 40,
            y: 40,
            w: 520,
            h: 24,
            content: { text: "texLooper" },
            style: {
              fontFamily: "ui",
              fontSize: 13,
              fontWeight: 700,
              color: ACCENT,
              letterSpacing: 0.4,
            },
            condition: EMAIL,
          }),
          b("text", {
            name: "Email title EN",
            x: 40,
            y: 80,
            w: 520,
            h: 40,
            content: { text: "Hello {{name|upper|default:THERE}}" },
            style: {
              fontFamily: "display",
              fontSize: 26,
              fontWeight: 700,
              color: INK,
            },
            condition: `${EMAIL} && ${EN}`,
          }),
          b("text", {
            name: "Email title FR",
            x: 40,
            y: 80,
            w: 520,
            h: 40,
            content: { text: "Bonjour {{name|upper|default:LÀ}}" },
            style: {
              fontFamily: "display",
              fontSize: 26,
              fontWeight: 700,
              color: INK,
            },
            condition: `${EMAIL} && ${FR}`,
          }),
          b("text", {
            name: "Email title NL",
            x: 40,
            y: 80,
            w: 520,
            h: 40,
            content: { text: "Hoi {{name|upper|default:DAAR}}" },
            style: {
              fontFamily: "display",
              fontSize: 26,
              fontWeight: 700,
              color: INK,
            },
            condition: `${EMAIL} && ${NL}`,
          }),
          b("text", {
            name: "Email role",
            x: 40,
            y: 128,
            w: 520,
            h: 22,
            content: { text: "Role: {{role}}" },
            style: { fontFamily: "ui", fontSize: 13, color: MUTED },
            condition: EMAIL,
          }),
          b("paragraph", {
            name: "Email body EN",
            x: 40,
            y: 164,
            w: 520,
            h: 90,
            content: {
              text: "This is the email channel — a stacked HTML message, not the page canvas. Merged values resolve from the row; empty fields stay visible as {{tokens}} so you can spot gaps before send.\n\nCompany: {{company|default:texLooper}}\nNote: {{optional_note}}",
            },
            style: { fontSize: 13, lineHeight: 1.55, color: INK },
            condition: `${EMAIL} && ${EN}`,
          }),
          b("paragraph", {
            name: "Email body FR",
            x: 40,
            y: 164,
            w: 520,
            h: 90,
            content: {
              text: "Canal e-mail — message HTML empilé, pas le canevas page. Les champs fusionnés viennent de la ligne ; les vides restent visibles en {{jetons}}.\n\nSociété : {{company|default:texLooper}}\nNote : {{optional_note}}",
            },
            style: { fontSize: 13, lineHeight: 1.55, color: INK },
            condition: `${EMAIL} && ${FR}`,
          }),
          b("paragraph", {
            name: "Email body NL",
            x: 40,
            y: 164,
            w: 520,
            h: 90,
            content: {
              text: "E-mailkanaal — gestapelde HTML, niet het paginacanvas. Ontbrekende velden blijven zichtbaar als {{tokens}}.\n\nBedrijf: {{company|default:texLooper}}\nNotitie: {{optional_note}}",
            },
            style: { fontSize: 13, lineHeight: 1.55, color: INK },
            condition: `${EMAIL} && ${NL}`,
          }),
          b("link", {
            name: "Email CTA",
            x: 40,
            y: 270,
            w: 200,
            h: 36,
            content: {
              label: "Open in texLooper",
              target: "https://texlooper.app",
            },
            style: {
              fontFamily: "ui",
              fontSize: 13,
              fontWeight: 600,
              color: "#ffffff",
              background: ACCENT,
              padding: 10,
              borderRadius: 6,
              textAlign: "center",
            },
            condition: EMAIL,
          }),
          b("text", {
            name: "Email footer",
            x: 40,
            y: 330,
            w: 520,
            h: 20,
            content: { text: "You are receiving this because {{email}} is on the sample list." },
            style: { fontFamily: "ui", fontSize: 11, color: MUTED },
            condition: EMAIL,
          }),

          /* ── Full document (Screen / PDF / Print / Image) ── */
          /* ── Header ── */
          b("shape", {
            name: "Letterhead",
            x: 0,
            y: 0,
            w: 720,
            h: 72,
            content: { shape: "rect", filled: true },
            style: { background: "#f3f7fb" },
            zIndex: 0,
            pin: { top: true, left: true, right: true },
            condition: FULL,
          }),
          b("picture", {
            name: "Logo",
            x: 40,
            y: 16,
            w: 140,
            h: 40,
            content: { src: DEMO_IMG.logoMark, alt: "Northline" },
            condition: FULL,
            zIndex: 1,
          }),
          b("text", {
            name: "Sender",
            x: 200,
            y: 24,
            w: 480,
            h: 22,
            content: { text: "texLooper · Quickstart guide" },
            style: { fontFamily: "ui", fontSize: 11, color: "#5c6570", textAlign: "right" },
            condition: FULL,
            zIndex: 1,
          }),
          b("text", {
            name: "Title EN",
            x: 40,
            y: 88,
            w: 640,
            h: 48,
            content: { text: "Hello {{name|upper}}" },
            style: { fontFamily: "display", fontSize: 28, fontWeight: 700, color: "#1c2430" },
            bindings: { text: "name" },
            condition: `${FULL} && ${EN}`,
          }),
          b("text", {
            name: "Title FR",
            x: 40,
            y: 88,
            w: 640,
            h: 48,
            content: { text: "Bonjour {{name|upper}}" },
            style: { fontFamily: "display", fontSize: 28, fontWeight: 700, color: "#1c2430" },
            bindings: { text: "name" },
            condition: `${FULL} && ${FR}`,
          }),
          b("text", {
            name: "Title NL",
            x: 40,
            y: 88,
            w: 640,
            h: 48,
            content: { text: "Hallo {{name|upper}}" },
            style: { fontFamily: "display", fontSize: 28, fontWeight: 700, color: "#1c2430" },
            bindings: { text: "name" },
            condition: `${FULL} && ${NL}`,
          }),
          b("text", {
            name: "Role line",
            x: 40,
            y: 140,
            w: 300,
            h: 20,
            content: { text: "Role: {{role}}" },
            style: { fontFamily: "ui", fontSize: 12, fontWeight: 600, color: "#2383e2" },
            condition: "data.role && " + FULL,
          }),
          b("shape", {
            name: "Top rule",
            x: 40,
            y: 168,
            w: 640,
            h: 3,
            content: { shape: "rect" },
            style: { background: "#2383e2", borderRadius: 2 },
            condition: FULL,
          }),

          /* ── Merge fields & filters ── */
          b("text", {
            name: "Heading merge",
            x: 40,
            y: 176,
            w: 300,
            h: 16,
            content: { text: "MERGE FIELDS & FILTERS" },
            style: {
              fontFamily: "ui", fontSize: 10, fontWeight: 700,
              textTransform: "uppercase", letterSpacing: 1.6, color: "#2383e2",
            },
            condition: FULL,
          }),
          {
            ...b("paragraph", {
              name: "Greeting EN",
              x: 40,
              y: 198,
              w: 640,
              h: 60,
              content: {
                text: "Hello {{name|upper}}, welcome to {{company|default:texLooper}}. This starter project demonstrates merge fields, conditional rendering, and every building block the editor offers. Bind data in the Data tab and watch this page update in real time.",
              },
              style: { fontSize: 12, lineHeight: 1.55, color: "#1c2430" },
              condition: `${FULL} && ${EN}`,
            }),
            id: blockA,
          },
          b("paragraph", {
            name: "Greeting FR",
            x: 40,
            y: 198,
            w: 640,
            h: 60,
            content: {
              text: "Bonjour {{name|upper}}, bienvenue chez {{company|default:texLooper}}. Ce projet de démarrage montre les champs de fusion, le rendu conditionnel et chaque bloc de l'éditeur. Liez les données dans l'onglet Data et regardez la page se mettre à jour.",
            },
            style: { fontSize: 12, lineHeight: 1.55, color: "#1c2430" },
            condition: `${FULL} && ${FR}`,
          }),
          b("paragraph", {
            name: "Greeting NL",
            x: 40,
            y: 198,
            w: 640,
            h: 60,
            content: {
              text: "Hallo {{name|upper}}, welkom bij {{company|default:texLooper}}. Dit startproject toont samenvoegvelden, conditionele weergave en elk bouwblok van de editor. Koppel data in het Data-tabblad en zie de pagina live bijwerken.",
            },
            style: { fontSize: 12, lineHeight: 1.55, color: "#1c2430" },
            condition: `${FULL} && ${NL}`,
          }),
          b("paragraph", {
            name: "Body",
            x: 40,
            y: 264,
            w: 640,
            h: 56,
            content: {
              text: "Every field here is live. Replace the sample data with your own rows — CSV or JSON — and the preview adapts instantly. The |upper filter capitalises names; |default supplies fallback text when a field is empty.",
            },
            style: { fontSize: 12, lineHeight: 1.55, color: "#1c2430" },
            condition: FULL,
          }),
          b("text", {
            name: "Device line",
            x: 40,
            y: 326,
            w: 640,
            h: 30,
            content: { text: "Output: {{output.kind}} · Device: {{device.media}} · DPI: {{device.dpi}}" },
            style: { fontFamily: "mono", fontSize: 10, color: "#5c6570" },
            condition: FULL,
          }),

          /* ── Typography ── */
          b("text", {
            name: "Heading typo",
            x: 40,
            y: 368,
            w: 300,
            h: 16,
            content: { text: "TYPOGRAPHY" },
            style: {
              fontFamily: "ui", fontSize: 10, fontWeight: 700,
              textTransform: "uppercase", letterSpacing: 1.6, color: "#2383e2",
            },
            condition: FULL,
          }),
          b("text", {
            name: "Italic",
            x: 40,
            y: 390,
            w: 640,
            h: 26,
            content: { text: "This text is italic — fontStyle: italic adds emphasis without changing weight." },
            style: { fontSize: 12, fontStyle: "italic", color: "#3d4a5c" },
            condition: FULL,
          }),
          b("text", {
            name: "Underline",
            x: 40,
            y: 422,
            w: 640,
            h: 24,
            content: { text: "Underlined text for emphasis and inline links." },
            style: { fontSize: 12, textDecoration: "underline", color: "#2383e2" },
            condition: FULL,
          }),
          b("text", {
            name: "Letter-spacing",
            x: 40,
            y: 452,
            w: 640,
            h: 24,
            content: { text: "LETTERS WITH EXTRA SPACING — letterSpacing: 3px" },
            style: { fontSize: 12, fontWeight: 700, letterSpacing: 3, color: "#1c2430" },
            condition: FULL,
          }),
          b("text", {
            name: "Text-transform",
            x: 40,
            y: 482,
            w: 640,
            h: 24,
            content: { text: "text-transform: uppercase applied to this block" },
            style: { fontSize: 12, textTransform: "uppercase", letterSpacing: 1.2, color: "#5c6570" },
            condition: FULL,
          }),
          b("text", {
            name: "Mono font",
            x: 40,
            y: 512,
            w: 640,
            h: 28,
            content: { text: "Monospaced font (fontFamily: mono): const x = 42;" },
            style: { fontFamily: "mono", fontSize: 12, color: "#3d4a5c" },
            condition: FULL,
          }),

          /* ── Lists & tables ── */
          b("text", {
            name: "Heading lists",
            x: 40,
            y: 552,
            w: 300,
            h: 16,
            content: { text: "LISTS & TABLES" },
            style: {
              fontFamily: "ui", fontSize: 10, fontWeight: 700,
              textTransform: "uppercase", letterSpacing: 1.6, color: "#2383e2",
            },
            condition: FULL,
          }),
          b("list", {
            name: "Disc list",
            x: 40,
            y: 574,
            w: 280,
            h: 120,
            content: {
              items: [
                "Disc marker (default)",
                "Supports arbitrary depth",
                "Marker colour is configurable",
                "Line height adjusts spacing",
                "Font size is fully flexible",
                "List style: disc",
              ],
              markerColor: "#2383e2",
            },
            style: { fontSize: 11.5, lineHeight: 1.45, color: "#1c2430", listStyle: "disc" },
            condition: FULL,
          }),
          b("list", {
            name: "Decimal list",
            x: 340,
            y: 574,
            w: 160,
            h: 88,
            content: {
              items: ["First step", "Second step", "Third step", "Fourth step"],
              markerColor: "#2383e2",
            },
            style: { fontSize: 11.5, lineHeight: 1.45, color: "#1c2430", listStyle: "decimal" },
            condition: FULL,
          }),
          b("table", {
            name: "Mini table",
            x: 520,
            y: 574,
            w: 160,
            h: 108,
            content: {
              rows: 5,
              cols: 2,
              cells: [
                ["Feature", "Status"],
                ["Merge fields", "✓"],
                ["Conditions", "✓"],
                ["Filters", "✓"],
                ["Page numbers", "✓"],
              ],
            },
            style: { fontSize: 10, color: "#1c2430" },
            condition: FULL,
          }),

          /* ── Building blocks ── */
          b("text", {
            name: "Heading blocks",
            x: 40,
            y: 706,
            w: 300,
            h: 16,
            content: { text: "BUILDING BLOCKS" },
            style: {
              fontFamily: "ui", fontSize: 10, fontWeight: 700,
              textTransform: "uppercase", letterSpacing: 1.6, color: "#2383e2",
            },
            condition: FULL,
          }),
          b("shape", {
            name: "Card shape",
            x: 40,
            y: 728,
            w: 180,
            h: 80,
            content: { shape: "rect" },
            style: { background: "#e3f2fd", borderRadius: 8, borderWidth: 2, borderColor: "#2383e2" },
            condition: FULL,
          }),
          b("group", {
            name: "Feature cards",
            x: 240,
            y: 728,
            w: 440,
            h: 80,
            content: {
              blocks: [
                b("shape", {
                  name: "Card A",
                  x: 0,
                  y: 0,
                  w: 130,
                  h: 72,
                  content: { shape: "rect" },
                  style: { background: "#e8f5e9", borderRadius: 8 },
                }),
                b("shape", {
                  name: "Card B",
                  x: 140,
                  y: 0,
                  w: 130,
                  h: 72,
                  content: { shape: "rect" },
                  style: { background: "#fff3e0", borderRadius: 8 },
                }),
                b("shape", {
                  name: "Card C",
                  x: 280,
                  y: 0,
                  w: 140,
                  h: 72,
                  content: { shape: "rect" },
                  style: { background: "#fce4ec", borderRadius: 8, shadow: true },
                }),
              ],
            },
            style: {
              layout: "flex",
              direction: "row",
              justify: "start",
              alignItems: "stretch",
              gap: 12,
            },
            condition: FULL,
          }),
          b("files", {
            name: "Attachments",
            x: 40,
            y: 822,
            w: 180,
            h: 48,
            content: { label: "Attached files", count: 3 },
            condition: FULL,
          }),
          b("shape", {
            name: "Opacity demo",
            x: 240,
            y: 822,
            w: 200,
            h: 48,
            content: { shape: "rect" },
            style: { background: "#2383e2", borderRadius: 6, opacity: 0.25 },
            condition: FULL,
          }),
          b("text", {
            name: "Padding demo",
            x: 460,
            y: 822,
            w: 220,
            h: 48,
            content: { text: "Padded block\npadding: 8px" },
            style: { fontSize: 11, color: "#1c2430", padding: 8, background: "#f2f4f7", borderRadius: 6 },
            condition: FULL,
          }),
          b("shape", {
            name: "Rotate stamp",
            x: 600,
            y: 760,
            w: 88,
            h: 36,
            content: { shape: "rect" },
            style: {
              background: "#0f6b63",
              borderRadius: 4,
              rotate: -14,
              shadow: true,
            },
            condition: FULL,
            zIndex: 2,
          }),
          b("text", {
            name: "Rotate stamp label",
            x: 600,
            y: 768,
            w: 88,
            h: 20,
            content: { text: "ROTATE" },
            style: {
              fontFamily: "ui",
              fontSize: 11,
              fontWeight: 700,
              textAlign: "center",
              color: "#fff",
              letterSpacing: 1,
              rotate: -14,
            },
            condition: FULL,
            zIndex: 3,
          }),
          b("text", {
            name: "Print-only",
            x: 40,
            y: 882,
            w: 400,
            h: 20,
            content: { text: "LABEL · {{device.media}} · {{device.dpi}}dpi" },
            style: { fontSize: 10, color: "#0f6b63" },
            condition: "output.kind == 'print' && device.media == 'label'",
          }),
          b("text", {
            name: "Footer",
            x: 40,
            y: 910,
            w: 640,
            h: 18,
            content: { text: "texLooper · {{company|default:texLooper}} · Open Samples for more templates" },
            style: { fontSize: 9, color: "#5c6570", textAlign: "center" },
            condition: FULL,
            pin: { bottom: true, left: true, right: true },
          }),
        ],
        { pageNumber: { mode: "all", format: "{n}" } },
      ),
      page(
        "More features",
        [
          b("shape", {
            name: "Header bar",
            x: 0,
            y: 0,
            w: 720,
            h: 48,
            content: { shape: "rect", filled: true },
            style: { background: "#f3f7fb" },
            zIndex: 0,
            pin: { top: true, left: true, right: true },
            condition: FULL,
          }),
          b("text", {
            name: "Page 2 title",
            x: 40,
            y: 14,
            w: 400,
            h: 24,
            content: { text: "More features" },
            style: { fontFamily: "display", fontSize: 18, fontWeight: 700, color: "#1c2430" },
            condition: FULL,
            zIndex: 1,
          }),
          b("shape", {
            name: "Top rule",
            x: 40,
            y: 64,
            w: 640,
            h: 2,
            content: { variant: "line" },
            style: { borderWidth: 1, borderColor: "#d4d9e0" },
            condition: FULL,
          }),

          /* ── Page numbers ── */
          b("text", {
            name: "Heading pages",
            x: 40,
            y: 84,
            w: 300,
            h: 16,
            content: { text: "PAGE NUMBERS" },
            style: {
              fontFamily: "ui", fontSize: 10, fontWeight: 700,
              textTransform: "uppercase", letterSpacing: 1.6, color: "#2383e2",
            },
            condition: FULL,
          }),
          b("paragraph", {
            name: "Page number text",
            x: 40,
            y: 106,
            w: 640,
            h: 40,
            content: {
              text: "This page has automatic page numbering enabled. Check the bottom of each page in the preview — the number appears automatically.",
            },
            style: { fontSize: 12, lineHeight: 1.5, color: "#1c2430" },
            condition: FULL,
          }),

          /* ── Conditional content ── */
          b("text", {
            name: "Heading cond",
            x: 40,
            y: 164,
            w: 400,
            h: 16,
            content: { text: "CONDITIONAL CONTENT" },
            style: {
              fontFamily: "ui", fontSize: 10, fontWeight: 700,
              textTransform: "uppercase", letterSpacing: 1.6, color: "#2383e2",
            },
            condition: FULL,
          }),
          b("paragraph", {
            name: "Conditional text",
            x: 40,
            y: 188,
            w: 640,
            h: 64,
            content: {
              text: "{{#if role}}You are listed as {{role}} in the data. {{/if}}Conditional blocks let you show or hide content based on data values, output mode, or environment flags.",
            },
            style: { fontSize: 12, lineHeight: 1.55, color: "#1c2430" },
            condition: FULL,
          }),
          b("text", {
            name: "Print-only 2",
            x: 40,
            y: 268,
            w: 640,
            h: 28,
            content: { text: "This line only appears in print or PDF output." },
            style: { fontSize: 11, fontStyle: "italic", color: "#5c6570" },
            condition: "output.kind == 'print' || output.kind == 'pdf'",
          }),

          /* ── Data filters ── */
          b("text", {
            name: "Heading filters",
            x: 40,
            y: 312,
            w: 400,
            h: 16,
            content: { text: "DATA FILTERS" },
            style: {
              fontFamily: "ui", fontSize: 10, fontWeight: 700,
              textTransform: "uppercase", letterSpacing: 1.6, color: "#2383e2",
            },
            condition: FULL,
          }),
          b("text", {
            name: "Lower filter",
            x: 40,
            y: 340,
            w: 640,
            h: 24,
            content: { text: "|lower: {{name|lower}} · |capitalize: {{name|capitalize}} · |title: {{role|title}}" },
            style: { fontSize: 12, color: "#1c2430" },
            condition: FULL,
          }),
          b("text", {
            name: "Upper filter",
            x: 40,
            y: 368,
            w: 640,
            h: 24,
            content: { text: "|upper: {{name|upper}} · |number: {{qty|number:0}} · |currency: {{price|currency:EUR}}" },
            style: { fontSize: 12, color: "#1c2430" },
            condition: FULL,
          }),
          b("text", {
            name: "Date filters",
            x: 40,
            y: 396,
            w: 640,
            h: 24,
            content: {
              text: "|date:short {{event_date|date:short}} · |date:long {{event_date|date:long}} · today {{env.today|date:short}}",
            },
            style: { fontSize: 12, color: "#1c2430" },
            condition: FULL,
          }),

          /* ── Style gallery ── */
          b("text", {
            name: "Heading styles",
            x: 40,
            y: 448,
            w: 400,
            h: 16,
            content: { text: "STYLE GALLERY" },
            style: {
              fontFamily: "ui", fontSize: 10, fontWeight: 700,
              textTransform: "uppercase", letterSpacing: 1.6, color: "#2383e2",
            },
            condition: FULL,
          }),
          b("shape", {
            name: "Style card 1",
            x: 40,
            y: 468,
            w: 200,
            h: 90,
            content: { shape: "rect" },
            style: { background: "#2383e2", borderRadius: 8, opacity: 0.15 },
            condition: FULL,
          }),
          b("shape", {
            name: "Style card 2",
            x: 260,
            y: 468,
            w: 200,
            h: 90,
            content: { shape: "rect" },
            style: { background: "#ffffff", borderRadius: 8, borderWidth: 2, borderColor: "#2383e2" },
            condition: FULL,
          }),
          b("shape", {
            name: "Style card 3",
            x: 480,
            y: 468,
            w: 200,
            h: 90,
            content: { shape: "rect" },
            style: { background: "#f2f4f7", borderRadius: 8, shadow: true },
            condition: FULL,
          }),

          /* ── Font presets ── */
          b("text", {
            name: "Heading fonts",
            x: 40,
            y: 584,
            w: 400,
            h: 16,
            content: { text: "FONT PRESETS" },
            style: {
              fontFamily: "ui", fontSize: 10, fontWeight: 700,
              textTransform: "uppercase", letterSpacing: 1.6, color: "#2383e2",
            },
            condition: FULL,
          }),
          b("text", {
            name: "Doc font",
            x: 40,
            y: 612,
            w: 640,
            h: 24,
            content: { text: "Document font (Source Serif) — serif body text for readability." },
            style: { fontFamily: "doc", fontSize: 12, color: "#1c2430" },
            condition: FULL,
          }),
          b("text", {
            name: "UI font",
            x: 40,
            y: 648,
            w: 640,
            h: 24,
            content: { text: "Interface font (Sora) — clean sans-serif for UI chrome." },
            style: { fontFamily: "ui", fontSize: 12, color: "#1c2430" },
            condition: FULL,
          }),
          b("text", {
            name: "Mono font 2",
            x: 40,
            y: 684,
            w: 640,
            h: 24,
            content: { text: "Monospace font — code, tracking numbers, technical data." },
            style: { fontFamily: "mono", fontSize: 12, color: "#3d4a5c" },
            condition: FULL,
          }),
          b("text", {
            name: "Inter font",
            x: 40,
            y: 720,
            w: 640,
            h: 24,
            content: { text: "Display font — headlines and hero titles." },
            style: { fontFamily: "display", fontSize: 12, color: "#1c2430" },
            condition: FULL,
          }),
          b("paragraph", {
            name: "Next steps EN",
            x: 40,
            y: 768,
            w: 640,
            h: 72,
            content: {
              text: "Next: open Samples, load another template, and flip Data rows or the language chip. Every merge field updates live; SMS FR vs PDF EN show different conditions.",
            },
            style: { fontSize: 12, lineHeight: 1.55, color: "#3d4a5c" },
            condition: `${FULL} && ${EN}`,
          }),
          b("paragraph", {
            name: "Next steps FR",
            x: 40,
            y: 768,
            w: 640,
            h: 72,
            content: {
              text: "Ensuite : ouvrez Samples, chargez un autre modèle, et changez la ligne de données ou la langue. Les champs de fusion se mettent à jour ; SMS FR et PDF EN utilisent des conditions différentes.",
            },
            style: { fontSize: 12, lineHeight: 1.55, color: "#3d4a5c" },
            condition: `${FULL} && ${FR}`,
          }),
          b("paragraph", {
            name: "Next steps NL",
            x: 40,
            y: 768,
            w: 640,
            h: 72,
            content: {
              text: "Vervolg: open Samples, laad een ander sjabloon en wissel data-rijen of taal. Samenvoegvelden updaten live; SMS NL versus PDF EN tonen andere voorwaarden.",
            },
            style: { fontSize: 12, lineHeight: 1.55, color: "#3d4a5c" },
            condition: `${FULL} && ${NL}`,
          }),
          b("text", {
            name: "Footer",
            x: 40,
            y: 900,
            w: 640,
            h: 18,
            content: { text: "texLooper · page 2 · {{company|default:texLooper}}" },
            style: { fontSize: 9, color: "#5c6570", textAlign: "center" },
            condition: FULL,
            pin: { bottom: true, left: true, right: true },
          }),
        ],
        { pageNumber: { mode: "all", format: "{n}" } },
      ),
    ],
    {
      comments: [
        {
          id: createId(),
          blockId: blockA,
          body: "Open Samples for full letter, contract, invoice, email, and more.",
          author: "Guide",
          createdAt: new Date().toISOString(),
        },
      ],
      outputs: [...defaultOutputs(), ...channelOutputs],
      ...northlineStyleExtras("en"),
    },
  );
}

function jobEntry(
  y: number,
  f: { period: string; title: string; company: string; p1: string; p2: string; p3: string },
) {
  return [
    b("text", {
      name: `Job period ${f.period}`,
      x: 56,
      y,
      w: 96,
      h: 20,
      content: { text: f.period },
      style: {
        fontFamily: "ui",
        fontSize: 10,
        fontWeight: 600,
        color: MUTED,
        verticalAlign: "middle",
      },
    }),
    b("text", {
      name: `Job role ${f.title}`,
      x: 164,
      y,
      w: 292,
      h: 20,
      content: { text: f.title },
      style: {
        fontFamily: "ui",
        fontSize: 12.5,
        fontWeight: 700,
        color: INK,
        verticalAlign: "middle",
      },
    }),
    b("list", {
      name: `Job bullets ${f.company}`,
      x: 164,
      y: y + 26,
      w: 292,
      h: 108,
      content: {
        items: [f.p1, f.p2, f.p3],
        markerColor: ACCENT,
      },
      style: {
        fontSize: 11.5,
        lineHeight: 1.35,
        color: INK,
        listStyle: "disc",
      },
    }),
  ];
}

export function resume(): Project {
  const teal = resumePalette("teal");
  return shell(
    {
      name: "Resume — merge-field template",
      author: "texLooper samples",
      subject: "CV + cover letter driven by Data rows",
      description:
        "Two-page resume with palette axis, four jobs, tiered skill chips, plus a matching cover letter. Flip Data rows to render each candidate.",
    },
    [
      page("Resume", [
        // ---- Header ----
        b("picture", {
          name: "Portrait",
          x: 560,
          y: 44,
          w: 104,
          h: 104,
          content: { src: "", alt: "Portrait", fit: "cover" },
          style: { borderRadius: 52, borderWidth: 2, borderColor: ACCENT },
        }),
        b("text", {
          name: "Candidate name",
          x: 56,
          y: 48,
          w: 480,
          h: 56,
          content: { text: "{{full_name}}" },
          style: {
            fontFamily: "display",
            fontSize: 34,
            fontWeight: 700,
            color: INK,
          },
        }),
        ...paletteVariants((palette) =>
          b("text", {
            name: "Role line",
            x: 56,
            y: 104,
            w: 480,
            h: 22,
            content: { text: "{{role}}" },
            style: {
              fontFamily: "ui",
              fontSize: 13,
              fontWeight: 600,
              textTransform: "uppercase",
              letterSpacing: 2.4,
              color: palette.accent,
              verticalAlign: "middle",
            },
          }),
        ),
        b("text", {
          name: "Contact block",
          x: 56,
          y: 130,
          w: 400,
          h: 40,
          content: {
            text: "{{email}} · {{phone}}\n{{location}} · {{website}}",
          },
          style: {
            fontFamily: "ui",
            fontSize: 10.5,
            lineHeight: 1.5,
            color: MUTED,
          },
        }),
        ...paletteAccentRule(56, 172, 608),

        // ---- Main column ----
        ...paletteSectionHeading("Profile", 56, 192, 200),
        b("paragraph", {
          name: "Summary",
          x: 56,
          y: 214,
          w: 400,
          h: 84,
          content: { text: "{{summary}}" },
          style: { fontSize: 11.5, lineHeight: 1.55, color: INK },
        }),
        ...paletteSectionHeading("Experience", 56, 304, 200),
        ...jobEntry(328, {
          period: "{{j1_period}}",
          title: "{{j1_title}} — {{j1_company}}",
          company: "j1",
          p1: "{{j1_p1}}",
          p2: "{{j1_p2}}",
          p3: "{{j1_p3}}",
        }),
        ...jobEntry(456, {
          period: "{{j2_period}}",
          title: "{{j2_title}} — {{j2_company}}",
          company: "j2",
          p1: "{{j2_p1}}",
          p2: "{{j2_p2}}",
          p3: "{{j2_p3}}",
        }),
        ...jobEntry(584, {
          period: "{{j3_period}}",
          title: "{{j3_title}} — {{j3_company}}",
          company: "j3",
          p1: "{{j3_p1}}",
          p2: "{{j3_p2}}",
          p3: "{{j3_p3}}",
        }),
        ...jobEntry(712, {
          period: "{{j4_period}}",
          title: "{{j4_title}} — {{j4_company}}",
          company: "j4",
          p1: "{{j4_p1}}",
          p2: "{{j4_p2}}",
          p3: "",
        }),

        // ---- Sidebar ----
        b("shape", {
          name: "Aside wash",
          x: 488,
          y: 212,
          w: 176,
          h: 580,
          content: { variant: "rect" },
          style: {
            background: "#f3f6fa",
            borderRadius: 8,
            shadow: true,
          },
        }),
        ...paletteSectionHeading("Skills", 500, 228, 152),
        ...mergeSkillChipSlot(502, 254, 1, teal),
        ...mergeSkillChipSlot(502, 282, 2, teal),
        ...mergeSkillChipSlot(502, 310, 3, teal),
        ...mergeSkillChipSlot(502, 338, 4, teal),
        ...mergeSkillChipSlot(502, 366, 5, teal),
        ...mergeSkillChipSlot(502, 394, 6, teal),
        b("text", {
          name: "Skills tier summary",
          x: 502,
          y: 428,
          w: 150,
          h: 72,
          content: {
            text: "Expert: {{skills_expert}}\n\nProficient: {{skills_proficient}}\n\nExposure: {{skills_exposure}}",
          },
          style: { fontSize: 8.5, lineHeight: 1.35, color: MUTED },
        }),
        ...paletteSectionHeading("Education", 500, 510, 152),
        b("text", {
          name: "Education entries",
          x: 500,
          y: 534,
          w: 152,
          h: 120,
          content: {
            text: "{{edu1_degree}}\n{{edu1_school}}, {{edu1_years}}\n\n{{edu2_degree}}\n{{edu2_school}}, {{edu2_years}}",
          },
          style: { fontSize: 10.5, lineHeight: 1.45, color: INK },
        }),
        ...paletteSectionHeading("Languages", 500, 670, 152),
        b("text", {
          name: "Languages line",
          x: 500,
          y: 694,
          w: 152,
          h: 70,
          content: { text: "{{languages}}" },
          style: { fontSize: 10.5, lineHeight: 1.5, color: INK },
        }),

        // ---- Footer ----
        b("shape", {
          name: "Bottom rule",
          x: 56,
          y: 792,
          w: 608,
          h: 1,
          content: { variant: "line" },
          style: { borderWidth: 1, borderColor: "#d4d9e0" },
        }),
        b("text", {
          name: "Footer",
          x: 56,
          y: 900,
          w: 608,
          h: 18,
          content: {
            text: "References available on request · {{website}}",
          },
          style: {
            fontFamily: "ui",
            fontSize: 9.5,
            letterSpacing: 0.4,
            color: MUTED,
            textAlign: "center",
          },
          pin: { bottom: true, left: true, right: true },
        }),
      ]),
      page("Cover letter", [
        b("shape", {
          name: "Letterhead",
          x: 0,
          y: 0,
          w: 720,
          h: 48,
          content: { shape: "rect", filled: true },
          style: { background: "#f7f9fc" },
          zIndex: 0,
          pin: { top: true, left: true, right: true },
        }),
        b("text", {
          name: "CL sender",
          x: 56,
          y: 64,
          w: 400,
          h: 56,
          content: {
            text: "{{full_name}}\n{{email}} · {{phone}}\n{{location}}",
          },
          style: { fontFamily: "ui", fontSize: 10.5, lineHeight: 1.5, color: MUTED },
        }),
        b("picture", {
          name: "CL portrait",
          x: 560,
          y: 60,
          w: 104,
          h: 104,
          content: { src: "", alt: "Portrait", fit: "cover" },
          style: { borderRadius: 52, borderWidth: 2, borderColor: ACCENT },
        }),
        b("shape", {
          name: "Top rule",
          x: 56,
          y: 140,
          w: 608,
          h: 3,
          content: { variant: "rect" },
          style: { background: ACCENT, borderRadius: 2 },
        }),
        b("text", {
          name: "CL subject",
          x: 56,
          y: 164,
          w: 460,
          h: 20,
          content: { text: "Application: {{role}}" },
          style: {
            fontFamily: "ui",
            fontSize: 11,
            fontWeight: 700,
            textTransform: "uppercase",
            letterSpacing: 1.6,
            color: ACCENT,
          },
        }),
        b("text", {
          name: "CL recipient",
          x: 56,
          y: 196,
          w: 420,
          h: 44,
          content: {
            text: "Hiring Team\n[Company name]\n[Office address]",
          },
          style: { fontFamily: "ui", fontSize: 11, lineHeight: 1.45, color: INK },
        }),
        b("text", {
          name: "CL salutation",
          x: 56,
          y: 260,
          w: 608,
          h: 22,
          content: { text: "Dear Hiring Team," },
          style: { fontFamily: "ui", fontSize: 12, color: INK },
        }),
        b("paragraph", {
          name: "CL opening",
          x: 56,
          y: 296,
          w: 608,
          h: 120,
          content: {
            text: "I am applying for the {{role}} position. {{summary}} The short version: I like owning outcomes end to end, and I measure my work by the numbers it moves.\n\nI am writing because your team’s problems match the work I do best — clear systems, honest metrics, and delivery that compounds.",
          },
          style: { fontFamily: "ui", fontSize: 11.5, lineHeight: 1.6, color: INK },
        }),
        b("paragraph", {
          name: "CL proof",
          x: 56,
          y: 436,
          w: 608,
          h: 140,
          content: {
            text: "Most recently at {{j1_company}}, {{j1_p1|lower}} — and before that, {{j2_p1|lower}}. Earlier in my career at {{j3_company}} I learned to ship small, measure honestly, and write things down so the next person moves faster.\n\nThose habits travel: I still keep a weekly review of what shipped, what slipped, and what I would change next time.",
          },
          style: { fontFamily: "ui", fontSize: 11.5, lineHeight: 1.6, color: INK },
        }),
        b("paragraph", {
          name: "CL fit",
          x: 56,
          y: 596,
          w: 608,
          h: 110,
          content: {
            text: "What draws me to your team is the chance to bring {{skill1}}, {{skill2}} and {{skill3}} to problems that matter, alongside people who care about craft. My toolkit also covers {{skill4}} and {{skill5}}, picked up while delivering {{edu1_degree}}-level coursework and everything since.",
          },
          style: { fontFamily: "ui", fontSize: 11.5, lineHeight: 1.6, color: INK },
        }),
        b("paragraph", {
          name: "CL closing",
          x: 56,
          y: 724,
          w: 608,
          h: 72,
          content: {
            text: "My full CV is on page one; references are available on request. Thank you for your time and consideration — I would welcome a conversation about where I can help your team most.",
          },
          style: { fontFamily: "ui", fontSize: 11.5, lineHeight: 1.6, color: INK },
        }),
        b("text", {
          name: "CL sign-off",
          x: 56,
          y: 812,
          w: 608,
          h: 48,
          content: {
            text: "Kind regards,\n{{full_name}}\n{{website}}",
          },
          style: { fontFamily: "ui", fontSize: 11.5, lineHeight: 1.5, color: INK },
        }),
        b("text", {
          name: "Footer",
          x: 56,
          y: 900,
          w: 608,
          h: 18,
          content: { text: "{{full_name}} · {{role}} · Confidential" },
          style: { fontFamily: "ui", fontSize: 9, color: MUTED, textAlign: "center" },
          pin: { bottom: true, left: true, right: true },
        }),
      ]),
    ],
    { conditions: [resumePaletteCondition()] },
  );
}

