import type { Project } from "../../document";
import { b, page, shell } from "../helpers";

const SIDE_BG = "#1a2332";
const SIDE_INK = "#e8eef6";
const SIDE_MUTED = "#9aabbc";
const ACCENT = "#3d9cf0";
const INK = "#232a33";
const MUTED = "#5c6570";
const PAPER = "#f7f4ef";

/** Left-rail CV — dense sidebar + main column (mirrors classic right-photo layouts). */
export function resumeSidebar(): Project {
  return shell(
    {
      name: "Resume — sidebar",
      author: "texLooper samples",
      subject: "Two-column CV with dark rail",
      description:
        "Sidebar contact/skills rail with main experience column. Flip Data rows to switch candidates. Shows padding, opacity, borders, and flex gap.",
    },
    [
      page(
        "Resume",
        [
          b("shape", {
            name: "Rail",
            x: 0,
            y: 0,
            w: 220,
            h: 960,
            content: { shape: "rect" },
            style: { background: SIDE_BG },
            zIndex: 0,
            pin: { left: true, top: true, bottom: true },
          }),
          b("text", {
            name: "Name",
            x: 16,
            y: 40,
            w: 188,
            h: 56,
            content: { text: "{{full_name}}" },
            style: {
              fontFamily: "display",
              fontSize: 22,
              fontWeight: 700,
              color: SIDE_INK,
              lineHeight: 1.2,
            },
            zIndex: 1,
          }),
          b("text", {
            name: "Role",
            x: 16,
            y: 104,
            w: 188,
            h: 36,
            content: { text: "{{role}}" },
            style: {
              fontFamily: "ui",
              fontSize: 11,
              fontWeight: 600,
              textTransform: "uppercase",
              letterSpacing: 1.4,
              color: ACCENT,
              lineHeight: 1.35,
            },
            zIndex: 1,
          }),
          b("text", {
            name: "Contact",
            x: 16,
            y: 160,
            w: 188,
            h: 72,
            content: {
              text: "{{email}}\n{{phone}}\n{{location}}\n{{website}}",
            },
            style: {
              fontFamily: "ui",
              fontSize: 10,
              lineHeight: 1.55,
              color: SIDE_MUTED,
            },
            zIndex: 1,
          }),
          b("text", {
            name: "Skills heading",
            x: 16,
            y: 260,
            w: 188,
            h: 18,
            content: { text: "Skills" },
            style: {
              fontFamily: "ui",
              fontSize: 10,
              fontWeight: 700,
              textTransform: "uppercase",
              letterSpacing: 1.5,
              color: ACCENT,
            },
            zIndex: 1,
          }),
          b("paragraph", {
            name: "Skills",
            x: 16,
            y: 284,
            w: 188,
            h: 160,
            content: {
              text: "{{skill1}} · {{skill2}} · {{skill3}} · {{skill4}} · {{skill5}} · {{skill6}}",
            },
            style: {
              fontFamily: "ui",
              fontSize: 10.5,
              lineHeight: 1.55,
              color: SIDE_INK,
              padding: 0,
            },
            zIndex: 1,
          }),
          b("text", {
            name: "Education heading",
            x: 16,
            y: 470,
            w: 188,
            h: 18,
            content: { text: "Education" },
            style: {
              fontFamily: "ui",
              fontSize: 10,
              fontWeight: 700,
              textTransform: "uppercase",
              letterSpacing: 1.5,
              color: ACCENT,
            },
            zIndex: 1,
          }),
          b("paragraph", {
            name: "Education",
            x: 16,
            y: 494,
            w: 188,
            h: 100,
            content: {
              text: "{{edu1_degree}}\n{{edu1_school}}, {{edu1_years}}\n\n{{edu2_degree}}\n{{edu2_school}}, {{edu2_years}}",
            },
            style: {
              fontFamily: "ui",
              fontSize: 10,
              lineHeight: 1.45,
              color: SIDE_MUTED,
            },
            zIndex: 1,
          }),
          b("text", {
            name: "Languages",
            x: 16,
            y: 620,
            w: 188,
            h: 60,
            content: { text: "{{languages}}" },
            style: {
              fontFamily: "ui",
              fontSize: 10,
              lineHeight: 1.45,
              color: SIDE_MUTED,
            },
            zIndex: 1,
          }),

          b("text", {
            name: "Profile H",
            x: 248,
            y: 40,
            w: 420,
            h: 18,
            content: { text: "Profile" },
            style: {
              fontFamily: "ui",
              fontSize: 11,
              fontWeight: 700,
              textTransform: "uppercase",
              letterSpacing: 1.6,
              color: ACCENT,
            },
          }),
          b("paragraph", {
            name: "Summary",
            x: 248,
            y: 64,
            w: 420,
            h: 88,
            content: { text: "{{summary}}" },
            style: {
              fontSize: 11.5,
              lineHeight: 1.55,
              color: INK,
              padding: 4,
            },
          }),
          b("text", {
            name: "Experience H",
            x: 248,
            y: 168,
            w: 420,
            h: 18,
            content: { text: "Experience" },
            style: {
              fontFamily: "ui",
              fontSize: 11,
              fontWeight: 700,
              textTransform: "uppercase",
              letterSpacing: 1.6,
              color: ACCENT,
            },
          }),
          b("text", {
            name: "J1 title",
            x: 248,
            y: 196,
            w: 420,
            h: 20,
            content: { text: "{{j1_title}} — {{j1_company}}" },
            style: { fontFamily: "ui", fontSize: 12, fontWeight: 700, color: INK },
          }),
          b("text", {
            name: "J1 period",
            x: 248,
            y: 216,
            w: 420,
            h: 16,
            content: { text: "{{j1_period}}" },
            style: { fontSize: 10, color: MUTED },
          }),
          b("list", {
            name: "J1 bullets",
            x: 248,
            y: 236,
            w: 420,
            h: 88,
            content: {
              items: ["{{j1_p1}}", "{{j1_p2}}", "{{j1_p3}}"],
            },
            style: { fontSize: 11, lineHeight: 1.45, color: INK, listStyle: "disc" },
          }),
          b("text", {
            name: "J2 title",
            x: 248,
            y: 340,
            w: 420,
            h: 20,
            content: { text: "{{j2_title}} — {{j2_company}}" },
            style: { fontFamily: "ui", fontSize: 12, fontWeight: 700, color: INK },
          }),
          b("text", {
            name: "J2 period",
            x: 248,
            y: 360,
            w: 420,
            h: 16,
            content: { text: "{{j2_period}}" },
            style: { fontSize: 10, color: MUTED },
          }),
          b("list", {
            name: "J2 bullets",
            x: 248,
            y: 380,
            w: 420,
            h: 88,
            content: {
              items: ["{{j2_p1}}", "{{j2_p2}}", "{{j2_p3}}"],
            },
            style: { fontSize: 11, lineHeight: 1.45, color: INK, listStyle: "disc" },
          }),
          b("text", {
            name: "J3 title",
            x: 248,
            y: 484,
            w: 420,
            h: 20,
            content: { text: "{{j3_title}} — {{j3_company}}" },
            style: { fontFamily: "ui", fontSize: 12, fontWeight: 700, color: INK },
          }),
          b("text", {
            name: "J3 period",
            x: 248,
            y: 504,
            w: 420,
            h: 16,
            content: { text: "{{j3_period}}" },
            style: { fontSize: 10, color: MUTED },
          }),
          b("list", {
            name: "J3 bullets",
            x: 248,
            y: 524,
            w: 420,
            h: 88,
            content: {
              items: ["{{j3_p1}}", "{{j3_p2}}"],
            },
            style: { fontSize: 11, lineHeight: 1.45, color: INK, listStyle: "disc" },
          }),
          b("shape", {
            name: "Accent bar",
            x: 248,
            y: 640,
            w: 420,
            h: 4,
            content: { shape: "rect" },
            style: { background: ACCENT, borderRadius: 2 },
          }),
          b("paragraph", {
            name: "Footer note",
            x: 248,
            y: 660,
            w: 420,
            h: 40,
            content: {
              text: "References available on request · Portfolio at {{website}}",
            },
            style: { fontSize: 10, color: MUTED, fontStyle: "italic" },
            pin: { bottom: true },
          }),
        ],
        {
          background: "#ffffff",
          margins: { top: 0, right: 48, bottom: 40, left: 0 },
        },
      ),
      page(
        "Projects",
        [
          b("shape", {
            name: "Rail",
            x: 0,
            y: 0,
            w: 220,
            h: 960,
            content: { shape: "rect", filled: true },
            style: { background: SIDE_BG },
            zIndex: 0,
            pin: { left: true, top: true, bottom: true },
          }),
          b("text", {
            name: "Side title",
            x: 16,
            y: 48,
            w: 188,
            h: 48,
            content: { text: "{{full_name}}" },
            style: {
              fontFamily: "display",
              fontSize: 18,
              fontWeight: 700,
              color: SIDE_INK,
              lineHeight: 1.25,
            },
            zIndex: 1,
          }),
          b("text", {
            name: "Side subtitle",
            x: 16,
            y: 108,
            w: 188,
            h: 40,
            content: { text: "Selected projects\n& credentials" },
            style: {
              fontFamily: "ui",
              fontSize: 11,
              fontWeight: 600,
              textTransform: "uppercase",
              letterSpacing: 1.2,
              color: ACCENT,
              lineHeight: 1.4,
            },
            zIndex: 1,
          }),
          b("text", {
            name: "Side note",
            x: 16,
            y: 180,
            w: 188,
            h: 120,
            content: {
              text: "{{email}}\n{{website}}\n\nOpen to remote · {{location}}",
            },
            style: {
              fontFamily: "ui",
              fontSize: 10,
              lineHeight: 1.55,
              color: SIDE_MUTED,
            },
            zIndex: 1,
          }),
          b("text", {
            name: "Languages side",
            x: 16,
            y: 820,
            w: 188,
            h: 48,
            content: { text: "{{languages}}" },
            style: {
              fontFamily: "ui",
              fontSize: 10,
              lineHeight: 1.45,
              color: SIDE_MUTED,
            },
            zIndex: 1,
          }),
          b("text", {
            name: "Projects heading",
            x: 248,
            y: 40,
            w: 420,
            h: 24,
            content: { text: "SELECTED WORK" },
            style: {
              fontFamily: "ui",
              fontSize: 12,
              fontWeight: 700,
              letterSpacing: 1.6,
              color: ACCENT,
            },
          }),
          b("text", {
            name: "Proj 1 title",
            x: 248,
            y: 80,
            w: 420,
            h: 22,
            content: { text: "{{j1_title}} — {{j1_company}}" },
            style: {
              fontFamily: "ui",
              fontSize: 13,
              fontWeight: 700,
              color: INK,
            },
          }),
          b("paragraph", {
            name: "Proj 1 body",
            x: 248,
            y: 108,
            w: 420,
            h: 100,
            content: {
              text: "{{j1_p1}}\n\n{{j1_p2}}\n\n{{j1_p3}}",
            },
            style: { fontSize: 11, lineHeight: 1.5, color: INK },
          }),
          b("text", {
            name: "Proj 2 title",
            x: 248,
            y: 232,
            w: 420,
            h: 22,
            content: { text: "{{j2_title}} — {{j2_company}}" },
            style: {
              fontFamily: "ui",
              fontSize: 13,
              fontWeight: 700,
              color: INK,
            },
          }),
          b("paragraph", {
            name: "Proj 2 body",
            x: 248,
            y: 260,
            w: 420,
            h: 100,
            content: {
              text: "{{j2_p1}}\n\n{{j2_p2}}\n\n{{j2_p3}}",
            },
            style: { fontSize: 11, lineHeight: 1.5, color: INK },
          }),
          b("text", {
            name: "Education heading",
            x: 248,
            y: 400,
            w: 420,
            h: 22,
            content: { text: "EDUCATION" },
            style: {
              fontFamily: "ui",
              fontSize: 12,
              fontWeight: 700,
              letterSpacing: 1.6,
              color: ACCENT,
            },
          }),
          b("paragraph", {
            name: "Education detail",
            x: 248,
            y: 432,
            w: 420,
            h: 72,
            content: {
              text: "{{edu1_degree}} — {{edu1_school}} ({{edu1_years}})\n{{edu2_degree}} — {{edu2_school}} ({{edu2_years}})",
            },
            style: { fontSize: 12, lineHeight: 1.55, color: INK },
          }),
          b("text", {
            name: "Refs heading",
            x: 248,
            y: 540,
            w: 420,
            h: 22,
            content: { text: "REFERENCES" },
            style: {
              fontFamily: "ui",
              fontSize: 12,
              fontWeight: 700,
              letterSpacing: 1.6,
              color: ACCENT,
            },
          }),
          b("paragraph", {
            name: "Refs body",
            x: 248,
            y: 572,
            w: 420,
            h: 80,
            content: {
              text: "Professional references available on request. Happy to share case write-ups and architecture notes for {{j1_company}} and {{j2_company}} under NDA.",
            },
            style: { fontSize: 11, lineHeight: 1.5, color: MUTED },
          }),
          b("shape", {
            name: "Accent bar",
            x: 248,
            y: 680,
            w: 420,
            h: 4,
            content: { shape: "rect", filled: true },
            style: { background: ACCENT, borderRadius: 2 },
          }),
          b("text", {
            name: "Footer",
            x: 248,
            y: 900,
            w: 420,
            h: 20,
            content: { text: "{{full_name}} · {{role}} · page 2" },
            style: { fontSize: 9, color: MUTED, textAlign: "center" },
            pin: { bottom: true, left: true, right: true },
          }),
        ],
        {
          background: "#ffffff",
          margins: { top: 0, right: 48, bottom: 40, left: 0 },
        },
      ),
    ],
  );
}

/** Creative CV — paper tone, rotated seal, mirrored accent strip. */
export function resumeCreative(): Project {
  return shell(
    {
      name: "Resume — creative",
      author: "texLooper samples",
      subject: "Editorial CV with transforms",
      description:
        "Warm paper surface, rotated availability seal, mirrored decorative strip, shadow cards. Showcases rotate / mirror / opacity / radius.",
    },
    [
      page(
        "Portfolio CV",
        [
          b("shape", {
            name: "Rail",
            x: 640,
            y: 0,
            w: 80,
            h: 960,
            content: { shape: "rect" },
            style: {
              background: "#c45c26",
              opacity: 0.9,
              mirrorX: true,
            },
            zIndex: 0,
            pin: { right: true, top: true, bottom: true },
          }),
          b("text", {
            name: "Name",
            x: 48,
            y: 48,
            w: 520,
            h: 48,
            content: { text: "{{full_name}}" },
            style: {
              fontFamily: "display",
              fontSize: 36,
              fontWeight: 700,
              color: INK,
            },
            zIndex: 1,
          }),
          b("text", {
            name: "Role",
            x: 48,
            y: 100,
            w: 480,
            h: 22,
            content: { text: "{{role}}" },
            style: {
              fontFamily: "ui",
              fontSize: 13,
              fontWeight: 600,
              letterSpacing: 2,
              textTransform: "uppercase",
              color: "#c45c26",
            },
            zIndex: 1,
          }),
          b("text", {
            name: "Contact",
            x: 48,
            y: 132,
            w: 480,
            h: 28,
            content: { text: "{{email}}  ·  {{phone}}  ·  {{location}}" },
            style: { fontSize: 11, color: MUTED },
            zIndex: 1,
          }),
          b("shape", {
            name: "Availability seal",
            x: 520,
            y: 40,
            w: 100,
            h: 100,
            content: { shape: "ellipse" },
            style: {
              background: "#c45c26",
              opacity: 0.92,
              rotate: -18,
              shadow: true,
              borderWidth: 0,
            },
            zIndex: 2,
          }),
          b("text", {
            name: "Seal label",
            x: 530,
            y: 72,
            w: 80,
            h: 40,
            content: { text: "OPEN\nTO WORK" },
            style: {
              fontFamily: "ui",
              fontSize: 11,
              fontWeight: 700,
              textAlign: "center",
              color: "#fffaf5",
              letterSpacing: 1,
              rotate: -18,
              lineHeight: 1.25,
            },
            zIndex: 3,
          }),
          b("paragraph", {
            name: "Summary card",
            x: 48,
            y: 180,
            w: 560,
            h: 130,
            content: {
              text: "{{summary}}\n\nAvailable for remote or hybrid roles across the EU; portfolio and references on request.",
            },
            style: {
              fontSize: 12,
              lineHeight: 1.55,
              color: INK,
              background: "#fff",
              padding: 14,
              borderRadius: 8,
              shadow: true,
              borderWidth: 1,
              borderColor: "#e6ddd2",
            },
          }),
          b("text", {
            name: "Recent",
            x: 48,
            y: 332,
            w: 200,
            h: 18,
            content: { text: "Recent work" },
            style: {
              fontFamily: "ui",
              fontSize: 11,
              fontWeight: 700,
              textTransform: "uppercase",
              letterSpacing: 1.6,
              color: "#c45c26",
            },
          }),
          b("text", {
            name: "J1",
            x: 48,
            y: 360,
            w: 560,
            h: 20,
            content: { text: "{{j1_title}} @ {{j1_company}}  ·  {{j1_period}}" },
            style: { fontSize: 12, fontWeight: 700, color: INK },
          }),
          b("paragraph", {
            name: "J1 body",
            x: 48,
            y: 388,
            w: 560,
            h: 88,
            content: { text: "{{j1_p1}} {{j1_p2}} {{j1_p3}}" },
            style: { fontSize: 11.5, lineHeight: 1.5, color: INK },
          }),
          b("text", {
            name: "J2",
            x: 48,
            y: 496,
            w: 560,
            h: 20,
            content: { text: "{{j2_title}} @ {{j2_company}}  ·  {{j2_period}}" },
            style: { fontSize: 12, fontWeight: 700, color: INK },
          }),
          b("paragraph", {
            name: "J2 body",
            x: 48,
            y: 524,
            w: 560,
            h: 88,
            content: { text: "{{j2_p1}} {{j2_p2}} {{j2_p3}}" },
            style: { fontSize: 11.5, lineHeight: 1.5, color: INK },
          }),
          b("shape", {
            name: "Skill chip 1",
            x: 48,
            y: 640,
            w: 120,
            h: 32,
            content: { shape: "rect" },
            style: {
              background: "#fff",
              borderRadius: 16,
              borderWidth: 1,
              borderColor: "#c45c26",
              rotate: -4,
              shadow: true,
            },
            zIndex: 1,
          }),
          b("text", {
            name: "Skill 1 label",
            x: 48,
            y: 646,
            w: 120,
            h: 22,
            content: { text: "{{skill1}}" },
            style: {
              fontSize: 11,
              fontWeight: 600,
              textAlign: "center",
              color: "#c45c26",
              rotate: -4,
            },
            zIndex: 2,
          }),
          b("shape", {
            name: "Skill chip 2",
            x: 184,
            y: 648,
            w: 120,
            h: 32,
            content: { shape: "rect" },
            style: {
              background: "#fff",
              borderRadius: 16,
              borderWidth: 1,
              borderColor: "#c45c26",
              rotate: 3,
              shadow: true,
            },
            zIndex: 1,
          }),
          b("text", {
            name: "Skill 2 label",
            x: 184,
            y: 654,
            w: 120,
            h: 22,
            content: { text: "{{skill2}}" },
            style: {
              fontSize: 11,
              fontWeight: 600,
              textAlign: "center",
              color: "#c45c26",
              rotate: 3,
            },
            zIndex: 2,
          }),
          b("shape", {
            name: "Skill chip 3",
            x: 320,
            y: 640,
            w: 120,
            h: 32,
            content: { shape: "rect" },
            style: {
              background: "#fff",
              borderRadius: 16,
              borderWidth: 1,
              borderColor: "#c45c26",
              rotate: -2,
              shadow: true,
            },
            zIndex: 1,
          }),
          b("text", {
            name: "Skill 3 label",
            x: 320,
            y: 646,
            w: 120,
            h: 22,
            content: { text: "{{skill3}}" },
            style: {
              fontSize: 11,
              fontWeight: 600,
              textAlign: "center",
              color: "#c45c26",
              rotate: -2,
            },
            zIndex: 2,
          }),
          b("paragraph", {
            name: "Edu",
            x: 48,
            y: 700,
            w: 560,
            h: 64,
            content: {
              text: "{{edu1_degree}} — {{edu1_school}} ({{edu1_years}}) · {{edu2_degree}} — {{edu2_school}} ({{edu2_years}})\n{{languages}}",
            },
            style: { fontSize: 11, color: MUTED, lineHeight: 1.45 },
          }),
          b("text", {
            name: "Footer",
            x: 48,
            y: 900,
            w: 560,
            h: 20,
            content: {
              text: "References available on request · {{website}}",
            },
            style: { fontSize: 10, color: MUTED, fontStyle: "italic", textAlign: "center" },
            pin: { bottom: true, left: true, right: true },
          }),
        ],
        {
          background: PAPER,
          watermark: {
            text: "PORTFOLIO",
            angle: -28,
            opacity: 0.05,
            fontSize: 96,
            color: "#c45c26",
          },
        },
      ),
      page(
        "Case notes",
        [
          b("shape", {
            name: "Mirror accent",
            x: 640,
            y: 0,
            w: 80,
            h: 960,
            content: { shape: "rect", filled: true },
            style: {
              background: "#c45c26",
              opacity: 0.9,
              mirrorX: true,
            },
            zIndex: 0,
            pin: { right: true, top: true, bottom: true },
          }),
          b("text", {
            name: "Letterhead",
            x: 48,
            y: 40,
            w: 520,
            h: 28,
            content: { text: "Case notes — {{full_name}}" },
            style: {
              fontFamily: "display",
              fontSize: 22,
              fontWeight: 700,
              color: INK,
            },
          }),
          b("text", {
            name: "Case 1 head",
            x: 48,
            y: 96,
            w: 520,
            h: 22,
            content: { text: "01 · {{j1_company}}" },
            style: {
              fontFamily: "ui",
              fontSize: 12,
              fontWeight: 700,
              letterSpacing: 1.4,
              textTransform: "uppercase",
              color: "#c45c26",
            },
          }),
          b("paragraph", {
            name: "Case 1",
            x: 48,
            y: 128,
            w: 520,
            h: 150,
            content: {
              text: "As {{j1_title}} ({{j1_period}}):\n\n{{j1_p1}}\n\n{{j1_p2}}\n\n{{j1_p3}}",
            },
            style: { fontSize: 12, lineHeight: 1.55, color: INK },
          }),
          b("text", {
            name: "Case 2 head",
            x: 48,
            y: 310,
            w: 520,
            h: 22,
            content: { text: "02 · {{j2_company}}" },
            style: {
              fontFamily: "ui",
              fontSize: 12,
              fontWeight: 700,
              letterSpacing: 1.4,
              textTransform: "uppercase",
              color: "#c45c26",
            },
          }),
          b("paragraph", {
            name: "Case 2",
            x: 48,
            y: 342,
            w: 520,
            h: 150,
            content: {
              text: "As {{j2_title}} ({{j2_period}}):\n\n{{j2_p1}}\n\n{{j2_p2}}\n\n{{j2_p3}}",
            },
            style: { fontSize: 12, lineHeight: 1.55, color: INK },
          }),
          b("text", {
            name: "Toolkit head",
            x: 48,
            y: 520,
            w: 520,
            h: 22,
            content: { text: "Toolkit" },
            style: {
              fontFamily: "ui",
              fontSize: 12,
              fontWeight: 700,
              letterSpacing: 1.4,
              textTransform: "uppercase",
              color: "#c45c26",
            },
          }),
          b("paragraph", {
            name: "Toolkit",
            x: 48,
            y: 552,
            w: 520,
            h: 64,
            content: {
              text: "{{skill1}} · {{skill2}} · {{skill3}} · {{skill4}} · {{skill5}} · {{skill6}}",
            },
            style: { fontSize: 13, lineHeight: 1.55, color: INK },
          }),
          b("paragraph", {
            name: "Closing",
            x: 48,
            y: 640,
            w: 520,
            h: 80,
            content: {
              text: "I am especially interested in teams that treat design and engineering as one craft. Reach me at {{email}} or {{website}}.",
            },
            style: { fontSize: 12, lineHeight: 1.55, color: MUTED },
          }),
          b("text", {
            name: "Footer",
            x: 48,
            y: 900,
            w: 520,
            h: 18,
            content: { text: "{{role}} · page 2 of 2" },
            style: { fontSize: 9, color: MUTED, textAlign: "center" },
            pin: { bottom: true, left: true, right: true },
          }),
        ],
        {
          background: PAPER,
          watermark: {
            text: "NOTES",
            angle: -24,
            opacity: 0.04,
            fontSize: 88,
            color: "#c45c26",
          },
        },
      ),
    ],
  );
}

/** Showcase surface + block transforms on two pages. */
export function transformsDemo(): Project {
  return shell(
    {
      name: "Transforms studio",
      author: "texLooper samples",
      subject: "Rotate, mirror, surface transform",
      description:
        "Page 1: block rotate / mirror / shadow stamps. Page 2: whole surface mirrored. Page 3: mobile artboard tips.",
    },
    [
      page("Stamps", [
        b("shape", {
          name: "Header bar",
          x: 0,
          y: 0,
          w: 720,
          h: 72,
          content: { shape: "rect", filled: true },
          style: { background: "#eef2f7" },
          zIndex: 0,
          pin: { top: true, left: true, right: true },
        }),
        b("text", {
          name: "Title",
          x: 48,
          y: 20,
          w: 500,
          h: 36,
          content: { text: "Block transforms" },
          style: {
            fontFamily: "display",
            fontSize: 28,
            fontWeight: 700,
            color: INK,
          },
          zIndex: 1,
        }),
        b("paragraph", {
          name: "Hint",
          x: 48,
          y: 96,
          w: 624,
          h: 72,
          content: {
            text: "Select any stamp and open Design → Geometry for Rotate ° and Mirror H/V. Surface transform lives under Design when nothing is selected.\n\nUse these samples to compare resting cards with rotated badges in the same composition.",
          },
          style: { fontSize: 12, lineHeight: 1.5, color: MUTED },
        }),
        b("shape", {
          name: "Approved",
          x: 80,
          y: 200,
          w: 140,
          h: 48,
          content: { shape: "rect" },
          style: {
            background: "#0f6b63",
            borderRadius: 6,
            rotate: -12,
            shadow: true,
          },
          zIndex: 1,
        }),
        b("text", {
          name: "Approved label",
          x: 80,
          y: 212,
          w: 140,
          h: 24,
          content: { text: "APPROVED" },
          style: {
            fontFamily: "ui",
            fontSize: 14,
            fontWeight: 700,
            textAlign: "center",
            color: "#fff",
            letterSpacing: 2,
            rotate: -12,
          },
          zIndex: 2,
        }),
        b("shape", {
          name: "Draft badge",
          x: 280,
          y: 220,
          w: 120,
          h: 120,
          content: { shape: "ellipse" },
          style: {
            background: "#c45c26",
            opacity: 0.85,
            rotate: 22,
            shadow: true,
          },
          zIndex: 1,
        }),
        b("text", {
          name: "Draft label",
          x: 290,
          y: 262,
          w: 100,
          h: 36,
          content: { text: "DRAFT" },
          style: {
            fontFamily: "ui",
            fontSize: 16,
            fontWeight: 700,
            textAlign: "center",
            color: "#fff",
            rotate: 22,
          },
          zIndex: 2,
        }),
        b("text", {
          name: "Mirrored copy",
          x: 440,
          y: 240,
          w: 200,
          h: 40,
          content: { text: "Mirror H →" },
          style: {
            fontFamily: "ui",
            fontSize: 18,
            fontWeight: 700,
            color: "#2383e2",
            mirrorX: true,
          },
        }),
        b("paragraph", {
          name: "Stamp notes",
          x: 48,
          y: 380,
          w: 624,
          h: 64,
          content: {
            text: "Rotated stamps are still editable blocks — change copy, fill, or opacity without losing the transform. Mirrored text flips glyphs but keeps the same bounding box for layout.",
          },
          style: { fontSize: 12, lineHeight: 1.5, color: INK },
        }),
        b("shape", {
          name: "Card",
          x: 80,
          y: 480,
          w: 280,
          h: 140,
          content: { shape: "rect" },
          style: {
            background: "#f2f4f7",
            borderRadius: 12,
            padding: 16,
            borderWidth: 1,
            borderColor: "#d4d9e0",
            shadow: true,
          },
        }),
        b("paragraph", {
          name: "Card text",
          x: 96,
          y: 504,
          w: 248,
          h: 100,
          content: {
            text: "Padding, radius, border, and shadow on a resting card — no rotation. Contrast this with the stamps above.",
          },
          style: { fontSize: 12, lineHeight: 1.5, color: INK },
        }),
        b("text", {
          name: "Flip V label",
          x: 400,
          y: 520,
          w: 220,
          h: 32,
          content: { text: "Flip vertical" },
          style: {
            fontFamily: "display",
            fontSize: 22,
            color: INK,
            mirrorY: true,
          },
        }),
        b("paragraph", {
          name: "Bottom tip",
          x: 48,
          y: 680,
          w: 624,
          h: 80,
          content: {
            text: "Page two mirrors the entire surface. Deselect all blocks, then use Design → Transform → Mirror horizontally. Rotate a few degrees to preview print proofs at an angle.",
          },
          style: { fontSize: 12, lineHeight: 1.55, color: MUTED },
        }),
        b("text", {
          name: "Footer",
          x: 48,
          y: 900,
          w: 624,
          h: 18,
          content: { text: "Transforms studio · page 1 of 2" },
          style: { fontSize: 9, color: MUTED, textAlign: "center" },
          pin: { bottom: true, left: true, right: true },
        }),
      ]),
      page(
        "Mirrored surface",
        [
          b("shape", {
            name: "Header bar",
            x: 0,
            y: 0,
            w: 720,
            h: 64,
            content: { shape: "rect", filled: true },
            style: { background: "#e8eef8" },
            zIndex: 0,
            pin: { top: true, left: true, right: true },
          }),
          b("text", {
            name: "Notice",
            x: 64,
            y: 96,
            w: 592,
            h: 48,
            content: { text: "This whole surface is mirrored horizontally" },
            style: {
              fontFamily: "display",
              fontSize: 24,
              fontWeight: 700,
              color: INK,
            },
          }),
          b("paragraph", {
            name: "Body",
            x: 64,
            y: 164,
            w: 592,
            h: 120,
            content: {
              text: "Deselect all blocks → Design → Transform → Mirror horizontally. Rotate the surface a few degrees to preview print proofs at an angle.\n\nBlocks below stay editable; the mirror applies at the page level so you can proof RTL-like layouts without rewriting content.",
            },
            style: { fontSize: 13, lineHeight: 1.55, color: MUTED },
          }),
          b("shape", {
            name: "Arrow",
            x: 64,
            y: 320,
            w: 220,
            h: 56,
            content: { shape: "rect" },
            style: { background: "#2383e2", borderRadius: 8 },
          }),
          b("text", {
            name: "Arrow label",
            x: 64,
            y: 336,
            w: 220,
            h: 24,
            content: { text: "READ → LEFT" },
            style: {
              fontFamily: "ui",
              fontSize: 14,
              fontWeight: 700,
              textAlign: "center",
              color: "#fff",
              letterSpacing: 1,
            },
          }),
          b("paragraph", {
            name: "Checklist",
            x: 64,
            y: 420,
            w: 592,
            h: 160,
            content: {
              text: "Checklist while you explore:\n• Flip mirror off to restore LTR reading order\n• Combine with a light page rotate for desk proofs\n• Keep chrome pinned so letterheads stay edge-true\n• Compare with page one stamps for block-level transforms",
            },
            style: { fontSize: 12, lineHeight: 1.55, color: INK },
          }),
          b("text", {
            name: "Footer",
            x: 64,
            y: 900,
            w: 592,
            h: 18,
            content: { text: "Transforms studio · mirrored surface · page 2" },
            style: { fontSize: 9, color: MUTED, textAlign: "center" },
            pin: { bottom: true, left: true, right: true },
          }),
        ],
        { mirrorX: true, background: "#f8fafc" },
      ),
      page(
        "Mobile artboard",
        [
          b("shape", {
            name: "Phone frame",
            x: 180,
            y: 48,
            w: 360,
            h: 720,
            content: { shape: "rect", filled: false },
            style: {
              background: "transparent",
              borderWidth: 3,
              borderColor: INK,
              borderRadius: 28,
            },
          }),
          b("shape", {
            name: "Notch",
            x: 300,
            y: 60,
            w: 120,
            h: 12,
            content: { shape: "rect", filled: true },
            style: { background: INK, borderRadius: 6 },
          }),
          b("text", {
            name: "Title",
            x: 200,
            y: 100,
            w: 320,
            h: 36,
            content: { text: "Mobile canvas" },
            style: {
              fontFamily: "display",
              fontSize: 22,
              fontWeight: 700,
              color: INK,
              textAlign: "center",
            },
          }),
          b("paragraph", {
            name: "Hint",
            x: 200,
            y: 152,
            w: 320,
            h: 110,
            content: {
              text: "Options bar → View → Mobile phone (or Notification) resizes the artboard. This is a fixed end-device target — not a responsive web layout.",
            },
            style: {
              fontSize: 12,
              lineHeight: 1.5,
              color: MUTED,
              textAlign: "center",
            },
          }),
          b("list", {
            name: "Targets",
            x: 220,
            y: 300,
            w: 280,
            h: 160,
            content: {
              items: [
                "Mobile phone — 390×844",
                "Notification — 360×180",
                "Square — 720×720",
                "Landscape — 960×540",
              ],
            },
            style: {
              fontSize: 12,
              lineHeight: 1.55,
              color: INK,
              listStyle: "disc",
            },
          }),
          b("text", {
            name: "Footer",
            x: 64,
            y: 900,
            w: 592,
            h: 18,
            content: { text: "Transforms studio · artboard tips · page 3" },
            style: { fontSize: 9, color: MUTED, textAlign: "center" },
            pin: { bottom: true, left: true, right: true },
          }),
        ],
        { background: "#ffffff" },
      ),
    ],
  );
}
