import type { Project } from "../../document";
import { createId } from "../../document";
import { DEMO_IMG } from "../assets";
import { b, page, shell } from "../helpers";
import { northlineStyleExtras, nlText } from "../brand/northlineStyles";

export function advertisement(): Project {
  const stockistsId = createId();
  const primaryId = createId();
  /** Full-bleed flyer — zero margins so pins/layout stay edge-aligned. */
  const bleed = { top: 0, right: 0, bottom: 0, left: 0 };
  return shell(
    {
      name: "Print advertisement",
      author: "Northline Marketing",
      subject: "Full-bleed retail flyer",
      description:
        "Retail flyer: hero + logo, dynamic promo badge, SKU table, stockists on the back.",
    },
    [
      page(
        "Flyer",
        [
          b("picture", {
            name: "Hero",
            x: 0,
            y: 0,
            w: 720,
            h: 240,
            content: { src: DEMO_IMG.productHero, alt: "Atlas Pack", fit: "cover" },
            zIndex: 0,
          }),
          b("picture", {
            name: "Logo",
            x: 40,
            y: 20,
            w: 120,
            h: 36,
            content: { src: DEMO_IMG.logoMark, alt: "Northline", fit: "contain" },
            zIndex: 2,
          }),
          b("text", {
            name: "Eyebrow",
            x: 40,
            y: 260,
            w: 280,
            h: 18,
            content: { text: "{{eyebrow|default:LIMITED RELEASE}}" },
            style: {
              fontSize: 11,
              fontWeight: 700,
              letterSpacing: 1.2,
              color: "#0f6b63",
            },
          }),
          b("paragraph", {
            name: "Headline EN",
            x: 40,
            y: 284,
            w: 420,
            h: 64,
            content: {
              text: "{{headline|default:Carry less. Arrive ready.}}",
            },
            style: { ...nlText("nl-display"), fontSize: 26 },
            condition: "vars.language != 'fr'",
          }),
          b("text", {
            name: "Headline FR",
            x: 40,
            y: 284,
            w: 420,
            h: 64,
            content: {
              text: "{{headline_fr|default:Voyagez léger. Arrivez prêts.}}",
            },
            style: { ...nlText("nl-display"), fontSize: 26 },
            condition: "vars.language == 'fr'",
          }),
          b("text", {
            name: "Promo badge",
            x: 540,
            y: 256,
            w: 120,
            h: 120,
            content: {
              text: "{{promo_label|default:SAVE}}\n{{promo_amount|default:20%}}",
            },
            style: {
              fontFamily: "ui",
              fontSize: 16,
              fontWeight: 700,
              textAlign: "center",
              color: "#ffffff",
              background: "#c45c26",
              borderRadius: 999,
              padding: 18,
              lineHeight: 1.25,
              rotate: -8,
              shadow: true,
              verticalAlign: "middle",
            },
            zIndex: 3,
          }),
          b("paragraph", {
            name: "Body",
            x: 40,
            y: 360,
            w: 460,
            h: 88,
            content: {
              text: "{{offer_copy}}\n\nValid through {{valid_until|date:short}}. Free shipping over €120. Code {{promo_code}}.",
            },
            style: { fontSize: 12, color: "#3d4a5c", lineHeight: 1.5 },
          }),
          b("table", {
            name: "SKUs",
            x: 40,
            y: 464,
            w: 400,
            h: 140,
            content: {
              header: true,
              zebra: true,
              sourcePath: "skus",
              rows: 2,
              cols: 3,
              cells: [
                ["SKU", "Color", "Price"],
                ["{{sku}}", "{{color}}", "{{price|currency:EUR}}"],
              ],
              headerBackground: "#e8f0ee",
              cellPadding: 8,
              borderColor: "#cfc8bc",
            },
            style: { fontSize: 12 },
          }),
          b("text", {
            name: "CTA",
            x: 468,
            y: 464,
            w: 200,
            h: 140,
            content: { text: "{{cta}}\n{{store_url}}" },
            style: {
              fontSize: 14,
              fontWeight: 700,
              color: "#ffffff",
              textAlign: "center",
              lineHeight: 1.45,
              background: "#0f6b63",
              borderRadius: 6,
              padding: 24,
              verticalAlign: "middle",
            },
            zIndex: 2,
          }),
          b("paragraph", {
            name: "Retail note",
            x: 40,
            y: 628,
            w: 640,
            h: 64,
            content: {
              text: "Ask for Atlas Pack at {{stockist_summary}} — or order online with code {{promo_code}}. Returns within 30 days in unused condition.",
            },
            style: { fontSize: 11, color: "#5c6570", lineHeight: 1.45 },
          }),
          b("text", {
            name: "Print QR hint",
            x: 500,
            y: 708,
            w: 168,
            h: 36,
            content: { text: "Scan for stock · print only" },
            style: {
              fontSize: 10,
              color: "#5c6570",
              textAlign: "center",
              background: "#f2f4f7",
              padding: 8,
              borderRadius: 4,
            },
            condition: "output.kind == 'pdf' || output.kind == 'print'",
          }),
          b("text", {
            name: "Footer",
            x: 40,
            y: 920,
            w: 640,
            h: 20,
            content: {
              text: "PRINT LOT {{lot}} · {{device.dpi}}dpi · {{store_url}}",
            },
            style: { fontSize: 9, color: "#5c6570", textAlign: "center" },
          }),
        ],
        { spread: false, margins: bleed },
      ),
      page(
        "Back",
        [
          b("picture", {
            name: "Logo",
            x: 40,
            y: 36,
            w: 120,
            h: 36,
            content: { src: DEMO_IMG.logoMark, alt: "Northline", fit: "contain" },
          }),
          b("text", {
            name: "Back kicker",
            x: 180,
            y: 40,
            w: 500,
            h: 28,
            content: { text: "ATLAS PACK · BACK OF FLYER" },
            style: {
              fontSize: 11,
              fontWeight: 700,
              letterSpacing: 1.4,
              color: "#0f6b63",
              verticalAlign: "middle",
            },
          }),
          b("paragraph", {
            name: "Back headline",
            x: 40,
            y: 88,
            w: 640,
            h: 48,
            content: { text: "{{headline}}" },
            style: {
              fontSize: 24,
              fontWeight: 700,
              color: "#1c2430",
              fontFamily: "display",
              lineHeight: 1.2,
            },
          }),
          b("shape", {
            name: "Accent rule",
            x: 40,
            y: 148,
            w: 120,
            h: 3,
            content: { shape: "rect", filled: true },
            style: { background: "#0f6b63" },
          }),
          b("text", {
            name: "Why label",
            x: 40,
            y: 172,
            w: 360,
            h: 20,
            content: { text: "WHY ATLAS PACK" },
            style: {
              fontSize: 11,
              fontWeight: 700,
              letterSpacing: 1.5,
              color: "#0f6b63",
            },
          }),
          b("list", {
            name: "Why list",
            x: 40,
            y: 200,
            w: 360,
            h: 200,
            content: {
              items: [
                "Water-resistant seams rated for 200 cycles",
                "Laptop sleeve fits up to 16-inch devices",
                "Lifetime stitching guarantee",
                "Recycled shell — 68% ocean-bound plastic",
                "Quiet zippers and padded harness for all-day wear",
              ],
              markerColor: "#0f6b63",
            },
            style: { fontSize: 12, lineHeight: 1.55, color: "#3d4a5c" },
          }),
          b("picture", {
            name: "Detail shot",
            x: 432,
            y: 172,
            w: 248,
            h: 228,
            content: {
              src: DEMO_IMG.productDetail,
              alt: "Atlas Pack detail",
              fit: "cover",
            },
            style: { borderRadius: 8 },
          }),
          b("text", {
            name: "Stockists label",
            x: 40,
            y: 432,
            w: 360,
            h: 20,
            content: { text: "ALSO IN STORE" },
            style: {
              fontSize: 11,
              fontWeight: 700,
              letterSpacing: 1.5,
              color: "#0f6b63",
            },
          }),
          b("table", {
            name: "Stockists",
            x: 40,
            y: 460,
            w: 360,
            h: 132,
            content: {
              header: true,
              zebra: true,
              datasetName: "stockists",
              rows: 2,
              cols: 2,
              cells: [
                ["Store", "City"],
                ["{{store}}", "{{city}}"],
              ],
              headerBackground: "#e8f0ee",
              cellPadding: 8,
            },
            style: { fontSize: 12 },
          }),
          b("text", {
            name: "Coupon code",
            x: 432,
            y: 432,
            w: 248,
            h: 160,
            content: {
              text: "{{cta}}\n{{promo_code}}\nSave {{promo_amount}}",
            },
            style: {
              fontSize: 15,
              fontWeight: 700,
              color: "#1c2430",
              textAlign: "center",
              lineHeight: 1.45,
              background: "#f7f3ec",
              borderRadius: 8,
              padding: 20,
              verticalAlign: "middle",
            },
          }),
          b("text", {
            name: "Offer label",
            x: 40,
            y: 616,
            w: 400,
            h: 20,
            content: { text: "THIS WEEK'S LINE-UP" },
            style: {
              fontSize: 11,
              fontWeight: 700,
              letterSpacing: 1.5,
              color: "#0f6b63",
            },
          }),
          b("table", {
            name: "Fine offer table",
            x: 40,
            y: 644,
            w: 640,
            h: 120,
            content: {
              header: true,
              zebra: true,
              sourcePath: "skus",
              rows: 2,
              cols: 3,
              cells: [
                ["Model", "Finish", "Launch price"],
                ["{{sku}}", "{{color}}", "{{price|currency:EUR}}"],
              ],
              headerBackground: "#e8f0ee",
              cellPadding: 8,
            },
            style: { fontSize: 11 },
          }),
          b("paragraph", {
            name: "Small print",
            x: 40,
            y: 788,
            w: 640,
            h: 64,
            content: {
              text: "Offer valid through {{valid_until|date:short}} while stocks last. Prices include VAT. Full terms: {{store_url}}/terms. Soy-based inks · Lot {{lot}}.",
            },
            style: { fontSize: 10, lineHeight: 1.45, color: "#5c6570" },
          }),
          b("text", {
            name: "Footer",
            x: 40,
            y: 920,
            w: 640,
            h: 20,
            content: { text: "{{lot}} · {{store_url}}" },
            style: { fontSize: 9, color: "#5c6570", textAlign: "center" },
          }),
        ],
        { spread: false, margins: bleed },
      ),

    ],
    {
      primaryDatasetId: primaryId,
      datasets: [
        { id: primaryId, name: "primary", rows: [] },
        {
          id: stockistsId,
          name: "stockists",
          rows: [
            { store: "Northline Flagship", city: "Antwerp" },
            { store: "Brightline Co.", city: "Lisbon" },
            { store: "Kanaal Goods", city: "Rotterdam" },
          ],
        },
      ],
      ...northlineStyleExtras("en"),
    },
  );
}

